### ISSUE TITLE
switch 开关 设置size没用

### ISSUE THREAD

**Issue by nincompoopH** [Moonofweisheng/wot-design-uni#107]
### Wot Design Uni 版本号

0.1.41

### 平台

h5

### 重现链接

https://gitee.com/Moonofweisheng/wot-design-uni/blob/master/src/pages/search/Index.vue

### 重现步骤

设置size没用

### 期望的结果是什么？

可以改变大小

### 实际的结果是什么？

没改变

**Comment by Moonofweisheng** [comment]
15ffa1f9172d3c11722c71ca370c1016e25f2b41
