### ISSUE TITLE
ConfigProvider 全局配置 自定义主题色无效

### ISSUE THREAD

**Issue by Lron-boy** [Moonofweisheng/wot-design-uni#133]
1. 版本 0.1.62
2. 按照主题文档来写配置无效

**package.json**
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/61782856/5ac68069-68eb-4a29-bd96-485ce267c333)

**页面文件**
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/61782856/7ddfa802-eea7-4887-a7ec-8d29d0a566cf)

**Comment by Lron-boy** [comment]
是否只可以单个组件的颜色，能否修改全局主色呢

**Comment by Moonofweisheng** [comment]
> 是否只可以单个组件的颜色，能否修改全局主色呢

包裹在config-provider组件中的wot-design-uni的组件都支持自定义css变量，

**Comment by Lron-boy** [comment]
> > 是否只可以单个组件的颜色，能否修改全局主色呢
> 
> 包裹在config-provider组件中的wot-design-uni的组件都支持自定义css变量，

我的意思是能否支持传入一个变量，修改所有组件的主色，例如您现在的颜色是蓝色的，我页面有按钮，有tab等等，我传入一个主色变量，可以同时修改两个组件的变量，我看文档，好像只可以通过css去修改全局的主色

**Comment by Moonofweisheng** [comment]
> > > 是否只可以单个组件的颜色，能否修改全局主色呢
> > 
> > 
> > 包裹在config-provider组件中的wot-design-uni的组件都支持自定义css变量，
> 
> 我的意思是能否支持传入一个变量，修改所有组件的主色，例如您现在的颜色是蓝色的，我页面有按钮，有tab等等，我传入一个主色变量，可以同时修改两个组件的变量，我看文档，好像只可以通过css去修改全局的主色

使用公共主题色变量的组件，就可以通过重新定义公共主体色变量的方式实现全局修改的

**Comment by Moonofweisheng** [comment]
> > > 是否只可以单个组件的颜色，能否修改全局主色呢
> > 
> > 
> > 包裹在config-provider组件中的wot-design-uni的组件都支持自定义css变量，
> 
> 我的意思是能否支持传入一个变量，修改所有组件的主色，例如您现在的颜色是蓝色的，我页面有按钮，有tab等等，我传入一个主色变量，可以同时修改两个组件的变量，我看文档，好像只可以通过css去修改全局的主色

目前关于组件css变量的介绍，在组件库后续计划中会在每个组件文档下方给出的，到时候可以比较直观的看到哪些变量是受全局变量影响的。

**Comment by Lron-boy** [comment]
> > > > 是否只可以单个组件的颜色，能否修改全局主色呢
> > > 
> > > 
> > > 包裹在config-provider组件中的wot-design-uni的组件都支持自定义css变量，
> > 
> > 
> > 我的意思是能否支持传入一个变量，修改所有组件的主色，例如您现在的颜色是蓝色的，我页面有按钮，有tab等等，我传入一个主色变量，可以同时修改两个组件的变量，我看文档，好像只可以通过css去修改全局的主色
> 
> 目前关于组件css变量的介绍，在组件库后续计划中会在每个组件文档下方给出的，到时候可以比较直观的看到哪些变量是受全局变量影响的。

好的，谢谢，辛苦了
