### ISSUE TITLE
增加单位可配置功能

### ISSUE THREAD

**Issue by zhongwuhuang** [Moonofweisheng/wot-design-uni#145]
### 这个功能解决了什么问题？

想使用rpx的单位，该库好像默认使用的是px，rpx可以适配不同屏幕的手机让组件自适应屏幕，可以增加一个配置入口吗

### 你期望的 API 是什么样子的？

类似于uview的 uni.$u.config.unit = 'rpx'

**Comment by zhongwuhuang** [comment]
大哥，这个功能会做吗

**Comment by Moonofweisheng** [comment]
这个应该有一些插件可以做到，px2rpx或者pxtorpx，如果找不到的话后面我可以开发一个，最近在养病，还没时间开发。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月4日(周一) 上午9:23
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [Moonofweisheng/wot-design-uni] 增加单位可配置功能 (Issue #145)




 
大哥，这个功能会做吗

**Comment by zhongwuhuang** [comment]
> 这个应该有一些插件可以做到，px2rpx或者pxtorpx，如果找不到的话后面我可以开发一个，最近在养病，还没时间开发。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年12月4日(周一) 上午9:23 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: Re: [Moonofweisheng/wot-design-uni] 增加单位可配置功能 (Issue #145) 大哥，这个功能会做吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

大佬辛苦了，这个库ui很赞，还是希望可配置，用插件转怕出问题

**Comment by zhongwuhuang** [comment]
关于单位这个问题应该算是设计层面的问题，从一开始开发就要考虑

**Comment by ehangwork** [comment]
同样有这方面需求，希望能增加配置，大佬。

**Comment by Qiu-Jun** [comment]
> ### 这个功能解决了什么问题？
> 想使用rpx的单位，该库好像默认使用的是px，rpx可以适配不同屏幕的手机让组件自适应屏幕，可以增加一个配置入口吗
> 
> ### 你期望的 API 是什么样子的？
> 类似于uview的 uni.$u.config.unit = 'rpx'



> 关于单位这个问题应该算是设计层面的问题，从一开始开发就要考虑

是的，uview plus好像有这么一个配置，但是那个vue3版的bug真的多

**Comment by longshao5520** [comment]
现在我使用postcss转换会造成table的显示异常

**Comment by zhaoyunyes** [comment]
https://developers.weixin.qq.com/miniprogram/design/adapt.html#%E6%A6%82%E8%BF%B0

小程序也支持横屏了 看起来以后不要rpx这样的等比缩放方案了。直接用响应式设计方案吧。

**Comment by linshenghao** [comment]
@Moonofweisheng 同样也有宽屏适配的需求，不只是平板，我们项目中涉及到终端机，终端机尺寸和我们目前的手机比例一直，之前我是px转rpx，再设置uni-app的globalStyle解决大屏的适配问题，但是wot好像做了配置也不生效，希望能给一个统一单位配置

**Comment by Moonofweisheng** [comment]
> @Moonofweisheng 同样也有宽屏适配的需求，不只是平板，我们项目中涉及到终端机，终端机尺寸和我们目前的手机比例一直，之前我是px转rpx，再设置uni-app的globalStyle解决大屏的适配问题，但是wot好像做了配置也不生效，希望能给一个统一单位配置

目前大多数组件已经移除行内样式中的px，可以使用postcss插件尝试将px转成rpx
