### ISSUE TITLE
notify 无效

### ISSUE THREAD

**Issue by jamarion126** [Moonofweisheng/wot-design-uni#148]
### Wot Design Uni 版本号

^0.1.68

### 平台

h5

### 重现链接

无

### 重现步骤

1. 引入 notify 组件在 template
```js
<wd-notify />
```
2. 导入hooks
```js
import { useMessage, useNotify } from "wot-design-uni";
```
3. 使用hooks
```js
showNotify({ type: "success", message: "success" });
```

### 期望的结果是什么？

notify显示在页面

### 实际的结果是什么？

无显示

### 环境信息

- H5平台
- Google Chrome 120.0.6099.71
- vue cli
- uniapp版本 3.0.0-3081220230817001

### 其他补充信息

无

**Comment by Moonofweisheng** [comment]
使用示例参考，<wd-notify />上如果没有传入selector，useNotify就不需要传入参数了
```
import { useNotify } from "wot-design-uni"
const { showNotify, closeNotify } = useNotify()
showNotify('通知内容')
```

**Comment by jamarion126** [comment]
> 使用示例参考修改，如果没有格式化选择器，useNotify就不需要格式化参数了，这一点文档上有误，会。
> 
> ```
> import { useNotify } from "wot-design-uni"
> const { showNotify, closeNotify } = useNotify()
> showNotify('通知内容')
> ```

是的，不传入 `selector` 后成功
