### ISSUE TITLE
[新功能需求] wd-loadmore遇到深色背景色时无法调整字颜色

### ISSUE THREAD

**Issue by BillionChen** [Moonofweisheng/wot-design-uni#150]
### 这个功能解决了什么问题？

wd-loadmore遇到深色背景色时无法调整字颜色

### 你期望的 API 是什么样子的？

<wd-loadmore color="white" />

**Comment by Moonofweisheng** [comment]
是手机深色主题吗？能否给个复现demo

**Comment by BillionChen** [comment]
不是 就是我们有的页面是黑色底色，例如视频列表这样的，需要调整这个加载更多及无更多的字体颜色，或者你直接提供一个type=dark也行

**Comment by Moonofweisheng** [comment]
> 不是 就是我们有的页面是黑色底色，例如视频列表这样的，需要调整这个加载更多及无更多的字体颜色，或者你直接提供一个type=dark也行

使用custom-class或者穿透应该可以实现的

**Comment by Moonofweisheng** [comment]
使用custom-class或者自定义css变量实现
