### ISSUE TITLE
[Bug 上报] input中设置readonly不显示placeholder和suffix-icon

### ISSUE THREAD

**Issue by ywb312** [Moonofweisheng/wot-design-uni#151]
### Wot Design Uni 版本号

0.1.69

### 平台

h5, APP

### 重现链接

无

### 重现步骤

![image](https://github.com/Moonofweisheng/wot-design-uni/assets/42398546/4cea840b-a9fb-43cd-bf4c-6efe847bf9c2)

图中红框是设置readonly和没设置readonly的对比，disabled没问题，readonly就会这样

### 期望的结果是什么？

设置readonly显示placeholder和suffix-icon

### 实际的结果是什么？

input中设置readonly不显示placeholder和suffix-icon

**Comment by Moonofweisheng** [comment]
下个版本修复
