### ISSUE TITLE
[Bug 上报] picker组件在ios上渲染有误

### ISSUE THREAD

**Issue by ywb312** [Moonofweisheng/wot-design-uni#152]
### Wot Design Uni 版本号

0.1.69

### 平台

APP

### 重现链接

无

### 重现步骤

iphone 8上picker唤起后是只有一个选项，选项值为传入的columns。安卓可正常解析并渲染成多个选项。

### 期望的结果是什么？

picker正常渲染

### 实际的结果是什么？

唤起picker只有一个columns数组的选项

**Comment by Moonofweisheng** [comment]
hbx是最新的版本吗

**Comment by ywb312** [comment]
> hbx是最新的版本吗

hbx是最新的，但依赖还是<Vue3-Uni-TS-快速上手模板>里的版本。

**Comment by ywb312** [comment]
> hbx是最新的版本吗

hbx是最新的，但依赖还是<Vue3-Uni-TS-快速上手模板>里的版本。

**Comment by Moonofweisheng** [comment]
> > hbx是最新的版本吗
> 
> hbx是最新的，但依赖还是<Vue3-Uni-TS-快速上手模板>里的版本。

之前有人反馈过 不过把hbx升级到最新就没这个问题了，可以把复现demo贴一下吗

**Comment by ywb312** [comment]
> > > hbx是最新的版本吗
> > 
> > 
> > hbx是最新的，但依赖还是<Vue3-Uni-TS-快速上手模板>里的版本。
> 
> 之前有人反馈过 不过把hbx升级到最新就没这个问题了，可以把复现demo贴一下吗

大佬，发现问题了。试了本地静态数据、setTimeout模拟请求，在ios都是正常的。就是接口查询回来的数据有问题`columns.value=res.data`，直接赋值在ios会出问题。拿到数据后深拷贝就可以解决。
