### ISSUE TITLE
[Bug 上报] wd-picker组件用于选择出生年份，在Android上回显不成功，小程序上回显正常

### ISSUE THREAD

**Issue by Mengrongrong** [Moonofweisheng/wot-design-uni#157]
### Wot Design Uni 版本号

0.1.66

### 平台

APP

### 重现链接

暂时没有

### 重现步骤

1、选中日期，显示成功
2、退出该界面，重新界面此界面，没有回显之前选中的值
（小程序上是正常的）

### 期望的结果是什么？

能够正常回显
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/42793434/b23169e5-121c-491c-9a31-3782f81d4335)

### 实际的结果是什么？

不能正常回显
![Screenshot_20231226_182828](https://github.com/Moonofweisheng/wot-design-uni/assets/42793434/61c6fd57-d3de-4d2c-a5ab-2a08b7349679)

### 环境信息

发行平台：Android
uniapp: 3.0.0-3081220230817001
操作系统：鸿蒙4.0

**Comment by Moonofweisheng** [comment]
请将测试数据补充一下。

**Comment by Mengrongrong** [comment]
const formatAge = (items: { value: number; label: string }) => {
  return items.value == -1 ? "保密" : `${items.value - 2}岁`
}

yearList = [{"value":-1,"label":"保密"},{"value":2,"label":"2023年"},{"value":3,"label":"2022年"},{"value":4,"label":"2021年"},{"value":5,"label":"2020年"},{"value":6,"label":"2019年"},{"value":7,"label":"2018年"},{"value":8,"label":"2017年"},{"value":9,"label":"2016年"},{"value":10,"label":"2015年"},{"value":11,"label":"2014年"},{"value":12,"label":"2013年"},{"value":13,"label":"2012年"},{"value":14,"label":"2011年"},{"value":15,"label":"2010年"},{"value":16,"label":"2009年"},{"value":17,"label":"2008年"},{"value":18,"label":"2007年"},{"value":19,"label":"2006年"},{"value":20,"label":"2005年"},{"value":21,"label":"2004年"},{"value":22,"label":"2003年"},{"value":23,"label":"2002年"},{"value":24,"label":"2001年"},{"value":25,"label":"2000年"},{"value":26,"label":"1999年"},{"value":27,"label":"1998年"},{"value":28,"label":"1997年"},{"value":29,"label":"1996年"},{"value":30,"label":"1995年"},{"value":31,"label":"1994年"},{"value":32,"label":"1993年"},{"value":33,"label":"1992年"},{"value":34,"label":"1991年"},{"value":35,"label":"1990年"},{"value":36,"label":"1989年"},{"value":37,"label":"1988年"},{"value":38,"label":"1987年"},{"value":39,"label":"1986年"},{"value":40,"label":"1985年"},{"value":41,"label":"1984年"},{"value":42,"label":"1983年"},{"value":43,"label":"1982年"},{"value":44,"label":"1981年"},{"value":45,"label":"1980年"},{"value":46,"label":"1979年"},{"value":47,"label":"1978年"},{"value":48,"label":"1977年"},{"value":49,"label":"1976年"},{"value":50,"label":"1975年"},{"value":51,"label":"1974年"},{"value":52,"label":"1973年"},{"value":53,"label":"1972年"},{"value":54,"label":"1971年"},{"value":55,"label":"1970年"},{"value":56,"label":"1969年"},{"value":57,"label":"1968年"},{"value":58,"label":"1967年"},{"value":59,"label":"1966年"},{"value":60,"label":"1965年"},{"value":61,"label":"1964年"},{"value":62,"label":"1963年"},{"value":63,"label":"1962年"},{"value":64,"label":"1961年"},{"value":65,"label":"1960年"},{"value":66,"label":"1959年"},{"value":67,"label":"1958年"},{"value":68,"label":"1957年"},{"value":69,"label":"1956年"},{"value":70,"label":"1955年"},{"value":71,"label":"1954年"},{"value":72,"label":"1953年"},{"value":73,"label":"1952年"},{"value":74,"label":"1951年"},{"value":75,"label":"1950年"}]

      <wd-picker
        label="年龄"
        v-model="age"
        :columns="yearList"
        title="选择出生年份"
        @confirm="doAgeSelect"
        :display-format="formatAge"
      />

**Comment by Moonofweisheng** [comment]
升级至0.2.x可修复
