### ISSUE TITLE
[Bug 上报] APP是时间选择使用插槽后，不能关闭弹窗

### ISSUE THREAD

**Issue by ywb312** [Moonofweisheng/wot-design-uni#164]
### Wot Design Uni 版本号

0.2.15

### 平台

APP

### 重现链接

无

### 重现步骤

use-default-slot后选择时间confirm时间不关闭弹窗。H5端可正常关闭，APP端报错TypeError: Cannot read property 'nodeName' of null

```
<wd-datetime-picker v-model="dateTime" :maxDate="maxDate" use-default-slot @confirm="onDateTimeChange">
   <view class="w-full rounded-md overflow-hidden bg-white box-border p-3 space-x-2 flex items-center color-[#A8A8A8]">
    <view class="grow flex items-center">
    <view class="text-[13px]">{{ formData.startTime || "选择开始日期" }}</view>
    </view>
    <view>~</view>
    <view class="grow flex items-center">
      <view class="text-[13px]">{{ formData.endTime || "选择结束日期" }}</view>
      </view>
  </view>
</wd-datetime-picker>

```
```
const maxDate = ref(Date.now());
const dateTime = ref<any[]>([getToday(), Date.now()]);
const formData = ref({
	startTime: formatTimestamp(dateTime.value[0], "YYYY-MM-DD HH:mm"),
	endTime: formatTimestamp(dateTime.value[1], "YYYY-MM-DD HH:mm"),
});
function onDateTimeChange({ value }) {
	formData.value.startTime = formatTimestamp(value[0], "YYYY-MM-DD HH:mm");
	formData.value.endTime = formatTimestamp(value[1], "YYYY-MM-DD HH:mm");
}
```

### 期望的结果是什么？

正常关闭

### 实际的结果是什么？

不关闭并报错

**Comment by Moonofweisheng** [comment]
请问是安卓还是iOS？

**Comment by ywb312** [comment]
> 请问是安卓还是iOS？

都有TypeError: null is not an object (evaluating 'X.nodeName') __ERROR

**Comment by Moonofweisheng** [comment]
昨天尝试过，两个端都无法复现，能否提供一个完整可复现的仓库？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月22日(周一) 上午8:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Moonofweisheng/wot-design-uni] [Bug 上报] 请在此填写标题 (Issue #164)




  
请问是安卓还是iOS？
  
都有TypeError: null is not an object (evaluating 'X.nodeName') __ERROR

**Comment by ywb312** [comment]
> 昨天尝试过，两个端都无法复现，能否提供一个完整可复现的仓库？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年1月22日(周一) 上午8:39 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Moonofweisheng/wot-design-uni] [Bug 上报] 请在此填写标题 (Issue #164) 请问是安卓还是iOS？ 都有TypeError: null is not an object (evaluating 'X.nodeName') __ERROR — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

大佬，发现问题了。我有重复的查询部分，所以封装了个查询业务组件。放到页面是可以正常关闭的，放到组件中会报错。

**Comment by Moonofweisheng** [comment]
> > 昨天尝试过，两个端都无法复现，能否提供一个完整可复现的仓库？
> > […](#)
> > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2024年1月22日(周一) 上午8:39 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: Re: [Moonofweisheng/wot-design-uni] [Bug 上报] 请在此填写标题 (Issue #164) 请问是安卓还是iOS？ 都有TypeError: null is not an object (evaluating 'X.nodeName') __ERROR — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 大佬，发现问题了。我有重复的查询部分，所以封装了个查询业务组件。放到页面是可以正常关闭的，放到组件中会报错。

能否自己解决？不行的话，需要提供一个完整的可以复现的dmeo。
