### ISSUE TITLE
对于Form 针对某一项必填项通过之后，原本其他已经出现了必填提示的，不应该消失，让用户再去点击提交重新校验。

### ISSUE THREAD

**Issue by BeginnerDone** [Moonofweisheng/wot-design-uni#166]
### Wot Design Uni 版本号

0.2.13

### 平台

h5, 微信小程序

### 重现链接

https://wot-design-uni.cn/component/form.html

### 重现步骤

多个必填项，点击提交，显示出必填项提示，输入其中一个必填项，其他必填项提示消失

### 期望的结果是什么？

多个必填项，只填写其中一个，其他已经出现必填项的提示不应该消失

### 实际的结果是什么？

只要填写其中一个必填项，所有的必填项提示全部消失，需要用户再次点击提交，重新校验，感觉这种不太合理

**Comment by Moonofweisheng** [comment]
之前有讨论过，目前计划的实现是，提供开关控制组件是否自动校验，然后某一项变化了之后开发者可以自行校验对应的字段。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Moonofweisheng/wot-design-uni"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月22日(星期一) 下午3:25
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Moonofweisheng/wot-design-uni] 对于Form 针对某一项必填项通过之后，原本其他已经出现了必填提示的，不应该消失，让用户再去点击提交重新校验。 (Issue #166)





 
Wot Design Uni 版本号
 
0.2.13
 
平台
 
h5, 微信小程序
 
重现链接
 
https://wot-design-uni.cn/component/form.html
 
重现步骤
 
多个必填项，点击提交，显示出必填项提示，输入其中一个必填项，其他必填项提示消失
 
期望的结果是什么？
 
多个必填项，只填写其中一个，其他已经出现必填项的提示不应该消失
 
实际的结果是什么？
 
只要填写其中一个必填项，所有的必填项提示全部消失，需要用户再次点击提交，重新校验，感觉这种不太合理
 
环境信息
 
No response
 
其他补充信息
 
No response

**Comment by BeginnerDone** [comment]
> 之前有讨论过，目前计划的实现是，提供开关控制组件是否自动校验，然后某一项变化了之后开发者可以自行校验对应的字段。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Moonofweisheng/wot-design-uni" ***@***.***&gt;; 发送时间:&nbsp;2024年1月22日(星期一) 下午3:25 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[Moonofweisheng/wot-design-uni] 对于Form 针对某一项必填项通过之后，原本其他已经出现了必填提示的，不应该消失，让用户再去点击提交重新校验。 (Issue #166) Wot Design Uni 版本号 0.2.13 平台 h5, 微信小程序 重现链接 https://wot-design-uni.cn/component/form.html 重现步骤 多个必填项，点击提交，显示出必填项提示，输入其中一个必填项，其他必填项提示消失 期望的结果是什么？ 多个必填项，只填写其中一个，其他已经出现必填项的提示不应该消失 实际的结果是什么？ 只要填写其中一个必填项，所有的必填项提示全部消失，需要用户再次点击提交，重新校验，感觉这种不太合理 环境信息 No response 其他补充信息 No response — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

感谢，希望支持。
