### ISSUE TITLE
[Bug 上报] wd-popover 在编译成的支付宝小程序中，mode="menu"时，popup 宽度太窄，无法调整宽度

### ISSUE THREAD

**Issue by AdamZay** [Moonofweisheng/wot-design-uni#169]
### Wot Design Uni 版本号

最新版本

### 平台

支付宝小程序

### 重现链接

。

### 重现步骤

示例代码如下：
<wd-popover v-model="show" mode="menu" :content="menu" @menuclick="link">
          <view style="padding-left: 10rpx" @tap="toast">
            <uv-icon name="list" size="21" bold></uv-icon>
          </view>
        </wd-popover>
        
<img width="98" alt="image" src="https://github.com/Moonofweisheng/wot-design-uni/assets/113489584/05efb7d6-d9ee-47c6-a61d-76a980b8f4b0">

### 期望的结果是什么？

希望弹出的 popup 可以调整宽度，这个内容已经挤不下了

### 实际的结果是什么？

宽度太窄

### 环境信息

uniapp 编译成的支付宝小程序

### 其他补充信息

。

**Comment by AdamZay** [comment]
在中间时没问题，在左右两边时会出现这种问题 bug

**Comment by Moonofweisheng** [comment]
请提供完整复现demo，附件或者提供git仓库

**Comment by Moonofweisheng** [comment]
未提供复现demo
