### ISSUE TITLE
✍️贡献指南

### ISSUE THREAD

**Issue by Moonofweisheng** [Moonofweisheng/wot-design-uni#17]
## 本文讲述如何参与到wot-design-uni的开发工作
修改代码请阅读我们的 [贡献指南](https://github.com/Moonofweisheng/wot-design-uni/blob/master/.github/CONTRIBUTING.md)。

使用过程中发现任何问题都可以提 [Issue](https://github.com/Moonofweisheng/wot-design-uni/issues) 给我们，当然，我们也非常欢迎你给我们发 [PR](https://github.com/Moonofweisheng/wot-design-uni/pulls)。  

欢迎你的加入！

**Comment by soDoEasy** [comment]
更新到1.11.1吗
