### ISSUE TITLE
[Bug 上报] 请在此填写标题

### ISSUE THREAD

**Issue by pengziyun** [Moonofweisheng/wot-design-uni#170]
### Wot Design Uni 版本号

0.2.22

### 平台

微信小程序

### 重现链接

无

### 重现步骤

wd-tabbar 设置fixed不生效

### 期望的结果是什么？

生效

### 实际的结果是什么？

不生效

**Comment by Moonofweisheng** [comment]
需要提供复现dmeo或者复现链接，否则issue将被关闭



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月31日(周三) 晚上7:20
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Moonofweisheng/wot-design-uni] [Bug 上报] 请在此填写标题 (Issue #170)




 
Wot Design Uni 版本号
 
0.2.22
 
平台
 
微信小程序
 
重现链接
 
无
 
重现步骤
 
wd-tabbar 设置fixed不生效
 
期望的结果是什么？
 
生效
 
实际的结果是什么？
 
不生效
 
环境信息
 
No response
 
其他补充信息
 
No response

**Comment by Moonofweisheng** [comment]
组件库demo 微信小程序中有fixed的示例，并未出现issue中提到的问题，请确认后提供复现demo
