### ISSUE TITLE
[Bug 上报] wd-picker初始化页面组件赋值后，label值显示错乱 - 数据源是数组对象类型、value值类型number时

### ISSUE THREAD

**Issue by kaivin** [Moonofweisheng/wot-design-uni#171]
### Wot Design Uni 版本号

0.2.15

### 平台

APP

### 重现链接

无

### 重现步骤

columns的数据源为对象，同时value值为number，初始化时有默认值，此时该组件默认将对象数据显示到了页面上，而不是显示value对应的label值

### 期望的结果是什么？

显示的是正常的label的值，而不是将整个对象数据显示到页面上

### 实际的结果是什么？

将对象数据显示到了该显示label值的地方

**Comment by Moonofweisheng** [comment]
将columns深拷贝赋值一下看看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月31日(周三) 晚上10:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Moonofweisheng/wot-design-uni] [Bug 上报] wd-picker赋值错乱问题 (Issue #171)




 
Wot Design Uni 版本号
 
0.2.15
 
平台
 
APP
 
重现链接
 
无
 
重现步骤
 
columns的数据源为对象，同时value值为number，初始化时有默认值，此时该组件默认将对象数据显示到了页面上，而不是显示value对应的label值
 
期望的结果是什么？
 
显示的是正常的label的值，而不是将整个对象数据显示到页面上
 
实际的结果是什么？
 
将对象数据显示到了该显示label值的地方
 
环境信息
 
No response
 
其他补充信息
 
No response

**Comment by kaivin** [comment]
> 将columns深拷贝赋值一下看看
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年1月31日(周三) 晚上10:18 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [Moonofweisheng/wot-design-uni] [Bug 上报] wd-picker赋值错乱问题 (Issue #171) Wot Design Uni 版本号 0.2.15 平台 APP 重现链接 无 重现步骤 columns的数据源为对象，同时value值为number，初始化时有默认值，此时该组件默认将对象数据显示到了页面上，而不是显示value对应的label值 期望的结果是什么？ 显示的是正常的label的值，而不是将整个对象数据显示到页面上 实际的结果是什么？ 将对象数据显示到了该显示label值的地方 环境信息 No response 其他补充信息 No response — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

深拷贝也无效，这个问题目前只在app端有问题，H5端无问题，我试着将value改成字符串，也无效，而且只在初始化赋值时有问题，唤起弹窗重新选择后，是正常的，但每次进入页面，初始化赋值显示的都直接是那条数据

**Comment by kaivin** [comment]
显示的是整个数组

**Comment by kaivin** [comment]
与[#167](https://github.com/Moonofweisheng/wot-design-uni/issues/167)应该是同一个问题，只不过那个是H5和微信端的问题，我这是安卓APP端，问题展现不同，问题导致的原因应该是一致的，都是初始化请求数据，初始化赋值，然后显示的值存在问题，APP端将数组数据当作字符串显示到了页面上，[#167](https://github.com/Moonofweisheng/wot-design-uni/issues/167)提供的DEMO如果真机APP测试，应该能复现问题

**Comment by kaivin** [comment]
我目前是不做初始化赋值，用起来一切正常，不过有些地方肯定还是设置默认值更符合用户体验的，希望这个问题可以解决一下

**Comment by Moonofweisheng** [comment]
我今天会看，如果需要复现相关的问题，还希望可以帮忙提供。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月1日(周四) 上午9:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Moonofweisheng/wot-design-uni] [Bug 上报] wd-picker初始化页面组件赋值后，label值显示错乱 - 数据源是数组对象类型、value值类型number时 (Issue #171)




 
我目前是不做初始化赋值，用起来一切正常，不过有些地方肯定还是设置默认值更符合用户体验的，希望这个问题可以解决一下

**Comment by Moonofweisheng** [comment]
如果和#167是同一个问题的话可以更新到0.2.19及以后的版本试试。

**Comment by kaivin** [comment]
升级到了0.2.22，问题依然存在，赋值默认值，就会让整个columns数组显示到该显示label的地方

**Comment by Moonofweisheng** [comment]
那你的问题和那个问题应该并非相同问题。请提供一下完整复现demo吧。还有APP是指iOS还是安卓



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月2日(周五) 上午8:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Moonofweisheng/wot-design-uni] [Bug 上报] wd-picker初始化页面组件赋值后，label值显示错乱 - 数据源是数组对象类型、value值类型number时 (Issue #171)




 
升级到了0.2.22，问题依然存在，赋值默认值，就会让整个columns数组显示到该显示label的地方

**Comment by Moonofweisheng** [comment]
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/26426873/5f46d86c-d4b1-444f-a172-9e94750779ca)
#152 看你的描述应该和这个问题是一样的

**Comment by kaivin** [comment]
我将数据重新处理改成使用默认的label和value字段就好了
