### ISSUE TITLE
wd-notify组件zIndex不生效

### ISSUE THREAD

**Issue by BeginnerDone** [Moonofweisheng/wot-design-uni#173]
### Wot Design Uni 版本号

0.2.19

### 平台

h5, 微信小程序

### 重现链接

https://wot-design-uni.cn/component/notify.html

### 重现步骤

通过设置wd-notify中的z-index属性，发现其内部封装的wd-popup中的z-index并没有及时生效

### 期望的结果是什么？

wd-notify的z-index来将其放到最顶层。

### 实际的结果是什么？

会被自定义的navbar给遮住

### 其他补充信息

![微信图片_20240201104126](https://github.com/Moonofweisheng/wot-design-uni/assets/20809153/4b87d002-0d2f-48e0-8879-b55eee695483)
![微信图片_20240201104105](https://github.com/Moonofweisheng/wot-design-uni/assets/20809153/a9c7400d-8c3a-4972-9d06-8299ca983646)

**Comment by Moonofweisheng** [comment]
目前通过props设置z-index确实存在问题，可以先在showNotify中指定，后续会修复这个问题

**Comment by BeginnerDone** [comment]
> 目前通过props设置z-index确实存在问题，可以先在showNotify中指定，后续会修复这个问题

好的，再次感谢。
