### ISSUE TITLE
请问贵组件库支持nvue吗

### ISSUE THREAD

**Issue by geekchenzx** [Moonofweisheng/wot-design-uni#176]
如题

**Comment by Moonofweisheng** [comment]
目前是不支持的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月2日(周五) 晚上11:04
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Moonofweisheng/wot-design-uni] 请问贵组件库支持nvue吗 (Issue #176)




 
如题
