### ISSUE TITLE
[新功能需求]希望提供支付宝小程序相关的开放能力

### ISSUE THREAD

**Issue by Guan-Meng-Yuan** [Moonofweisheng/wot-design-uni#180]
### 这个功能解决了什么问题？

希望提供支付宝小程序相关的开放能力

### 你期望的 API 是什么样子的？

目前1.0版本的各类open-type只提供了微信小程序相关的开放能力

**Comment by Moonofweisheng** [comment]
OK



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月26日(周一) 晚上11:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Moonofweisheng/wot-design-uni] [新功能需求]希望提供支付宝小程序相关的开放能力 (Issue #180)




 
这个功能解决了什么问题？
 
希望提供支付宝小程序相关的开放能力
 
你期望的 API 是什么样子的？
 
目前1.0版本的各类open-type只提供了微信小程序相关的开放能力

**Comment by Moonofweisheng** [comment]
目前看下来，已经支持了uni-app文档中提到的支付宝支持的开放能力，我对比了支付宝与uni-app的文档，uni-app未提供关注生活号API的支持，这一点可以用[lifestyle组件](https://opendocs.alipay.com/mini/component/lifestyle)替代。你看看，是否还有其他的API未支持的？

**Comment by Guan-Meng-Yuan** [comment]
好的，我这边等遇到的时候会再提issue，感谢您
