### ISSUE TITLE
遮罩层 在小程序真机上不会消失

### ISSUE THREAD

**Issue by nincompoopH** [Moonofweisheng/wot-design-uni#183]
### Wot Design Uni 版本号

0.2.16

### 平台

微信小程序

### 重现链接

https://gitee.com/Moonofweisheng/wot-design-uni/blob/master/src/pages/search/Index.vue

### 重现步骤

![~V84J7%}}`MLSL_~QG{~EZU](https://github.com/Moonofweisheng/wot-design-uni/assets/34291443/3303d4a8-5360-4205-a3de-9d19aef2623b)

https://github.com/Moonofweisheng/wot-design-uni/assets/34291443/1b471014-afd3-43c6-bb6a-14462fc53571

需要用真机调试才可以
[wot-design-uniDemo.zip](https://github.com/Moonofweisheng/wot-design-uni/files/14456741/wot-design-uniDemo.zip)

### 期望的结果是什么？

遮罩层消失

### 实际的结果是什么？

没有消失

### 环境信息

微信小程序

### 其他补充信息

微信小程序真机才会显示

**Comment by Moonofweisheng** [comment]
[v1.1.8](https://github.com/Moonofweisheng/wot-design-uni/releases/tag/v1.1.8)
