### ISSUE TITLE
我在使用wd-tabbar时发现使用简写的boolean属性值fixed不生效，必须:fixed="true"，不确定其他boolean属性也是不是这样，如果不是，是否可以支持一下

### ISSUE THREAD

**Issue by pengziyun** [Moonofweisheng/wot-design-uni#184]
### 这个功能解决了什么问题？

精简boolean的属性代码

### 你期望的 API 是什么样子的？

<wd-tabbar v-model="activeTabbar" fixed safe-area-inset-bottom>
    <wd-tabbar-item v-for="(tabbar, index) in tabbarList" :key="index" :title="tabbar.title" :name="tabbar.name">
      <template #icon>
        <wd-icon :name="tabbar.icon"></wd-icon>
      </template>
    </wd-tabbar-item>
  </wd-tabbar>

**Comment by Moonofweisheng** [comment]
提供下复现demo看看。

**Comment by Moonofweisheng** [comment]
你可以拉取组件库代码本地跑一下，所有布尔值简写均正常的。

**Comment by pengziyun** [comment]
刚刚试了下，若是我引入了unocss，则fixed简写失效

**Comment by Moonofweisheng** [comment]
猜测，unocss将fixed当作样式处理了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Moonofweisheng/wot-design-uni"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月4日(星期一) 下午5:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Moonofweisheng/wot-design-uni] 我在使用wd-tabbar时发现使用简写的boolean属性值fixed不生效，必须:fixed="true"，不确定其他boolean属性也是不是这样，如果不是，是否可以支持一下 (Issue #184)





 
刚刚试了下，若是我引入了unocss，则fixed简写失效

**Comment by Moonofweisheng** [comment]
可以看下是否是[attributify](https://unocss.dev/presets/attributify#properties-conflicts)导致的
