### ISSUE TITLE
tab标签增加选中底部横线颜色

### ISSUE THREAD

**Issue by HFhefeng** [Moonofweisheng/wot-design-uni#187]
### 这个功能解决了什么问题？

目前好像没有这个功能，希望有这个功能  可以选择文字颜色，我觉得也应该有个匹配的active 底部选中颜色

### 你期望的 API 是什么样子的？

background

**Comment by Moonofweisheng** [comment]
目前激活色继承自主色，也提供了单独的css变量，可以通过css变量定制，是否增加props我想想。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月8日(周五) 中午1:50
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Moonofweisheng/wot-design-uni] tab标签增加选中底部横线颜色 (Issue #187)




 
这个功能解决了什么问题？
 
目前好像没有这个功能，希望有这个功能  可以选择文字颜色，我觉得也应该有个匹配的active 底部选中颜色
 
你期望的 API 是什么样子的？
 
background
