### ISSUE TITLE
组件wd-badge

### ISSUE THREAD

**Issue by Sk-0515** [Moonofweisheng/wot-design-uni#188]
### Wot Design Uni 版本号

1.1.6

### 平台

h5, APP

### 重现链接

https://wot-design-uni.cn/component/badge.html

### 重现步骤

[plugin:vite:vue] 
Single file component can contain only one <script> element
at ../node_modules/.pnpm/wot-design-uni@1.1.6_vue@3.3.13/node_modules/wot-design-uni/components/wd-badge/wd-badge.vue:1:0 (x2)

### 期望的结果是什么？

删除多余的<script></script>

### 实际的结果是什么？

导致编译报错

**Comment by Moonofweisheng** [comment]
uni-app当前并不支持vue3.3，请降低一下vue版本

**Comment by Sk-0515** [comment]
麻烦作者同步更新一下npm。

**Comment by Moonofweisheng** [comment]
1.1.7发布了，已经包含了这个改动。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月9日(周六) 下午3:20
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [Moonofweisheng/wot-design-uni] 组件wd-badge (Issue #188)




 
麻烦作者同步更新一下npm。
