### ISSUE TITLE
[新功能需求] Table 表格能否支持索引列？

### ISSUE THREAD

**Issue by goexc** [Moonofweisheng/wot-design-uni#191]
### 这个功能解决了什么问题？

显示索引，可以增加一列 wd-table-col ，设置 type 属性为 index 即可显示从 1 开始的索引号。

### 你期望的 API 是什么样子的？

```<wd-table-col type="index" label="索引" />```

**Comment by Moonofweisheng** [comment]
当前`wd-table-col`通过作用域插槽提供了`index`属性，支持通过自定义列模板展示当前的索引号，这也许可以解决你的问题。

**Comment by goexc** [comment]
您好，您的邮件我已收到。我会尽快给您回复。

**Comment by goexc** [comment]
您好，您的邮件我已收到。我会尽快给您回复。
