### ISSUE TITLE
[新功能需求] wd-img 支持点击全屏预览，以及增加图片预览组件

### ISSUE THREAD

**Issue by PromiseAll** [Moonofweisheng/wot-design-uni#193]
### 这个功能解决了什么问题？

有时候略缩图展示时 需要点击全屏展示

### 你期望的 API 是什么样子的？

参考nutui-uniapp 的   [imagepreview](https://nutui-uniapp.netlify.app/components/exhibition/imagepreview.html)

**Comment by Moonofweisheng** [comment]
计划支持
