### ISSUE TITLE
wd-tabs第一次没有初始化的时候，通过某些条件显示时，下面的横线会偏移

### ISSUE THREAD

**Issue by BeginnerDone** [Moonofweisheng/wot-design-uni#194]
### Wot Design Uni 版本号

1.2.0

### 平台

微信小程序

### 重现链接

https://wot-design-uni.cn/component/tabs.html

### 重现步骤

![image](https://github.com/Moonofweisheng/wot-design-uni/assets/20809153/aa097bd9-92e1-41e4-8059-189f988e6789)

<template>
  <wd-button @click="show=true">显示</wd-button>
   <view v-show="show">
     <wd-tabs ref="tabsRef" v-model="tabsCurrent" :slidable-num="4">
	 <wd-tab title="测试1" name="1">
	 </wd-tab>
         <wd-tab title="测试2" name="2">
	 </wd-tab>
   </wd-tabs>
  </view>
</template>

### 期望的结果是什么？

显示wd-tabs 时，可以正常显示下面的横线位置

### 实际的结果是什么？

横线位置偏离

**Comment by Moonofweisheng** [comment]
场景是否为tabs数据赋值前已经存在tabs组件。可以先控制一下没有tabs数据没有的时候先不渲染tabs组件，后面会优化。

**Comment by BeginnerDone** [comment]
> 场景是否为tabs数据赋值前已经存在tabs组件。可以先控制一下没有tabs数据没有的时候先不渲染tabs组件，后面会优化。

好的，感谢

**Comment by Moonofweisheng** [comment]
我这没有复现了。给个复现的demo吧。

**Comment by longshao5520** [comment]
先加载数据后渲染也会偏移

**Comment by Moonofweisheng** [comment]
给个复现demo看看吧，之前看了很多场景，没有复现。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Moonofweisheng/wot-design-uni"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月19日(星期五) 下午3:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Moonofweisheng/wot-design-uni] wd-tabs第一次没有初始化的时候，通过某些条件显示时，下面的横线会偏移 (Issue #194)





 
先加载数据后渲染也会偏移

**Comment by Moonofweisheng** [comment]
目前遇到一个微信小程序在Popup中使用tabs组件初始化时滑块位置不对的问题，这个是uni-app目前已知的一个问题导致的，插槽外部已经加了v-if处理不显示插槽，但是插槽内组件的onMounted等生命周期仍会执行。  
此场景的解决办法是：  
1. popup打开后再显示tabs  
2. popup打开红调用tabs的setActive方法重新设置激活项  

如有另外的场景可以补充，可以重开此issue。
