### ISSUE TITLE
[Bug 上报] picker 选择器v-modal 传值过去 label 显示异常

### ISSUE THREAD

**Issue by wangruiStart** [Moonofweisheng/wot-design-uni#195]
### Wot Design Uni 版本号

1.2.1

### 平台

APP

### 重现链接

无

### 重现步骤

无

### 期望的结果是什么？

label 正常显示

### 实际的结果是什么？

label 显示 空白

**Comment by Moonofweisheng** [comment]
给一下复现demo吧



---原始邮件---
发件人: "Rui ***@***.***&gt;
发送时间: 2024年3月19日(周二) 晚上8:57
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Moonofweisheng/wot-design-uni] [Bug 上报] picker 选择器v-modal 传值过去 label 显示异常 (Issue #195)




 
Wot Design Uni 版本号
 
1.2.1
 
平台
 
APP
 
重现链接
 
无
 
重现步骤
 
无
 
期望的结果是什么？
 
label 正常显示
 
实际的结果是什么？
 
label 显示 空白
 
环境信息
 
No response
 
其他补充信息
 
No response

**Comment by wangruiStart** [comment]
> 给一下复现demo吧
> […](#)
> ---原始邮件--- 发件人: "Rui ***@***.***&gt; 发送时间: 2024年3月19日(周二) 晚上8:57 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [Moonofweisheng/wot-design-uni] [Bug 上报] picker 选择器v-modal 传值过去 label 显示异常 (Issue #195) Wot Design Uni 版本号 1.2.1 平台 APP 重现链接 无 重现步骤 无 期望的结果是什么？ label 正常显示 实际的结果是什么？ label 显示 空白 环境信息 No response 其他补充信息 No response — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

```vue
const value = ref(0)

const options = [
{
          value: 0,
          label: t('my.unknown')
        },
        {
          value: 1,
          label: 'GG'
        },
        {
          value: 2,
          label: 'MM'
        }
]

<wd-picker
          
              v-model:modelValue="value"
              :columns="options"
              :label="item.label"
              :prop="item.key"
              label-width="100px"
              placeholder="请选择"
              v-bind="item.props"
            />
```
