### ISSUE TITLE
[新功能需求] 希望Toast组件和MessageBox组件增加全局组件或示例

### ISSUE THREAD

**Issue by webarn** [Moonofweisheng/wot-design-uni#197]
### 这个功能解决了什么问题？

1. 现在的Toast如果使用需要在当前页面引入标签，我在layout组件内引入标签还无效。
2. 我在自定义指令中应当如何使用这两个组件，现在有warn：provide() can only be used inside setup()

### 你期望的 API 是什么样子的？

可以在公共布局中引入标签，在适当的地方都可调佣

**Comment by frankyoungd** [comment]
在非页面中怎么使用？比如axios的loading,消息提示等？

**Comment by webarn** [comment]
如只能在setup中使用，无法在如axios中使用，就造成了全局样式不统一，则无法使用。 @Moonofweisheng

**Comment by Moonofweisheng** [comment]
> 在非页面中怎么使用？比如axios的loading,消息提示等？

[参考](https://github.com/Moonofweisheng/wot-design-uni/issues/197#issuecomment-2029371714)

**Comment by shijunti19** [comment]
@Moonofweisheng 有具体例子吗，怎么写才可以全局调用
而且全局slot里也无效
<template>
  <view class="default-layout">
    <slot />
    <wd-toast />
    <wd-message-box />
  </view>
</template>

<style lang="scss"></style>
这里的    <wd-toast />无效的，需要在每个独立页面里写  <wd-toast />，超级麻烦

**Comment by Moonofweisheng** [comment]
> @Moonofweisheng 有具体例子吗，怎么写才可以全局调用 而且全局slot里也无效
> 
> ```
> <template>
>   <view class="default-layout">
>     <slot />
>     <wd-toast />
>     <wd-message-box />
>   </view>
> </template>
> 
> <style lang="scss"></style>
> ```
> 
> 这里的
> 
> ```
> <wd-toast />
> ```
> 
> 无效的，需要在每个独立页面里写
> 
> ```
> <wd-toast />
> ```
> 
> ，超级麻烦

可以参考wot-starter-retail仓库的实现，还有如果有问题可以另外开issue。
