### ISSUE TITLE
建议把文档放在gitee上，netlify基本打不开

### ISSUE THREAD

**Issue by doghap** [Moonofweisheng/wot-design-uni#20]
建议把文档放在gitee上，netlify基本打不开

**Comment by Moonofweisheng** [comment]
考虑放到Vercel上一份

**Comment by doghap** [comment]
> 考虑放到Vercel上一份

vercel也可以的, netlify就基本打不开, ping.chinaz.com

**Comment by Moonofweisheng** [comment]
> 
周六吧，会在Vercel上托管一份文档

**Comment by Moonofweisheng** [comment]
> > 考虑放到Vercel上一份
> 
> vercel也可以的, netlify就基本打不开, ping.chinaz.com

这周六会在Vercel上托管一份文档，暂时先使用netlify上的文档吧

**Comment by Moonofweisheng** [comment]
已提供国内文档地址，参见 #22 #

**Comment by Moonofweisheng** [comment]
已提供国内文档地址，参见 ##22
