### ISSUE TITLE
[Bug 上报] 官网 ICON 组件展示异常

### ISSUE THREAD

**Issue by zwmmm** [Moonofweisheng/wot-design-uni#201]
### Wot Design Uni 版本号

0.1.27 

### 平台

h5

### 重现链接

https://wot-design-uni.gitee.io/component/icon.html

### 重现步骤

<img width="1769" alt="image" src="https://github.com/Moonofweisheng/wot-design-uni/assets/30194521/84431ea0-aefc-486a-85ec-708edc8ef8f6">

### 期望的结果是什么？

正常展示 icon 方便开发

### 实际的结果是什么？

icon 预览异常

**Comment by zwmmm** [comment]
测试出来 需要手动切换下 黑夜模式 才会正常 应该是预览的iframe初始化的 主题不对

**Comment by Moonofweisheng** [comment]
可能是缓存，应用了之前的暗黑模式的css样式




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Moonofweisheng/wot-design-uni"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月27日(星期三) 上午10:29
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Moonofweisheng/wot-design-uni] [Bug 上报] 官网 ICON 组件展示异常 (Issue #201)





 
测试出来 需要手动切换下 黑夜模式 才会正常 应该是预览的iframe初始化的 主题不对
