### ISSUE TITLE
wd-upload 希望上传组件增加图片预览模式配置

### ISSUE THREAD

**Issue by YILS-LIN** [Moonofweisheng/wot-design-uni#203]
### 这个功能解决了什么问题？

此属性目前外部无法修改，希望增加一个可传入的参数

![image](https://github.com/Moonofweisheng/wot-design-uni/assets/62397373/9f51c146-120f-49ea-af1d-662564d30313)

### 你期望的 API 是什么样子的？

```vue
<wd-upload img-preview-mode="aspectFit" />
```

**Comment by Moonofweisheng** [comment]
接受
