### ISSUE TITLE
Segmented 分段器增加一个参数，{value} 可以拿到整个对象

### ISSUE THREAD

**Issue by ximo-156** [Moonofweisheng/wot-design-uni#204]
### 这个功能解决了什么问题？

![image](https://github.com/Moonofweisheng/wot-design-uni/assets/117827636/af40dc7f-91f1-44df-8370-735ae278ab7a)

### 你期望的 API 是什么样子的？

const change = ({ value, selectedItems }) => {
  console.log(value, selectedItems)
}
selectedItems就是获取整个对象方便获取其他对象的其他属性

**Comment by Moonofweisheng** [comment]
可以

**Comment by ximo-156** [comment]
> 可以

随时关注
