### ISSUE TITLE
请问picker组件为啥要默认选中首项呢，可不可以不让他选中呢？

### ISSUE THREAD

**Issue by zzzzz-l-break** [Moonofweisheng/wot-design-uni#208]
### Wot Design Uni 版本号

1.2.5

### 平台

微信小程序

### 重现链接

无

### 重现步骤

<img width="1205" alt="Screenshot-2024-47-29_16-47-36" src="https://github.com/Moonofweisheng/wot-design-uni/assets/40649097/3696c35d-24b3-4f86-aa95-f62dafc57263">

### 期望的结果是什么？

默认啥也不选中，showValue展示空字符串

### 实际的结果是什么？

showValue展示第一项

**Comment by Moonofweisheng** [comment]
1.2.6以后已经解决了这个问题

**Comment by Moonofweisheng** [comment]
建议更新到1.2.7，修复了Picker在APP端的无法显示接口返回的多列数据的问题
