### ISSUE TITLE
官网文档icon组件的图标无法预览

### ISSUE THREAD

**Issue by zzzzz-l-break** [Moonofweisheng/wot-design-uni#210]
### Wot Design Uni 版本号

0.1.27

### 平台

其他小程序

### 重现链接

https://wot-design-uni.gitee.io/component/icon.html#%E5%9F%BA%E6%9C%AC%E7%94%A8%E6%B3%95

### 重现步骤

https://wot-design-uni.gitee.io/component/icon.html#%E5%9F%BA%E6%9C%AC%E7%94%A8%E6%B3%95

### 期望的结果是什么？

可以预览icon

### 实际的结果是什么？

不可预览

**Comment by Moonofweisheng** [comment]
可以尝试切换一下暗黑模式，文档这块可能有点问题，还没定位

**Comment by h7ml** [comment]
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/55233292/a67e05fc-942b-4a29-aa6b-1638c4d11bd9)
问题依然存在。影响到本地开发了

**Comment by h7ml** [comment]
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/55233292/e0b70ab0-d346-46e2-bcab-ed5a5b7f5c41)

**Comment by h7ml** [comment]
已解决。
原因是代理模式下某些资源文件未加载
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/55233292/eec8d289-90d2-40b8-832b-41b0df887799)
