### ISSUE TITLE
希望组件都预留出个slot，用于自定义

### ISSUE THREAD

**Issue by webarn** [Moonofweisheng/wot-design-uni#213]
### 这个功能解决了什么问题？

解决了大部分组件的扩展功能，如wd-number-keyboard组件，title只能是字符串，我需要左右布局增加自己的展示，但是无法实现，如果预留出slot则更方便

<slot />

**Comment by Moonofweisheng** [comment]
可以列举一下你目前希望在哪些组件增加slot，我评估后会处理。wd-number-keyboard可以增加`title`的slot。

**Comment by webarn** [comment]
目前项目中只涉及到了 `wd-number-keyboard`组件，但是我看文档好多没有预留出来slot。感谢回复

**Comment by Moonofweisheng** [comment]
本次为`number-keyboard`新增`title`插槽，其他组件就有需求再提把。
