### ISSUE TITLE
wd-calendar组件选择日期时间，如果vmodel绑定的值为空，则弹出框不会出现时间选择，需要切换日期才会出现时间选择

### ISSUE THREAD

**Issue by XuanYuHou** [Moonofweisheng/wot-design-uni#214]
### Wot Design Uni 版本号

1.2.3

### 平台

微信小程序

### 重现链接

忽略

### 重现步骤

![image](https://github.com/Moonofweisheng/wot-design-uni/assets/82325016/d5476793-5a64-46c5-a480-3c72ac5ac8e9)
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/82325016/2e28166a-98ed-46e5-b188-eb8f0b28fd8e)

### 期望的结果是什么？

期望在选择时可以直接选择时间

### 实际的结果是什么？

时间选择不会出来 需要切换日期才会出现时间选择

### 环境信息

微信小程序

**Comment by Moonofweisheng** [comment]
确认为bug，修复后调整无默认值逻辑为：第一次选择日期后即可选择时间
