### ISSUE TITLE
有索引栏组件不，作者考不考虑搞一个呢

### ISSUE THREAD

**Issue by xx-qiang** [Moonofweisheng/wot-design-uni#233]
### 这个功能解决了什么问题？

https://vant-contrib.gitee.io/vant/?hmsr=aladdin1e5#/zh-CN/index-bar

### 你期望的 API 是什么样子的？

https://vant-contrib.gitee.io/vant/?hmsr=aladdin1e5#/zh-CN/index-bar

**Comment by Moonofweisheng** [comment]
可以有
