### ISSUE TITLE
wd-picker 赋值手动清空后，会默认选中第一个值

### ISSUE THREAD

**Issue by Mr-9** [Moonofweisheng/wot-design-uni#234]
### Wot Design Uni 版本号

1.2.14

### 平台

h5

### 重现链接

https://github.com/Mr-9/demo.git

### 重现步骤

选择后清空，默认值没有清空

### 期望的结果是什么？

期望清空回到初始的样子。

### 实际的结果是什么？

实际是值已经空了。但是显示的是早餐

**Comment by Mr-9** [comment]
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/24818515/e72b0a16-6386-4470-a2d7-662b565ab7bd)

**Comment by Moonofweisheng** [comment]
升级到1.2.6以上版本可以解决
