### ISSUE TITLE
[Bug 上报] wd-img组件预览效果失效

### ISSUE THREAD

**Issue by zhao-new-student** [Moonofweisheng/wot-design-uni#244]
### Wot Design Uni 版本号

1.2.5

### 平台

微信小程序

### 重现链接

https://wot-design-uni.cn/component/img.html

### 重现步骤

`    <wd-img
        :width="200"
        :height="200"
        :enable-preview="true"
        src="../../../../static/images/picture.png"
      ></wd-img>`
![Snipaste_2024-04-15_16-26-28](https://github.com/Moonofweisheng/wot-design-uni/assets/147313944/028aa0df-c821-49e3-99e2-7869878556cf)

### 期望的结果是什么？

在微信调试工具中点击上述图片可以出现预览效果

### 实际的结果是什么？

没有出现预览效果

**Comment by Moonofweisheng** [comment]
1.2.11以后版本支持，升级后再试试。文档漏掉了标明支持版本，后面补上。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Moonofweisheng/wot-design-uni"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月15日(星期一) 下午4:28
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Moonofweisheng/wot-design-uni] [Bug 上报] wd-img组件预览效果失效 (Issue #244)





 
Wot Design Uni 版本号
 
1.2.5
 
平台
 
微信小程序
 
重现链接
 
https://wot-design-uni.cn/component/img.html
 
重现步骤
 
    <wd-img :width="200" :height="200" :enable-preview="true" src="../../../../static/images/picture.png" &gt;</wd-img&gt;
 Snipaste_2024-04-15_16-26-28.png (view on web)
 
期望的结果是什么？
 
在微信调试工具中点击上述图片可以出现预览效果
 
实际的结果是什么？
 
没有出现预览效果
 
环境信息
 
No response
 
其他补充信息
 
No response

**Comment by zhao-new-student** [comment]
升级到1.2.11后点击预览无法加载,只显示加载图案

**Comment by Moonofweisheng** [comment]
> 升级到1.2.11后点击预览无法加载,只显示加载图案
这样写试试
`import img from '../../../../static/images/picture.png'`. 

` <wd-img :width="200" :height="200" :enable-preview="true" :src="src" ></wd-img>`

**Comment by jasper-ops** [comment]
预览功能的实现底层是调用的uni.previewImage来实现的，在小程序previewImage不支持预览包内图片
