### ISSUE TITLE
[新功能需求] 希望能完善ColPicker 多列选择器的地址功能及文档

### ISSUE THREAD

**Issue by Creat55** [Moonofweisheng/wot-design-uni#245]
### 这个功能解决了什么问题？

展示格式化需要用到label，而初始选项的auto-complete又只有 value 字段，没有 label 字段。当真实需求为修改地址时，如何传入原来的三级地址并让ColPicker显示出来呢

### 你期望的 API 是什么样子的？

需要重新map一次area.json 就很头大了，有没有别的好办法

**Comment by Moonofweisheng** [comment]
可以看看新的文档
