### ISSUE TITLE
tabs组件sticky的BUG

### ISSUE THREAD

**Issue by 5565007** [Moonofweisheng/wot-design-uni#251]
### Wot Design Uni 版本号

0.1.1

### 平台

h5, 微信小程序

### 重现链接

无啊

### 重现步骤

当tabs外层设置了view,这个view设置了padding:10px的内边距，这时tabs就会串出去了，这个tabs的宽度好像是按屏幕宽度计算的。
代码结构如下
        <view style="padding: 10px;">
            <wd-tabs v-model="tab" sticky>
                <block v-for="item in 4" :key="item">
                    <wd-tab :title="`标签${item}`">
                    <view class="content">内容{{ item }}</view>
                    </wd-tab>
                </block>
            </wd-tabs>
        </view>

### 期望的结果是什么？

期望tabs设置多多宽就是多宽，或根据外层容器的宽，灵活配置

### 实际的结果是什么？

是按照屏幕的宽计算了

**Comment by Moonofweisheng** [comment]
这是当前sticky的局限，可以不使用tabs组件的sticky功能，自己实现sticky布局



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月20日(周六) 上午10:11
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Moonofweisheng/wot-design-uni] tabs组件sticky的BUG (Issue #251)




 
Wot Design Uni 版本号
 
0.1.1
 
平台
 
h5, 微信小程序
 
重现链接
 
无啊
 
重现步骤
 
当tabs外层设置了view,这个view设置了padding:10px的内边距，这时tabs就会串出去了，这个tabs的宽度好像是按屏幕宽度计算的。
 代码结构如下
 
 
 
 
 内容{{ item }}
 
 
 
 
 
期望的结果是什么？
 
期望tabs设置多多宽就是多宽，或根据外层容器的宽，灵活配置
 
实际的结果是什么？
 
是按照屏幕的宽计算了
 
环境信息
 
No response
 
其他补充信息
 
No response
