### ISSUE TITLE
wd-button 组件 open-type开放能力失效

### ISSUE THREAD

**Issue by omgccyjj** [Moonofweisheng/wot-design-uni#253]
### Wot Design Uni 版本号

1.2.11

### 平台

微信小程序

### 重现链接

无

### 使用  wd-button 组件的open-type="getPhoneNumber" 会报错 Cannot read property 'errMsg' of undefined

```vue
<wd-button type="primary" block open-type="getPhoneNumber" @getphonenumber="onGetphonenumber">
        登录
      </wd-button>
``` 
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/127389226/64e7409f-cbaa-4f0d-ad66-620009f040eb)

报错的代码
```vue
 if (ev.detail.errMsg === 'getPhoneNumber:fail user deny')
``` [](url)

### 期望的结果是什么？

希望能够使用wd=button 的 open-type="getPhoneNumber"  以及 @getphonenumber 方法

### 实际的结果是什么？

读取不到errMsg，只能使用原生button

### 环境信息

_No response_

### 其他补充信息

_No response_

**Comment by Moonofweisheng** [comment]
组件内部目前的实现是直接将`event.detail`抛出来了，这一点文档中未写明，后续会补充。
你可以调整一下，这样写：
```
if (ev.errMsg === 'getPhoneNumber:fail user deny')
```  

感谢你的issue。

**Comment by omgccyjj** [comment]
解决了，感谢您的回复 #

> 组件内部目前的实现是直接将`event.detail`抛出来了，这一点文档中未写明，后续会补充。 你可以调整一下，这样写：
> 
> ```
> if (ev.errMsg === 'getPhoneNumber:fail user deny')
> ```
> 
> 感谢你的issue。
