### ISSUE TITLE
[Bug 上报] vue-tsc 大量报错

### ISSUE THREAD

**Issue by waset** [Moonofweisheng/wot-design-uni#258]
### Wot Design Uni 版本号

1.2.17

### 平台

h5, 微信小程序

### 重现链接

https://github.com/waset/yjzj-mini/actions/runs/8811586997/job/24185744402?pr=6

### 重现步骤

``` bash
$ vue-tsc --noEmit --skipLibCheck
```

### 期望的结果是什么？

全部通过

### 实际的结果是什么？

<img width="1063" alt="image" src="https://github.com/Moonofweisheng/wot-design-uni/assets/55943270/02c63c91-a6d6-48df-9ca4-df91bea265de">

**Comment by waset** [comment]
#192 并没有解决问题

**Comment by Moonofweisheng** [comment]
uni-helper+uni-app-types 大概是这个插件给很多原生组件加上了类型，导致很多组件里面使用的例如`opentype`和`uni-helper+uni-app-types`提供的`opentype`对不上。
·


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Moonofweisheng/wot-design-uni"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月24日(星期三) 下午2:07
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Moonofweisheng/wot-design-uni] [Bug 上报] vue-tsc 大量报错 (Issue #258)





 
#192 并没有解决问题

**Comment by Moonofweisheng** [comment]
> #192 并没有解决问题

和这个无关

**Comment by RJQingHuan** [comment]
回退volar版本可解决 @waset

**Comment by waset** [comment]
> 回退volar版本可解决 @waset 

vscode 插件？

**Comment by coolxiaohao** [comment]
同样的问题，请问解决了吗？

**Comment by Moonofweisheng** [comment]
> uni-helper+uni-app-types 大概是这个插件给很多原生组件加上了类型，导致很多组件里面使用的例如`opentype`和`uni-helper+uni-app-types`提供的`opentype`对不上。

参考这个[issue](https://github.com/uni-helper/uni-app-types/issues/64)

**Comment by coolxiaohao** [comment]
> > uni-helper+uni-app-types 大概是这个插件给很多原生组件加上了类型，导致很多组件里面使用的例如`opentype`和`uni-helper+uni-app-types`提供的`opentype`对不上。
> 
> 参考这个[issue](https://github.com/uni-helper/uni-app-types/issues/64)

![image](https://github.com/Moonofweisheng/wot-design-uni/assets/46562305/56f1e179-dc32-4279-aac5-d5915666ca71)
这个依旧解决不了，TypeScript Vue Plugin (Volar) 插件弃用了，提示 Plugin undefined API version incompatible, expected 1.x but got 2
