### ISSUE TITLE
[Bug 上报] input输入框placeholder样式错误

### ISSUE THREAD

**Issue by zhao-new-student** [Moonofweisheng/wot-design-uni#267]
### Wot Design Uni 版本号

1.2.11

### 平台

微信小程序

### 重现链接

无

### 重现步骤

手机屏幕滑到顶部不会偏移,随着手机向下滑动,点击输入框placeholder会产生偏移,且随着手机向下滑动的距离增加,点击输入框placeholder的偏移量会增加
![微信图片_20240427222742](https://github.com/Moonofweisheng/wot-design-uni/assets/147313944/940f2592-2a41-46c0-84ef-0c7362953df9)

### 期望的结果是什么？

placeholder不产生偏移

### 实际的结果是什么？

![微信图片_20240427222742](https://github.com/Moonofweisheng/wot-design-uni/assets/147313944/80417121-3c9f-4f1f-9bdb-ee59abf01101)

**Comment by Moonofweisheng** [comment]
未提供复现demo，此issue将被关闭，如果仍有问题可提供复现demo后重开此issue
