### ISSUE TITLE
Upload 上传功能增加上传类型

### ISSUE THREAD

**Issue by Mr-9** [Moonofweisheng/wot-design-uni#268]
### 这个功能解决了什么问题？

实际业务中，文件上传不仅是图片。有时候只需要展示文件名称。不需要预览和图片的展示。希望增加
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/24818515/c949bc8f-5946-420c-9352-9f79643035b0)

### 你期望的 API 是什么样子的？

![image](https://github.com/Moonofweisheng/wot-design-uni/assets/24818515/2c6c2458-9f9d-4eae-8c8f-898f0b7c58f6)

**Comment by Moonofweisheng** [comment]
#186
