### ISSUE TITLE
slider组件步长设置> 1无效

### ISSUE THREAD

**Issue by bsuooo** [Moonofweisheng/wot-design-uni#269]
### Wot Design Uni 版本号

0.1.1

### 平台

h5

### 重现链接

https://wot-design-uni.netlify.app/component/slider.html

### 重现步骤

设置了步长10 但是无效

### 期望的结果是什么？

设置了步长10 有效

### 实际的结果是什么？

设置了步长10 但是无效

### 其他补充信息

![image](https://github.com/Moonofweisheng/wot-design-uni/assets/91053541/70c5d14e-1a00-44ca-b4cc-bda3caec4a28)

**Comment by jasper-ops** [comment]
升级到新版本测试过吗，是否依然有此问题

**Comment by bsuooo** [comment]
emm 我看错了, 最新版本并没有生效 @Moonofweisheng  @jasper-ops

**Comment by jasper-ops** [comment]
> emm 我看错了, 最新版本并没有生效 @Moonofweisheng @jasper-ops

找到问题了，我修复一下，等待下一个版本
