### ISSUE TITLE
设置mergeVirtualHostAttributes导致微信小程序NavBar组件left箭头错位

### ISSUE THREAD

**Issue by c1emon** [Moonofweisheng/wot-design-uni#271]
### Wot Design Uni 版本号

1.2.18

### 平台

微信小程序

### 重现链接

https://github.com/c1emon/uni-starter

### 重现步骤

`npm run dev:mp-weixin` 后，使用微信开发者工具运行。进入**我的**选项卡下**主题设置**项目，导航栏即可显示箭头。

### 期望的结果是什么？

<img width="1438" alt="fix-view" src="https://github.com/Moonofweisheng/wot-design-uni/assets/33052582/01cd9193-c8d4-4d5b-8339-1bcc194bfaa6">
手动在源码中使用view标签包裹wd-icon可以解决此问题。

### 实际的结果是什么？

<img width="1410" alt="bug" src="https://github.com/Moonofweisheng/wot-design-uni/assets/33052582/f5fc5c4e-ddd8-434f-b44a-dcc57ee98d3b">

### 其他补充信息

mergeVirtualHostAttributes设置为false后问题可解决，但是需要mergeVirtualHostAttributes来支持自定义组件上的class。

**Comment by c1emon** [comment]
重现链接更新:
https://github.com/c1emon/uni-starter/tree/bug-nav-icon

**Comment by Moonofweisheng** [comment]
> 重现链接更新: https://github.com/c1emon/uni-starter/tree/bug-nav-icon 使用icon slot可以避免此问题

<img width="1272" alt="image" src="https://github.com/Moonofweisheng/wot-design-uni/assets/26426873/e36d7cd2-e38e-4c60-942b-b07a1255ac0f">
应该是这个项目`unocss`将`size="24px"`认为是设置`.size-24px {
    width: 24px;
    height: 24px;
}`，导致出现了此问题。

**Comment by Moonofweisheng** [comment]
参考[文档](https://unocss.nodejs.cn/presets/attributify#properties-conflicts)
