### ISSUE TITLE
Tabbar 标签栏自定义图标没办法区分来定义active和not-active的图标

### ISSUE THREAD

**Issue by TenXLL** [Moonofweisheng/wot-design-uni#277]
### 这个功能解决了什么问题？

现在的自定义图标只有一种状态

### 你期望的 API 是什么样子的？

<template #icon={data}>
        <wd-img
          round
          height="40rpx"
          width="40rpx"
          src="data.active ? '' : '' "
        ></wd-img>

**Comment by Moonofweisheng** [comment]
icon插槽会告诉你当前是否激活，可以根据这个状态来控制显示哪个图标



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月29日(周一) 中午1:28
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Moonofweisheng/wot-design-uni] Tabbar 标签栏自定义图标没办法区分来定义active和not-active的图标 (Issue #277)




 
这个功能解决了什么问题？
 
现在的自定义图标只有一种状态
 
你期望的 API 是什么样子的？
 
<template #icon={data}&gt;

**Comment by Moonofweisheng** [comment]
参考文档[TabbarItemSlots](https://wot-design-uni.gitee.io/component/tabbar.html#tabbaritem-slots)
