### ISSUE TITLE
[新功能需求] 希望将wd-circle组件的canvas组件渲染方式改为  2d渲染。

### ISSUE THREAD

**Issue by kissIce** [Moonofweisheng/wot-design-uni#278]
### 这个功能解决了什么问题？

canvas组件2d渲染 支持同层级渲染，可以避免canvas层级过高导致挡不住的情况

### 你期望的 API 是什么样子的？

``` xml <wd-circle type="2d"> ```

**Comment by Moonofweisheng** [comment]
计划支持

**Comment by Moonofweisheng** [comment]
已支持canvas2d
