### ISSUE TITLE
[Bug 上报] input输入框，ios中文输入法输入时不选择中文，关闭输入法，会一直狂跳输入法

### ISSUE THREAD

**Issue by zcandlyx** [Moonofweisheng/wot-design-uni#284]
### Wot Design Uni 版本号

1.2.15

### 平台

APP

### 重现链接

无

### 重现步骤

  <wd-input type="text" size="large" clearable v-model="code" placeholder="验证码"></wd-input>
  只要type为text时，ios官方中文输入法输入时不选择中文，关闭输入法，会一直狂跳输入法

### 期望的结果是什么？

无

### 实际的结果是什么？

无

### 环境信息

APP平台
IOS17.4.1
HBuilderX 4.14
VUE3
Iphone13 pro

**Comment by yeweihui0223** [comment]
+1,同样遇到这个bug
input,textarea  中文输入法输入时不选择中文，关闭输入法，会一直狂跳输入法

**Comment by Moonofweisheng** [comment]
> +1,同样遇到这个bug input,textarea 中文输入法输入时不选择中文，关闭输入法，会一直狂跳输入法

应该是组件清空后聚焦逻辑，在iOS存在异常导致的，会处理。

**Comment by yeweihui0223** [comment]
好的，辛苦了
