### ISSUE TITLE
官网504

### ISSUE THREAD

**Issue by de1ck** [Moonofweisheng/wot-design-uni#287]
### Wot Design Uni 版本号

1.2.19

### 平台

h5

### 重现链接

wot-design-uni.gitee.io

### 重现步骤

[wot-design-uni.gitee.io](https://wot-design-uni.gitee.io/)

### 期望的结果是什么？

正常预览

### 实际的结果是什么？

504

**Comment by Moonofweisheng** [comment]
gitee近日下线了Gitee Pages服务，导致所有托管在gitee上的文档、博客都无法访问了，推荐使用[netlify](https://wot-design-uni.netlify.app/)上的文档。
