### ISSUE TITLE
[新功能需求] upload增加对七牛云oss的支持

### ISSUE THREAD

**Issue by Creat55** [Moonofweisheng/wot-design-uni#288]
### 这个功能解决了什么问题？

阿里云，腾讯云，华为云。。。为啥木有七牛云

### 你期望的 API 是什么样子的？

增加对七牛云oss的支持

**Comment by Moonofweisheng** [comment]
都支持的，只是没提供七牛云的demo



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月6日(周一) 下午2:30
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Moonofweisheng/wot-design-uni] [新功能需求] upload增加对七牛云oss的支持 (Issue #288)




 
这个功能解决了什么问题？
 
阿里云，腾讯云，华为云。。。为啥木有七牛云
 
你期望的 API 是什么样子的？
 
增加对七牛云oss的支持

**Comment by Creat55** [comment]
找了半天七牛云的文档，写得稀烂。。 最后是靠后端换好token，前端只需要
	formData = {
		...formData,
		token,
		key
	}
就可以凑合用了

**Comment by Moonofweisheng** [comment]
> 找了半天七牛云的文档，写得稀烂。。 最后是靠后端换好token，前端只需要 formData = { ...formData, token, key } 就可以凑合用了

嗯 其他几个也是我去翻的对应的文档写的demo，基本上差不多的。
