### ISSUE TITLE
[Bug 上报] Popover placement left 没有出现箭头

### ISSUE THREAD

**Issue by de1ck** [Moonofweisheng/wot-design-uni#295]
### Wot Design Uni 版本号

1.2.19

### 平台

微信小程序

### 重现链接

https://wot-design-uni.cn/component/popover.html

### 重现步骤

```
<wd-popover v-model="show.popover2" placement="left" content="123..."  custom-style="--wot-popover-bg: rgba(0,0,0,0.8);--wot-popover-color: white;">
    <wd-button>123</wd-button>
</wd-popover>
```

### 期望的结果是什么？

出现箭头

### 实际的结果是什么？

![image](https://github.com/Moonofweisheng/wot-design-uni/assets/26627486/64e06522-e2fb-41fa-834e-47a6c507f2a8)

**Comment by Moonofweisheng** [comment]
确认问题，感谢反馈，会尽快修复。
