### ISSUE TITLE
[新功能需求] 新增回到顶部组件

### ISSUE THREAD

**Issue by 60late** [Moonofweisheng/wot-design-uni#298]
### 这个功能解决了什么问题？

回到顶部功能是一个很常见的通用功能，pc和app端都大量有用到。

### 你期望的 API 是什么样子的？

具体实现可以参考vant的BackTop组件 https://vant-ui.github.io/vant/#/zh-CN/back-top

**Comment by jasper-ops** [comment]
uni难哦，组件内无法注册页面滚动事件；是否有更好的办法检测滚动呢

**Comment by 60late** [comment]
> uni难哦，组件内无法注册页面滚动事件；是否有更好的办法检测滚动呢

确实组件内无法监听到滚动，但是可以在组件外监听滚动把scrolltop以prop的形式传给组件内
uview-plus就是以这种方式进行实现的，具体可以参考：
https://uview-plus.jiangruyi.com/components/backTop.html
https://github.com/ijry/uview-plus/blob/master/src/pages/componentsA/backtop/backtop.nvue
