### ISSUE TITLE
[Bug 上报] curtain  组件的宽度width提示不能将类型“string”分配给类型“number”

### ISSUE THREAD

**Issue by gao-xiang** [Moonofweisheng/wot-design-uni#303]
### Wot Design Uni 版本号

1.2.19

### 平台

h5, 微信小程序

### 重现链接

https://wot-design-uni.pages.dev/component/curtain

### 重现步骤

根据文档说明中添加，VS 中提示类型错误。类型中未添加string

/**
   * 幕帘图片宽度
   */
  width: Number,

### 期望的结果是什么？

修复

### 实际的结果是什么？

修复

**Comment by Moonofweisheng** [comment]
是文档标注错误，目前仅支持`number`类型
