### ISSUE TITLE
[Bug 上报] wd-tabbar 组件使用后，底部色块不对

### ISSUE THREAD

**Issue by codercup** [Moonofweisheng/wot-design-uni#307]
### Wot Design Uni 版本号

1.2.20

### 平台

APP

### 重现链接

https://github.com/codercup/unibest/tree/tabbar   (unibest tabbar分支）

### 重现步骤

  (unibest tabbar分支）
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/65991901/86ef9e04-4956-40f1-a5b0-fce744e5a252)
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/65991901/d5864720-14ae-405a-8362-d1bb00af440a)

### 期望的结果是什么？

上面2图发现，小程序正常，app 不正常，底部色块不对。

### 实际的结果是什么？

期望底部色块如小程序一样。

**Comment by Moonofweisheng** [comment]
未复现。
