### ISSUE TITLE
[新功能需求] wd-Button使用icon时，能像wd-icon一样，使用自定义图标

### ISSUE THREAD

**Issue by Creat55** [Moonofweisheng/wot-design-uni#310]
### 这个功能解决了什么问题？

能在button中使用自定义图标

### 你期望的 API 是什么样子的？

参考wd-icon组件 通过 class-prefix 引入自定义图标

**Comment by Moonofweisheng** [comment]
暂时不支持，可以先使用默认插槽实现这个功能

**Comment by telangY** [comment]
目前各端好像已经支持svg  可以加一下  确定微信小程序已经支持 不知道其他小程序是否支持  @Moonofweisheng
