### ISSUE TITLE
[Bug 上报] popup组件的position为center的情况下，picker组件位置不在底部

### ISSUE THREAD

**Issue by tutouxiaozhou** [Moonofweisheng/wot-design-uni#313]
### Wot Design Uni 版本号

1.2.18

### 平台

h5

### 重现链接

无

### 重现步骤

![Snipaste_2024-05-14_11-49-41](https://github.com/Moonofweisheng/wot-design-uni/assets/54765307/c8473443-2c78-4183-ba61-244c6be22ba2)

### 期望的结果是什么？

当position为center时，picker组件位置也在底部

### 实际的结果是什么？

picker组件位置不在底部

**Comment by Moonofweisheng** [comment]
如何使用的呢，给一下demo。

**Comment by tutouxiaozhou** [comment]
`<wd-popup v-model="pop" position="center">

</wd-popup>`

**Comment by tutouxiaozhou** [comment]
`<wd-popup v-model="pop" position="center">
   <wd-picker :columns="columns"  v-model="value" />
</wd-popup>`

**Comment by RJQingHuan** [comment]
picker组件的定位是根据父组件来的

**Comment by Moonofweisheng** [comment]
> `<wd-popup v-model="pop" position="center"> <wd-picker :columns="columns" v-model="value" /> </wd-popup>`

可以把pciker放到外面去，popup内部用cell触发picker的打开和关闭。
