### ISSUE TITLE
组件在大驼峰命名的时候不生效

### ISSUE THREAD

**Issue by omgccyjj** [Moonofweisheng/wot-design-uni#315]
### Wot Design Uni 版本号

1.2.13

### 平台

微信小程序

### 重现链接

无

### 重现步骤

![image](https://github.com/Moonofweisheng/wot-design-uni/assets/127389226/504b33e9-c65a-4efb-8332-0499f459ad33)
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/127389226/45583e67-43bb-4183-b1d5-14c5fc2e722c)

### 期望的结果是什么？

在大驼峰写法的时候也能使用

### 实际的结果是什么？

在大驼峰写法的时候失效了

**Comment by Moonofweisheng** [comment]
怎么导入的组件库？需要你提供一下复现demo。

**Comment by Moonofweisheng** [comment]
未提供复现demo，关闭此issue，如果仍有问题可以重新打开。
