### ISSUE TITLE
[Bug 上报] PickerView 选择器视图三级联动有二级三级无法滑动的bug

### ISSUE THREAD

**Issue by zhao-new-student** [Moonofweisheng/wot-design-uni#316]
### Wot Design Uni 版本号

1.2.13

### 平台

微信小程序

### 重现链接

https://wot-design-uni.cn/component/picker-view.html

### 重现步骤

`                    <wd-picker-view v-model="value" :columns="columns" :column-change="onChangeDistrict" />
`
在项目中使用了wot组件中的演示代码,但是出现二三级无法滑动的问题

https://github.com/Moonofweisheng/wot-design-uni/assets/147313944/9d8f7634-c906-4ffe-bbd1-566ef1514518

### 期望的结果是什么？

可以正常滑动使用

### 实际的结果是什么？

无法滑动

**Comment by Moonofweisheng** [comment]
演示demo未复现，请提供复现demo



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月15日(周三) 晚上10:04
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Moonofweisheng/wot-design-uni] [Bug 上报] PickerView 选择器视图三级联动有二级三级无法滑动的bug (Issue #316)




 
Wot Design Uni 版本号
 
1.2.13
 
平台
 
微信小程序
 
重现链接
 
https://wot-design-uni.cn/component/picker-view.html
 
重现步骤
 
                   <wd-picker-view v-model="value" :columns="columns" :column-change="onChangeDistrict" /&gt;
 在项目中使用了wot组件中的演示代码,但是出现二三级无法滑动的问题
 
https://github.com/Moonofweisheng/wot-design-uni/assets/147313944/9d8f7634-c906-4ffe-bbd1-566ef1514518
 
期望的结果是什么？
 
可以正常滑动使用
 
实际的结果是什么？
 
无法滑动
 
环境信息
 
No response
 
其他补充信息
 
No response

**Comment by Moonofweisheng** [comment]
未提供复现demo，此issue将关闭，可以参考组件库[演示demo](https://github.com/Moonofweisheng/wot-design-uni/blob/master/src/pages/pickerView/Index.vue)调整，如果仍有问题可以重开此issue。
