### ISSUE TITLE
[Bug 上报] swiper组件，点条状指示器indicator-不能将类型“{ type: string; }”分配给类型“boolean”

### ISSUE THREAD

**Issue by ggkkxxx** [Moonofweisheng/wot-design-uni#318]
### Wot Design Uni 版本号

1.2.20

### 平台

h5, 微信小程序

### 重现链接

https://wot-design-uni.cn/component/swiper.html

### 重现步骤

使用的unibest的base模板
编辑器使用的vscode
volar版本退回v1.8.27
添加了swiper组件，点条状指示器属性:indicator="{ type: 'dots-bar' }"类型报错
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/55626710/35b27d83-dfdc-4d03-b23c-0c79cfd4d284)

### 期望的结果是什么？

不报错

### 实际的结果是什么？

注释掉tsconfig.json里的wot-design-uni/global.d.ts报错消失，为啥呀
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/55626710/10ae7a59-e2b5-4ae9-8fd8-177d8c530eff)

### 环境信息

Windows

**Comment by Moonofweisheng** [comment]
提供一下重现链接或者复现demo

**Comment by ggkkxxx** [comment]
> 提供一下重现链接或者复现demo

[视频链接](https://file.liyuechun.com/5%E6%9C%8816%E6%97%A5.mp4)，超过10M了没法直接上传
视频中install过程中的报错信息
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/55626710/0ff5f990-63de-44c1-9395-84fa07ccef1e)

**Comment by Moonofweisheng** [comment]
> > 提供一下重现链接或者复现demo
> 
> [视频链接](https://file.liyuechun.com/5%E6%9C%8816%E6%97%A5.mp4)，超过10M了没法直接上传 视频中install过程中的报错信息 ![image](https://private-user-images.githubusercontent.com/55626710/331038395-0ff5f990-63de-44c1-9395-84fa07ccef1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MzA2NTUsIm5iZiI6MTcxNTgzMDM1NSwicGF0aCI6Ii81NTYyNjcxMC8zMzEwMzgzOTUtMGZmNWY5OTAtNjNkZS00NGMxLTkzOTUtODRmYTA3Y2NlZjFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDAzMzIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkZDMyZGUwN2JmODhlOWQ3M2NlYWVmYWRjNWEzZGQ0OWQzNTRhZWU0ZGJmM2Y4YTc1N2I2ZDRmMjY1NGZiMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n0A8K_6616GLkltX3AJM4Uo4QVxq9R2WKznLWjc1v-w)

需要的是复现代码，wot提供的快速上手项目[wot-stater-retail](https://github.com/Moonofweisheng/wot-starter-retail)中无法复现相关问题。

**Comment by ggkkxxx** [comment]
> > > 提供一下重现链接或者复现demo
> > 
> > 
> > [视频链接](https://file.liyuechun.com/5%E6%9C%8816%E6%97%A5.mp4)，超过10M了没法直接上传 视频中install过程中的报错信息 ![image](https://private-user-images.githubusercontent.com/55626710/331038395-0ff5f990-63de-44c1-9395-84fa07ccef1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MzA2NTUsIm5iZiI6MTcxNTgzMDM1NSwicGF0aCI6Ii81NTYyNjcxMC8zMzEwMzgzOTUtMGZmNWY5OTAtNjNkZS00NGMxLTkzOTUtODRmYTA3Y2NlZjFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDAzMzIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkZDMyZGUwN2JmODhlOWQ3M2NlYWVmYWRjNWEzZGQ0OWQzNTRhZWU0ZGJmM2Y4YTc1N2I2ZDRmMjY1NGZiMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n0A8K_6616GLkltX3AJM4Uo4QVxq9R2WKznLWjc1v-w)
> 
> 需要的是复现代码，wot提供的快速上手项目[wot-stater-retail](https://github.com/Moonofweisheng/wot-starter-retail)中无法复现相关问题。

down下来之后终于找到问题所在了！tsconfig里对照着wot-stater-retail加了这一段就好了！！！！！感谢感谢，之前没想到要到这里找
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/55626710/17b05877-0f31-426a-9c5b-b4577ec0906e)
