### ISSUE TITLE
[Bug 上报] input输入框莫名其妙失焦

### ISSUE THREAD

**Issue by TAYUN** [Moonofweisheng/wot-design-uni#319]
### Wot Design Uni 版本号

1.2.20

### 平台

h5

### 复现Demo地址

https://github.com/TAYUN/unibest-demo

### 重现步骤

<wd-input
          type="text"
          label="套餐组名"
          label-width="110rpx"
          center
          v-model="group.groupName"
          placeholder="请输入套餐组名..."
          use-suffix-slot
          clearable
        >
          <template #suffix>
            <wd-button
              class="ml-2"
              @click="addItem(groupIndex)"
              type="primary"
              size="small"
              plain
              custom-class="button"
            >
              添加条目
            </wd-button>
            <wd-button
              class="ml-2"
              @click="deleteGroup(groupIndex)"
              type="error"
              size="small"
              plain
              custom-class="button"
            >
              删除此组
            </wd-button>
          </template>
        </wd-input>
        具体代码看demo

### 期望的结果是什么？

不会自动失焦

### 实际的结果是什么？

输入或删除一次就自动失效

https://github.com/Moonofweisheng/wot-design-uni/assets/80144903/c40cc818-34d4-431c-87f1-dc6c9003f8a0

### 环境信息

微信公众号H5
操作系统：安卓14
设备信息：一加ace 2

**Comment by Moonofweisheng** [comment]
`groupName`作为key也作为绑定值，绑定值变化时key也变化，导致视图更新输入框失焦。

**Comment by Moonofweisheng** [comment]
`groupName`作为key也作为绑定值，绑定值变化时key也变化，导致视图更新输入框失焦。
