### ISSUE TITLE
[Bug 上报] 钉钉小程序wd-drop-menu-item组件下拉框显示异常

### ISSUE THREAD

**Issue by longbow1998** [Moonofweisheng/wot-design-uni#320]
### Wot Design Uni 版本号

1.2.19

### 平台

钉钉小程序

### 复现Demo地址

https://github.com/guoan123/demo.git

### 重现步骤

下拉菜单拉不下来

### 期望的结果是什么？

![10061715904232_ pic](https://github.com/Moonofweisheng/wot-design-uni/assets/72058329/4df208d9-a50a-4279-a7ee-2494e0c7b306)

### 实际的结果是什么？

![10031715904084_ pic](https://github.com/Moonofweisheng/wot-design-uni/assets/72058329/4997b2e2-52f1-436c-960b-c9cf5b0ff70a)

**Comment by Moonofweisheng** [comment]
钉钉使用条件编译了吗，还是直接用的支付宝的编译产物



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月17日(周五) 上午8:39
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Moonofweisheng/wot-design-uni] [Bug 上报] 钉钉小程序wd-drop-menu-item组件下拉框显示异常 (Issue #320)




 
Wot Design Uni 版本号
 
1.2.19
 
平台
 
钉钉小程序
 
复现Demo地址
 
https://github.com/guoan123/demo.git
 
重现步骤
 
下拉菜单拉不下来
 
期望的结果是什么？
 
10061715904232_.pic.jpg (view on web)
 
实际的结果是什么？
 
10031715904084_.pic.jpg (view on web)
 
环境信息
 
No response
 
其他补充信息
 
No response

**Comment by longbow1998** [comment]
使用的支付宝的编译出现的问题
我去尝试使用uniapp的钉钉小程序编译解决了这个问题 感谢

**Comment by Moonofweisheng** [comment]
> 使用的支付宝的编译出现的问题 我去尝试使用uniapp的钉钉小程序编译解决了这个问题 感谢

OK，我会在文档【常见问题】章节增加钉钉等自定义平台编译的相关内容。

**Comment by longbow1998** [comment]
[🙏unibest如何配置钉钉条件编译](https://github.com/codercup/unibest/discussions/82#discussion-6680074)
大佬 这个您知道咋配吗

**Comment by Moonofweisheng** [comment]
> [🙏unibest如何配置钉钉条件编译](https://github.com/codercup/unibest/discussions/82#discussion-6680074) 大佬 这个您知道咋配吗

可以参考[这里](https://github.com/Moonofweisheng/wot-design-uni/blob/cef427e78d251f25a01e7a1c57597951b2d3774f/package.json#L138)

**Comment by longbow1998** [comment]
感谢您的帮助
