### ISSUE TITLE
upload组件不兼容最新API

### ISSUE THREAD

**Issue by 593349399** [Moonofweisheng/wot-design-uni#324]
### 这个功能解决了什么问题？

微信小程序从基础库 2.21.0 开始， [wx.chooseImage](https://developers.weixin.qq.com/miniprogram/dev/api/media/image/wx.chooseImage.html) 停止维护，请使用 [uni.chooseMedia](https://uniapp.dcloud.net.cn/api/media/video.html#choosemedia) 代替

### 你期望的 API 是什么样子的？

兼容

**Comment by Moonofweisheng** [comment]
目前旧API仍可用的，1.3版本将会对upload组件做个比较大的改动，会更新到新的API。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月18日(周六) 上午9:32
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Moonofweisheng/wot-design-uni] upload组件不兼容最新API (Issue #324)




 
这个功能解决了什么问题？
 
微信小程序从基础库 2.21.0 开始， wx.chooseImage 停止维护，请使用 uni.chooseMedia 代替
 
你期望的 API 是什么样子的？
 
兼容
