### ISSUE TITLE
微信小程序将顶部的元素设置sticky时，粘性会失效

### ISSUE THREAD

**Issue by Yi-Wo-Zuo** [Moonofweisheng/wot-design-uni#325]
### Wot Design Uni 版本号

^1.2.20

### 平台

微信小程序

### 复现Demo地址

无

### 重现步骤

![WeChat045ffd974fb8d80ce514eca379e1418d](https://github.com/Moonofweisheng/wot-design-uni/assets/157704566/93c1d1ee-ced9-4ed6-b437-947912280398)

向下滚动，这个顶部元素没有粘性功能

### 期望的结果是什么？

可以粘性在顶部

### 实际的结果是什么？

没有粘性在顶部

### 环境信息

无

### 其他补充信息

# 问题排查

这里我看了具体的源码实现我进行了断点调试，如下代码：

![WeChat64a43db6eabbde9d8c0ad50ca3468e3c](https://github.com/Moonofweisheng/wot-design-uni/assets/157704566/49eebf73-f100-407e-be8c-e7ae75647bcf)

这个回调函数里的`boundingClientRect`参数里面的`top`值并不是`0px`而是`17px`我就觉得很不理解

我就去看了`wd-resize`组件的`resize`方法

![WeChat0d55ec1b404c00cf69336f3166dd7c3f](https://github.com/Moonofweisheng/wot-design-uni/assets/157704566/ea5ed81b-a1d2-41d5-9235-f71dc41dc666)

我在`onScrollHandler`里打了一个`debugger`，惊奇的发现当`debugger`触发时，使用`wd-sticky`组件的元素是向上有一定的距离

![WeChat92a618447edbfc6ebf842d81a82c93df](https://github.com/Moonofweisheng/wot-design-uni/assets/157704566/b4088c3a-c0e8-472e-b7cb-2baed4e9644a)

看到了`wd-sticky`里面的动态宽高还没有内容就调用了这个方法

# 解决

我使用`nextTick`函数包裹了一些就解决，目的是为了宽高样式加上后，在获取DOM的样式

![WeChatfdaca8f2f065b1cfdfaf7c4605dd8ee2](https://github.com/Moonofweisheng/wot-design-uni/assets/157704566/911aa761-6ecc-43d8-a851-af0d9c2ff8fb)

我这个方法不一定对，因为我也不清楚这个组件的具体逻辑，发出来我觉得作者有更好的解决方法

**Comment by Moonofweisheng** [comment]
大概问题是这样的：sticky使用IntersectionObserver实现的监听组件是否与视口范围有交叉，有交叉就回设置吸顶，视口范围为视口高度减去吸顶组件高度，而组件初始就放在顶部，则导致其始终都在视口范围外不会交叉，所以首次渲染时组件会模拟一次滚动，也就是你添加nextTick的地方，这里原来的实现是在设置style后立即执行获取节点信息，而这个时机在微信小程序上获取的节点信息是更新前的，这就导致未获取到真实的节点信息，进而使得模拟滚动的结果无效，而滚动页面又无法使sticky与视口存在交叉，所以吸顶就失效了。

**Comment by Yi-Wo-Zuo** [comment]
ok，我的思路没问题吧
