### ISSUE TITLE
[Bug 上报] 企业微信小程序模式下警告

### ISSUE THREAD

**Issue by tlerbao** [Moonofweisheng/wot-design-uni#326]
### Wot Design Uni 版本号

1.2.13

### 平台

微信小程序

### 复现Demo地址

无

### 重现步骤

小程序模式没问题，但是企业微信小程序模式会有一堆警告

<img width="834" alt="CleanShot 2024-05-19 at 10 05 49@2x" src="https://github.com/Moonofweisheng/wot-design-uni/assets/20442232/467958f0-f7bf-462d-8bb4-fd86514fb806">

### 期望的结果是什么？

不报错

### 实际的结果是什么？

报错

**Comment by Moonofweisheng** [comment]
可以参考这篇[文章](https://blog.csdn.net/weixin_43954962/article/details/122563524)，某些版本的基础库对slot的校验可能存在问题，导致出现此问题，如组件使用上无影响忽略即可。

**Comment by Moonofweisheng** [comment]
此问题微信开放社区搜索，可见很多报障，组件库如无使用上的问题，则不计划解决这个问题，此issue关闭，如仍有问题可以重开此issue。
