### ISSUE TITLE
toast组件不能在axios的返回拦截器里面使用吗

### ISSUE THREAD

**Issue by zlm742173** [Moonofweisheng/wot-design-uni#327]
### Wot Design Uni 版本号

1.2.20

### 平台

h5, APP

### 复现Demo地址

无

### 重现步骤

无

### 期望的结果是什么？

toast组件Notify组件可以在axios返回拦截器里面直接提示错误信息

### 实际的结果是什么？

没有响应

**Comment by Moonofweisheng** [comment]
需要在setup中使用，你可以将网络请求改造成hooks，这样就可以使用。
