### ISSUE TITLE
头条小程序有兼容计划吗

### ISSUE THREAD

**Issue by kernelmix** [Moonofweisheng/wot-design-uni#330]
### 这个功能解决了什么问题？

目前很多组件在头条小程序还不能使用

### 你期望的 API 是什么样子的？

无

**Comment by Moonofweisheng** [comment]
见#161

**Comment by Moonofweisheng** [comment]
目前还不支持字节系小程序，不过在计划中。

**Comment by www295686243** [comment]
wot的颜值挺高的，挺喜欢这套UI框架，不过还在犹豫要不要使用，主要原因是抖音基本占用用户时间最长的App之一，小程序基本算第二大用户体了，不支持抖音实在不敢下手，期待早日兼容

**Comment by Moonofweisheng** [comment]
uni-app vue3 script setup 在字节系的小程序上存在这样和那样的问题，导致迟迟没能兼容，最近uni-app有一些针对字节系的调整，我想等uni-app最近发布了之后再尝试一下关于字节系兼容。&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Moonofweisheng/wot-design-uni"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月12日(星期三) 上午10:50
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Moonofweisheng/wot-design-uni] 头条小程序有兼容计划吗 (Issue #330)





 
wot的颜值挺高的，挺喜欢这套UI框架，不过还在犹豫要不要使用，主要原因是抖音基本占用用户时间最长的App之一，小程序基本算第二大用户体了，不支持抖音实在不敢下手，期待早日兼容
