### ISSUE TITLE
[新功能需求] 提供 wd-text 组件

### ISSUE THREAD

**Issue by normal-coder** [Moonofweisheng/wot-design-uni#331]
### 这个功能解决了什么问题？

文本虽然是一个比较基础的属性但还是有很常见的用途。

目前自行维护文本的效果。在样式部分很多时候会有比较麻烦实现和重复。

期望能比较通用的文本组件。

### 你期望的 API 是什么样子的？

可借鉴 https://www.uviewui.com/components/text.html

**Comment by karlsbeard** [comment]
sounds great

**Comment by Moonofweisheng** [comment]
#403

**Comment by jasper-ops** [comment]
#403
