### ISSUE TITLE
[新功能需求] Picker 选择器支持defaultValue

### ISSUE THREAD

**Issue by LetFree** [Moonofweisheng/wot-design-uni#333]
### 这个功能解决了什么问题？

picker选择器如果数量过多，且最常用值位于中间时，用户体验很不好，希望可以支持支持选中defaultValue默认值功能

### 你期望的 API 是什么样子的？

```
<wd-picker defaultValue="2" :columns="columns" label="单列选项" v-model="value" @confirm="handleConfirm" />
```

**Comment by jasper-ops** [comment]
你给value设置一个默认值不就是defaultValue吗

**Comment by jasper-ops** [comment]
不计划加入`defaultValue`属性，其他组件的`defaultValue`属性也计划移除
