### ISSUE TITLE
[Bug 上报] NumberKeyboard 组件按键的背景颜色和文本颜色均为白色，导致看不见数字

### ISSUE THREAD

**Issue by HB-Wangweilun** [Moonofweisheng/wot-design-uni#334]
### Wot Design Uni 版本号

1.2.22

### 平台

h5, 微信小程序, 支付宝小程序, APP, 钉钉小程序

### 复现Demo地址

https://wot-design-uni.netlify.app/component/number-keyboard.html

### 重现步骤

右侧演示区

### 期望的结果是什么？

文本为灰色或黑色

### 实际的结果是什么？

文本为白色

### 环境信息

uni-app

**Comment by Moonofweisheng** [comment]
复现链接未复现标题所描述问题，请提供完整复现demo，否则issue将被关闭。

**Comment by Moonofweisheng** [comment]
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/26426873/e46a3224-5f4b-4d60-a5db-9b41baa1e998)

**Comment by jasper-ops** [comment]
> 复现链接未复现标题所描述问题，请提供完整复现demo，否则issue将被关闭。

系统是暗黑主题导致的
