### ISSUE TITLE
[Bug 上报] 组件样式在h5里面显示正常 在模拟器里面真机运行样式就乱了

### ISSUE THREAD

**Issue by lgh0601** [Moonofweisheng/wot-design-uni#341]
### Wot Design Uni 版本号

1.2.13

### 平台

h5, APP

### 复现Demo地址

//

### 重现步骤

![41b227bcaa11ba272680f01b7831b1e](https://github.com/Moonofweisheng/wot-design-uni/assets/132630776/471ff35e-7f59-4e52-a5e2-604c5aa86b91)

### 期望的结果是什么？

rpx单位不是可以自适应嘛

### 实际的结果是什么？

不知道是不是组件内部的px单位没有转换rpx单位的原因导致的  我也不知道咋转 我用的unocss

**Comment by Moonofweisheng** [comment]
浏览器不是已经有模拟器了？确认右边模拟器的尺寸。

**Comment by lgh0601** [comment]
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/132630776/15a299f6-5965-44a1-a9b4-aa1399f6e6d2)
左边浏览器的运行环境是h5的嘛  右边模拟器尺寸我是按照浏览器上iphone678的尺寸375x667来进行真机运行的,但是样式尺寸有问题

**Comment by Moonofweisheng** [comment]
模拟器配的有问题吧，是不是应该按分辨率配。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Moonofweisheng/wot-design-uni"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月27日(星期一) 下午4:42
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Moonofweisheng/wot-design-uni] [Bug 上报] 组件样式在h5里面显示正常 在模拟器里面真机运行样式就乱了 (Issue #341)





 
image.png (view on web)
 左边浏览器的运行环境是h5的嘛  右边模拟器尺寸我是按照浏览器上iphone678的尺寸375x667来进行真机运行的,但是样式尺寸有问题
