### ISSUE TITLE
[Bug 上报] DatetimePicker 日期时间选择器钉钉小程序默认时间显示有问题

### ISSUE THREAD

**Issue by pure1220** [Moonofweisheng/wot-design-uni#343]
### Wot Design Uni 版本号

1.2.22

### 平台

钉钉小程序

### 复现Demo地址

无

### 重现步骤

<wd-datetime-picker v-model="value" :default-value="defaultValue" label="日期选择" @confirm="handleConfirm" />
const value = ref<string>('')
const defaultValue = ref<number>(Date.now())

function handleConfirm({ value }) {
  console.log(new Date(value))
}

### 期望的结果是什么？

能正常显示默认值

### 实际的结果是什么？

不能正常显示
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/59270852/4a209f98-00a0-4c11-b08f-f17cc04a63f9)

### 环境信息

①钉钉小程序、
②用的vue-cli创建的离线打包项目，uniapp版本：3.0.0-4010520240507001
③设备信息：模拟器【支付宝开发工具->钉钉->企业内部应用】

**Comment by jasper-ops** [comment]
我的建议是不用defaultValue，你给value一个默认值不就是defaultValue了嘛

**Comment by pure1220** [comment]
> 我的建议是不用defaultValue，你给value一个默认值不就是defaultValue了嘛

是 我发现问题了。现在是我的defaultValue和value类型不一样导致的问题。

**Comment by jasper-ops** [comment]
不要使用defaultValue了，后期可能移除该属性，可以使用下面的方式来实现defaultValue
[cid:92710df8-b2a4-436d-b38e-e4837311e7e3]
________________________________
发件人: pure1220 ***@***.***>
发送时间: 2024年5月29日 11:38
收件人: Moonofweisheng/wot-design-uni ***@***.***>
抄送: Jasper ***@***.***>; Comment ***@***.***>
主题: Re: [Moonofweisheng/wot-design-uni] [Bug 上报] DatetimePicker 日期时间选择器钉钉小程序默认时间显示有问题 (Issue #343)


我的建议是不用defaultValue，你给value一个默认值不就是defaultValue了嘛

是 我发现问题了。现在是我的defaultValue和value类型不一样导致的问题。

―

**Comment by jasper-ops** [comment]
> > 我的建议是不用defaultValue，你给value一个默认值不就是defaultValue了嘛
> 
> 是 我发现问题了。现在是我的defaultValue和value类型不一样导致的问题。

不建议使用`defaultValue`了，计划目前的1.x版本将弃用该属性，下一个大版本将移除该属性，可以使用下方的方式做default

![W8ZY77AXJ{ 6WF LCJ(0RWI](https://github.com/Moonofweisheng/wot-design-uni/assets/85024227/0bc0fb66-d9d0-4517-aceb-c3a3363af28b)
