### ISSUE TITLE
[Bug 上报] wd-img 用相对路径加载本地图片，结果页面中不能显示图片

### ISSUE THREAD

**Issue by Bulandent** [Moonofweisheng/wot-design-uni#348]
### Wot Design Uni 版本号

1.2.13

### 平台

h5, 微信小程序

### 复现Demo地址

没有

### 重现步骤

`<wd-img :width="200" :height="200" src="../../imgs/iShot.png">`

### 期望的结果是什么？

正确显示图片

### 实际的结果是什么？

没有加载出图片，加载失败。

**Comment by telangY** [comment]
建议使用绝对地址或者网络地址，img最好放在static文件夹内

**Comment by Moonofweisheng** [comment]
> 建议使用绝对地址或者网络地址，img最好放在static文件夹内

正确的

**Comment by Bulandent** [comment]
> 建议使用绝对地址或者网络地址，img最好放在static文件夹内

ok
