### ISSUE TITLE
[Bug 上报] 请在此填写标题

### ISSUE THREAD

**Issue by shijunti19** [Moonofweisheng/wot-design-uni#349]
### Wot Design Uni 版本号

0.1.1

### 平台

h5

### 复现Demo地址
vant的
https://vant-ui.github.io/vant/mobile.html#/zh-CN
你的
https://wot-design-uni.netlify.app/demo/?timestamp=1717210331762#/pages/configProvider/Index
### 重现步骤

![image](https://github.com/Moonofweisheng/wot-design-uni/assets/5392211/a0700cb7-f642-4279-9ade-2fdb34afb280)

### 期望的结果是什么？

我发现你写的不对
van-doc-theme-dark van-theme-dark要写到html上，你的
.wot-theme-dark body {
  color: #f5f5f5;
  background-color: black;
}
不对

### 实际的结果是什么？

.wot-theme-dark 位置写的不对

**Comment by Moonofweisheng** [comment]
未提供完整复现demo，此issue关闭。

**Comment by shijunti19** [comment]
@Moonofweisheng 
vant有这个
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/5392211/54dbc92c-e7bb-4df6-9a0e-6192c24464a4)

你的没有这个标示
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/5392211/0c102eaf-a7cc-481b-919e-514523409dfc)
无法做到全页面暗黑
