### ISSUE TITLE
[Bug 上报] wd-input 输入类型是number或digit时，v-model无效

### ISSUE THREAD

**Issue by Guan-Meng-Yuan** [Moonofweisheng/wot-design-uni#352]
### Wot Design Uni 版本号

1.2.23

### 平台

支付宝小程序

### 复现Demo地址

https://github.com/Guan-Meng-Yuan/wot-design-bug-report

### 重现步骤

在digit或者number 输入框中输入值

### 期望的结果是什么？

digit或number v-model在iOS生效

### 实际的结果是什么？

digit或number类型的 v-model在iOS上无效

### 环境信息

发行平台：支付宝小程序
操作系统：iOS17及以上
uni-app版本： 3.0.0-alpha-4010820240531001
设备：macOs支付宝小程序开发工具模拟器或iPhone15Pro

### 其他补充信息

使用uni-app原生input组件有效

**Comment by Moonofweisheng** [comment]
uni-app版本问题，参见[uni-app更新日志](https://uniapp.dcloud.net.cn/release-note-alpha.html#_4-17-2024051110-alpha)

**Comment by Guan-Meng-Yuan** [comment]
input事件可以触发

**Comment by Moonofweisheng** [comment]
> input事件可以触发

    <input type="digit" v-model="digitValue" @input="handleinput" :maxlength="-1">  无法触发input事件，此为uni-app的问题
