### ISSUE TITLE
[新功能需求] 车牌号码键盘

### ISSUE THREAD

**Issue by TAYUN** [Moonofweisheng/wot-design-uni#353]
### 这个功能解决了什么问题？

在车辆相关的项目中使用，方便输入车牌号码。

### 你期望的 API 是什么样子的？

![image](https://github.com/Moonofweisheng/wot-design-uni/assets/80144903/6ea6eb6d-a03b-418d-976d-db02646f7a36)

**Comment by Guan-Meng-Yuan** [comment]
+1

**Comment by RYGRIT** [comment]
我可以尝试实现这个功能吗

**Comment by RYGRIT** [comment]
我可以尝试实现这个功能吗 @Moonofweisheng @TAYUN

**Comment by Moonofweisheng** [comment]
欢迎pr



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月10日(周六) 上午10:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Moonofweisheng/wot-design-uni] [新功能需求] 车牌号码键盘 (Issue #353)




 
我可以尝试实现这个功能吗 @Moonofweisheng @TAYUN

**Comment by WinterG26** [comment]
建议车牌号键盘考虑搭配显示框做成一个组件，目前无法实现在车牌号的特定位置只能输入相应内容
