### ISSUE TITLE
城市选择器，ColPicker 组件 再次赋值的问题。

### ISSUE THREAD

**Issue by 55555778** [Moonofweisheng/wot-design-uni#357]
### Wot Design Uni 版本号

1.2.21

### 平台

微信小程序

### 复现Demo地址

https://github.com/55555778/wot

### 重现步骤

<template>
  <div>
    <wd-col-picker
      label="选择地址"
      v-model="value"
      :columns="area"
      :column-change="columnChange1"
      @confirm="handleConfirm"
      auto-complete></wd-col-picker>
  </div>
</template>

<script setup lang="ts">
import areaData from '../../utils/area.json'
import { ref, onMounted } from 'vue'
const value = ref<any[]>([])

const area = ref<any[]>(areaData)
const columnChange1 = ({ selectedItem, resolve, finish, index, rowIndex }) => {
  const value = index === -1 ? 86 : selectedItem.value
  if (areaData[value]) {
    resolve(
      Object.keys(areaData[value]).map((key) => {
        return {
          value: key,
          label: areaData[value][key],
        }
      })
    )
  } else {
    finish()
  }
}
function handleConfirm({ value }) {
  console.log(value.value)
}
onMounted(() => {
  console.log('area :>> ', area.value)

  value.value = ['150000', '150100', '150121']
})
</script>

<style scoped></style>

### 期望的结果是什么？

再次赋值 仍然被检测的到；
大多数情况下，非首次选择，需要向后端请求数据，并且回显到组件中。

### 实际的结果是什么？

再次赋值三个地址编号，只回显了 第一个城市。
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/90385480/63a2a550-86fd-425b-b8c7-747bf30f0960)

**Comment by sand1018** [comment]
同样的问题，加上 auto-complete 也无效

**Comment by Moonofweisheng** [comment]
> 同样的问题，加上 auto-complete 也无效

你可以试试先在接口返回数据之前不渲染这个，这个问题大概率是[常见问题](https://wot-design-uni.pages.dev/guide/common-problems.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%9C%A8%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E4%B8%8A%E4%BD%BF%E7%94%A8popup%E3%80%81actionsheet%E3%80%81dropdownitem%E7%AD%89%E5%BC%B9%E5%87%BA%E6%A1%86%E7%BB%84%E4%BB%B6%E5%8C%85%E8%A3%B9slider%E3%80%81tabs%E7%AD%89%E7%BB%84%E4%BB%B6%E6%97%B6-slider%E3%80%81tabs%E8%A1%A8%E7%8E%B0%E5%BC%82%E5%B8%B8)中所链接的2个issue带来的。

**Comment by sand1018** [comment]
> > 同样的问题，加上 auto-complete 也无效
> 
> 你可以试试先在接口返回数据之前不渲染这个，这个问题大概率是[常见问题](https://wot-design-uni.pages.dev/guide/common-problems.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%9C%A8%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E4%B8%8A%E4%BD%BF%E7%94%A8popup%E3%80%81actionsheet%E3%80%81dropdownitem%E7%AD%89%E5%BC%B9%E5%87%BA%E6%A1%86%E7%BB%84%E4%BB%B6%E5%8C%85%E8%A3%B9slider%E3%80%81tabs%E7%AD%89%E7%BB%84%E4%BB%B6%E6%97%B6-slider%E3%80%81tabs%E8%A1%A8%E7%8E%B0%E5%BC%82%E5%B8%B8)中所链接的2个issue带来的。

我在组件上加 v-if 等数据加载回来后再显示，他还是没有触发 column-change 事件

**Comment by Moonofweisheng** [comment]
> > > 同样的问题，加上 auto-complete 也无效
> > 
> > 
> > 你可以试试先在接口返回数据之前不渲染这个，这个问题大概率是[常见问题](https://wot-design-uni.pages.dev/guide/common-problems.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%9C%A8%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E4%B8%8A%E4%BD%BF%E7%94%A8popup%E3%80%81actionsheet%E3%80%81dropdownitem%E7%AD%89%E5%BC%B9%E5%87%BA%E6%A1%86%E7%BB%84%E4%BB%B6%E5%8C%85%E8%A3%B9slider%E3%80%81tabs%E7%AD%89%E7%BB%84%E4%BB%B6%E6%97%B6-slider%E3%80%81tabs%E8%A1%A8%E7%8E%B0%E5%BC%82%E5%B8%B8)中所链接的2个issue带来的。
> 
> 我在组件上加 v-if 等数据加载回来后再显示，他还是没有触发 column-change 事件

可以参考最新的文档实现异步加载

**Comment by ZSX-JOJO** [comment]
目前这个问题我也遇到了,请问你们是怎么解决的？

**Comment by 55555778** [comment]
> 目前这个问题我也遇到了,请问你们是怎么解决的？

当数据加载完成之后渲染。 价格v-if 去判断一下。
