### ISSUE TITLE
[Bug 上报] wd-notice-bar组件，在页面初始渲染赋值时可以滚动播放，但如果是已被缓存页面，从其它界面返回时会停止滚动播放

### ISSUE THREAD

**Issue by Daimes** [Moonofweisheng/wot-design-uni#358]
### Wot Design Uni 版本号

1.2.22

### 平台

h5, 微信小程序

### 复现Demo地址

暂无

### 重现步骤

在页面初始渲染赋值时可以滚动播放，但如果是已被缓存页面，从其它界面返回时会停止滚动播放

### 期望的结果是什么？

返回后通知仍可播放

### 实际的结果是什么？

返回界面后播放停止

**Comment by Moonofweisheng** [comment]
微信小程序未复现相关问题，需要补充一下复现demo。

**Comment by ecfxs** [comment]
新建一个新的项目。如果组件出现在 tabBar 导航的页面中，切换到任意其他页面，在切换回该页，该组件就停止运行，不在滚动。小程序和 H5 端均存在该问题。

可能原因：切换页面后，原定时器停止。
自己临时解决办法：在页面 onShow 回调中里重启定时器。

**Comment by lxge** [comment]
> 新建一个新的项目。如果组件出现在 tabBar 导航的页面中，切换到任意其他页面，在切换回该页，该组件就停止运行，不在滚动。小程序和 H5 端均存在该问题。
> 
> 可能原因：切换页面后，原定时器停止。 自己临时解决办法：在页面 onShow 回调中里重启定时器。

遇到一样的问题, 请问怎么在onShow重启定时器, 你是直接改的组件吗, 还是在自己页面里面做的

**Comment by ecfxs** [comment]
> > 新建一个项目。如果组件出现在tabBar导航的页面中，切换到任意其他页面，在切换回该页面，该组件就停止运行，不再滚动。小程序和H5端均存在该问题。
> > 可能原因：切换页面后，原定时器。自己临时解决办法：在页面onShow回调中停止重启定时器。
> 
> 遇到同样的问题，请问怎么在onShow重启，你是直接修改组件吗，还是在自己的页面里面做的

修改组件，设置独立的 ID。在页面回调中，一个组件可以，超过一个组件。没办法判断不同时间的定时器哪个属于哪个，如果你有更好的解决办法也请告诉我。谢谢。
