### ISSUE TITLE
小程序打包问题，现在打包后所有的代码都打在主包中，占用700K空间，有什么方式可以减少体积

### ISSUE THREAD

**Issue by 5565007** [Moonofweisheng/wot-design-uni#361]
### 这个功能解决了什么问题？

小程序打包问题，现在打包后所有的代码都打在主包中，占用700K空间，有什么方式可以减少体积

### 你期望的 API 是什么样子的？

有什么方式可以减少体积

**Comment by Moonofweisheng** [comment]
多个分包都用到的组件和主包使用到的组件都会被打包进主包的。

**Comment by 5565007** [comment]
是啊。这个有没有方式处理一下。主包用到的就打主包里，分包用的，能不能不进主包里呢？

**Comment by Moonofweisheng** [comment]
多个分包公用的，也会打进主包，这是小程序的机制



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月10日(周一) 上午9:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Moonofweisheng/wot-design-uni] 小程序打包问题，现在打包后所有的代码都打在主包中，占用700K空间，有什么方式可以减少体积 (Issue #361)




 
是啊。这个有没有方式处理一下。主包用到的就打主包里，分包用的，能不能不进主包里呢？

**Comment by 5565007** [comment]
好的，谢谢说明，那我明白了。那我再看看有没有其他的方法优化一下打包吧，我现在的包超出限制了

**Comment by Moonofweisheng** [comment]
静态资源，例如图片，可以调整为线上资源，非必要页面可以调整至分包。
