### ISSUE TITLE
[Bug 上报] ImgCropper 图片裁剪组件，该组件中的滚动会触发底部界面的滚动

### ISSUE THREAD

**Issue by Mengrongrong** [Moonofweisheng/wot-design-uni#363]
### Wot Design Uni 版本号

1.2.18

### 平台

微信小程序

### 复现Demo地址

暂时没有

### 重现步骤

背景：部分机型中，ImgCropper 图片裁剪组件中的滚动会触发底部界面的滚动
重现平台：IOS的微信小程序中
重现机型：iphone SE  iphone 12pro

1、A界面中使用裁剪组件。
2、上传图片时，选择使用微信头像，确认后调用裁剪组件
3、裁剪组件中，放大微信头像，多放大几次，然后滑动到图片底部，点击选取
4、确定后上传图片成功，A界面向下滚动了一段距离

### 期望的结果是什么？

裁剪后，底部界面原来在什么位置，现在就应该在什么位置

### 实际的结果是什么？

部分机型中，ImgCropper 图片裁剪组件中的滚动会触发底部界面的滚动

**Comment by Moonofweisheng** [comment]
推测是滚动穿透了，文档中搜索滚动穿透参考一下解决试试呢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Moonofweisheng/wot-design-uni"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月12日(星期三) 上午10:33
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Moonofweisheng/wot-design-uni] [Bug 上报] ImgCropper 图片裁剪组件，该组件中的滚动会触发底部界面的滚动 (Issue #363)





 
Wot Design Uni 版本号
 
1.2.18
 
平台
 
微信小程序
 
复现Demo地址
 
暂时没有
 
重现步骤
 
背景：部分机型中，ImgCropper 图片裁剪组件中的滚动会触发底部界面的滚动
 重现平台：IOS的微信小程序中
 重现机型：iphone SE  iphone 12pro
 
1、A界面中使用裁剪组件。
 2、上传图片时，选择使用微信头像，确认后调用裁剪组件
 3、裁剪组件中，放大微信头像，多放大几次，然后滑动到图片底部，点击选取
 4、确定后上传图片成功，A界面向下滚动了一段距离
 
期望的结果是什么？
 
裁剪后，底部界面原来在什么位置，现在就应该在什么位置
 
实际的结果是什么？
 
部分机型中，ImgCropper 图片裁剪组件中的滚动会触发底部界面的滚动
 
环境信息
 
No response
 
其他补充信息
 
No response

**Comment by Mengrongrong** [comment]
useLockScroll用这个锁住了界面

**Comment by Moonofweisheng** [comment]
> useLockScroll用这个锁住了界面

useLockScroll只适用于h5，小程序上是无效的，可以考虑使用page-meta
