### ISSUE TITLE
[Bug 上报] Picker 选择器在小程序中报错组件错误，Unhandled error during execution of watcher callback 

### ISSUE THREAD

**Issue by gao-xiang** [Moonofweisheng/wot-design-uni#365]
### Wot Design Uni 版本号

1.2.25

### 平台

微信小程序

### 复现Demo地址

https://github.com/gao-xiang/wot-design-un

### 重现步骤

执行： pnpm dev:mp-weixin
在默认首页中部有个单项选择，

加载到微信小程序开发工具中就会报错

### 期望的结果是什么？

修复问题

### 实际的结果是什么？

需要工作

**Comment by Moonofweisheng** [comment]
参考：[常见问题](https://wot-design-uni.pages.dev/guide/common-problems.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%9C%A8%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E4%B8%8A%E4%BD%BF%E7%94%A8popup%E3%80%81actionsheet%E3%80%81dropdownitem%E7%AD%89%E5%BC%B9%E5%87%BA%E6%A1%86%E7%BB%84%E4%BB%B6%E5%8C%85%E8%A3%B9slider%E3%80%81tabs%E7%AD%89%E7%BB%84%E4%BB%B6%E6%97%B6-slider%E3%80%81tabs%E8%A1%A8%E7%8E%B0%E5%BC%82%E5%B8%B8)，在微信端没有列数据之前最好不要将picker渲染出来

**Comment by gao-xiang** [comment]
晕，翻常见问题，没看到最后。。
