### ISSUE TITLE
<wd-loadmore :state="loadingState" /> 不能将类型“string”分配给类型“LoadMoreState | undefined”。

### ISSUE THREAD

**Issue by zebraoo** [Moonofweisheng/wot-design-uni#369]
### Wot Design Uni 版本号

^1.2.24

### 平台

微信小程序

### 复现Demo地址

暂无

### 重现步骤

暂无

### 期望的结果是什么？

暂无

### 实际的结果是什么？

暂无

### 其他补充信息

const loadingState = ref<string>('loading')

**Comment by Moonofweisheng** [comment]
```ts
const loadingState = ref<LoadingState>()
```
