### ISSUE TITLE
[Bug 上报] input组件的type为idcard时不生效

### ISSUE THREAD

**Issue by echofly** [Moonofweisheng/wot-design-uni#377]
### Wot Design Uni 版本号

1.2.26

### 平台

h5, APP

### 复现Demo地址

https://github.com/Moonofweisheng/wot-design-uni

### 重现步骤

![image](https://github.com/Moonofweisheng/wot-design-uni/assets/36875450/fa51c2a0-8f0b-454a-bcae-d4b04ec335f6)
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/36875450/268c9bfc-84a4-423b-9d16-7f7a93b53e93)

### 期望的结果是什么？

**支持身份证输入**

### 实际的结果是什么？

**目前实际上和text类型没啥区别**

**Comment by Moonofweisheng** [comment]
https://github.com/Moonofweisheng/wot-design-uni/assets/26426873/5cddfcbe-f240-4cf5-8b64-af07db919625

未复现，请补充复现demo，否则此issue将被关闭

**Comment by Moonofweisheng** [comment]
h5本身是不支持的，其他平台需要在手机上才会弹出身份证键盘。

**Comment by echofly** [comment]
明白了，实际上App也是不支持的，希望大佬文档上能说明下。
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/36875450/4bb035c0-298e-41a4-b248-9dd3c3a926df)

**Comment by echofly** [comment]
明白了，实际上App也是不支持的，希望大佬文档上能说明下。
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/36875450/4bb035c0-298e-41a4-b248-9dd3c3a926df)

**Comment by Moonofweisheng** [comment]
ok，下版本加上。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Moonofweisheng/wot-design-uni"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月19日(星期三) 下午4:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Moonofweisheng/wot-design-uni] [Bug 上报] input组件的type为idcard时不生效 (Issue #377)





 
明白了，实际上App也是不支持的，希望大佬文档上能说明下。
 image.png (view on web)
