### ISSUE TITLE
[Bug Report] 组件样式丢失，部分组件不显示

### ISSUE THREAD

**Issue by like0413** [Moonofweisheng/wot-design-uni#378]
### Wot Design Uni 版本号

1.2.26

### 平台

微信小程序

### 复现Demo地址

-

### 重现步骤

官方命令：`npx degit dcloudio/uni-preset-vue#vite-ts my-vue3-project`
然后就按照文档的npm安装教程。

最新版的uni升级了vite和vue，是这个原因吗

### 期望的结果是什么？

-

### 实际的结果是什么？

![image](https://github.com/Moonofweisheng/wot-design-uni/assets/48686374/fc3e1878-dc03-43af-91a7-d9775b5b698b)
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/48686374/f5e67a6c-0a37-4be9-b8b1-1f358f81a27d)

### 环境信息

uni版本：3.0.0-alpha-4010520240507001

**Comment by Moonofweisheng** [comment]
换成3.99试试，未提供复现demo，关闭此issue。
