### ISSUE TITLE
SelectPicker 单复选选择器组件

### ISSUE THREAD

**Issue by LTTGGj** [Moonofweisheng/wot-design-uni#38]
### Wot Design Uni 版本号

0.1.7

### 平台

h5, 微信小程序

### 重现链接

https://wot-design-uni.netlify.app/component/select-picker.html

### 重现步骤

组件设置type为radio并且开启搜索 搜索关键词时会报错

### 期望的结果是什么？

正常搜索

### 实际的结果是什么？

报错

**Comment by Moonofweisheng** [comment]
没有复现相关的bug，可否提供更多信息，最好有最小复现demo

**Comment by Moonofweisheng** [comment]
见[0.1.14](https://github.com/Moonofweisheng/wot-design-uni/releases/tag/v0.1.14)
