### ISSUE TITLE
[新功能需求] tab固定宽度在tabs中左对齐

### ISSUE THREAD

**Issue by nickfox-cn** [Moonofweisheng/wot-design-uni#380]
### 这个功能解决了什么问题？

tab固定宽度在tabs中左对齐，当前默认是平均分布，在tab比较少时希望固定宽度左对齐
![b87e7bb3c2ce43314e7963b71041f4a](https://github.com/Moonofweisheng/wot-design-uni/assets/75859003/9820f28e-6340-44ff-81ec-52ea6fd6e4a8)

### 你期望的 API 是什么样子的？

<wd-tabs v-model="tab" align=“left” width="6em">
  <block v-for="item in 3" :key="item">
    <wd-tab :title="`标签${item}`">
      <view class="content">内容{{ item}}</view>
    </wd-tab>
  </block>
</wd-tabs>

**Comment by transtone** [comment]
需要一个左对齐设置，和 wd-col-picker 效果一样。
