### ISSUE TITLE
vue-tsc 检查报错找不到wot-design-uni/global.d.ts

### ISSUE THREAD

**Issue by spriteApe** [Moonofweisheng/wot-design-uni#381]
### Wot Design Uni 版本号

1.2.26

### 平台

h5, 微信小程序, 支付宝小程序, APP, 钉钉小程序, 其他小程序

### 复现Demo地址

https://gitee.com/ly_test/wot-design-uni-demo

### 重现步骤

1. pnpm add wot-design-uni
2. 
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/44717504/2bff686e-6cb2-44f7-992e-e923ee4b1a95)
3. 
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/44717504/7c00e969-b801-4707-bf46-ca385894e23a)

### 期望的结果是什么？

运行vue-tsc 不要报错说找不到wot-design-uni/global.d.ts文件，
也不要运行vue-tsc 就报node_modules/wot-design-uni目录下的错
tsconfig.json文件配置 "exclude": ["node_modules"]是没用的，因为项目中有引用到wot-design-uni相关的组件。

期望提供一个快速的解决方案，或者把wot-design-uni的代码都改一遍符合vue-tsc 的要求，不要报错

### 实际的结果是什么？

使用easycom规范会报错找不到wot-design-uni/global.d.ts文件，
基于vite配置自动引入组件自动引入方案 会报node_modules/wot-design-uni目录下的错

**Comment by Moonofweisheng** [comment]
https://github.com/Moonofweisheng/wot-starter-retail



参考这个看看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月19日(周三) 晚上6:42
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Moonofweisheng/wot-design-uni] vue-tsc 检查报错找不到wot-design-uni/global.d.ts (Issue #381)




 
Wot Design Uni 版本号
 
1.2.26
 
平台
 
h5, 微信小程序, 支付宝小程序, APP, 钉钉小程序, 其他小程序
 
复现Demo地址
 
https://gitee.com/ly_test/wot-design-uni-demo
 
重现步骤
  
pnpm add wot-design-uni
 

  
image.png (view on web)
 3.
 image.png (view on web)
 
期望的结果是什么？
 
运行vue-tsc 不要报错说找不到wot-design-uni/global.d.ts文件，
 也不要运行vue-tsc 就报node_modules/wot-design-uni目录下的错
 tsconfig.json文件配置 "exclude": ["node_modules"]是没用的，因为项目中有引用到wot-design-uni相关的组件。
 
期望提供一个快速的解决方案，或者把wot-design-uni的代码都改一遍符合vue-tsc 的要求，不要报错
 
实际的结果是什么？
 
使用easycom规范会报错找不到wot-design-uni/global.d.ts文件，
 基于vite配置自动引入组件自动引入方案 会报node_modules/wot-design-uni目录下的错
 
环境信息
 
No response
 
其他补充信息
 
No response

**Comment by spriteApe** [comment]
> https://github.com/Moonofweisheng/wot-starter-retail 参考这个看看
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年6月19日(周三) 晚上6:42 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [Moonofweisheng/wot-design-uni] vue-tsc 检查报错找不到wot-design-uni/global.d.ts (Issue #381) Wot Design Uni 版本号 1.2.26 平台 h5, 微信小程序, 支付宝小程序, APP, 钉钉小程序, 其他小程序 复现Demo地址 https://gitee.com/ly_test/wot-design-uni-demo 重现步骤 pnpm add wot-design-uni image.png (view on web) 3. image.png (view on web) 期望的结果是什么？ 运行vue-tsc 不要报错说找不到wot-design-uni/global.d.ts文件， 也不要运行vue-tsc 就报node_modules/wot-design-uni目录下的错 tsconfig.json文件配置 "exclude": ["node_modules"]是没用的，因为项目中有引用到wot-design-uni相关的组件。 期望提供一个快速的解决方案，或者把wot-design-uni的代码都改一遍符合vue-tsc 的要求，不要报错 实际的结果是什么？ 使用easycom规范会报错找不到wot-design-uni/global.d.ts文件， 基于vite配置自动引入组件自动引入方案 会报node_modules/wot-design-uni目录下的错 环境信息 No response 其他补充信息 No response — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

去掉.d.ts后就会报node_modules/wot-design-uni目录下的错
<img width="709" alt="3997e8c04e261e6ecebbe36069f0df50" src="https://github.com/Moonofweisheng/wot-design-uni/assets/44717504/aad695fe-ff0e-467c-9316-a87d74576e4e">

**Comment by Moonofweisheng** [comment]
> > https://github.com/Moonofweisheng/wot-starter-retail 参考这个看看
> > […](#)
> > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2024年6月19日(周三) 晚上6:42 收件人: _**@**_.**_>; 抄送: _**@**_._**>; 主题: [Moonofweisheng/wot-design-uni] vue-tsc 检查报错找不到wot-design-uni/global.d.ts (Issue #381) Wot Design Uni 版本号 1.2.26 平台 h5, 微信小程序, 支付宝小程序, APP, 钉钉小程序, 其他小程序 复现Demo地址 https://gitee.com/ly_test/wot-design-uni-demo 重现步骤 pnpm add wot-design-uni image.png (view on web) 3. image.png (view on web) 期望的结果是什么？ 运行vue-tsc 不要报错说找不到wot-design-uni/global.d.ts文件， 也不要运行vue-tsc 就报node_modules/wot-design-uni目录下的错 tsconfig.json文件配置 "exclude": ["node_modules"]是没用的，因为项目中有引用到wot-design-uni相关的组件。 期望提供一个快速的解决方案，或者把wot-design-uni的代码都改一遍符合vue-tsc 的要求，不要报错 实际的结果是什么？ 使用easycom规范会报错找不到wot-design-uni/global.d.ts文件， 基于vite配置自动引入组件自动引入方案 会报node_modules/wot-design-uni目录下的错 环境信息 No response 其他补充信息 No response — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: _**@**_.**_>
> 
> 去掉.d.ts后就会报node_modules/wot-design-uni目录下的错 <img alt="3997e8c04e261e6ecebbe36069f0df50" width="709" src="https://private-user-images.githubusercontent.com/44717504/341236479-aad695fe-ff0e-467c-9316-a87d74576e4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NTU4NTksIm5iZiI6MTcxODg1NTU1OSwicGF0aCI6Ii80NDcxNzUwNC8zNDEyMzY0NzktYWFkNjk1ZmUtZmYwZS00NjdjLTkzMTYtYTg3ZDc0NTc2ZTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDAzNTIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwMjMwM2QxMmM5OTNmNjQ4OGU1YjYzZDY0OWFmMzE5MjgxNDIwZjRmNDI4N2U1YTNjMDhjNmI1ZmU1ODk2MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.omH9qoyc8VS69wGVrV7RHYcZ-_hnXIw_5Z_YI8ElJ_w">

tsconfig.json用这个
``` json 
// tsconfig.json
{
  // "extends": "@vue/tsconfig/tsconfig.json",
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "jsx": "preserve",
    "resolveJsonModule": true,
    "noImplicitAny": false,
    "importHelpers": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "sourceMap": false,
    "skipLibCheck": true,
    "baseUrl": ".",
    "types": [
      "@dcloudio/types",
      "wot-design-uni/global"
    ],
    "paths": {
      "@/*": [
        "./src/*"
      ]
    },
    "lib": [
      "esnext",
      "dom",
      "dom.iterable",
      "scripthost"
    ]
  },
  "exclude": [
    "node_modules",
    "unpackage",
    "src/**/*.nvue"
  ],
}

```
