### ISSUE TITLE
[新功能需求] cell input下划线希望不要贯穿

### ISSUE THREAD

**Issue by xjt13417680505** [Moonofweisheng/wot-design-uni#384]
### 这个功能解决了什么问题？

cell input下划线希望不要贯穿，想要与左侧对称具有一些空白边距
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/75859003/ea834b61-b59d-4d73-992c-e1ef2a5c56ee)

### 你期望的 API 是什么样子的？

希望下划线的宽度可以独立调整 或者减去的乘2使之对称 width: calc(100% - var(--wot-input-cell-padding, 10px)*2);
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/75859003/3b2d89f4-a813-4b9a-a1d6-73a7df05cf95)

**Comment by daiwanxing** [comment]
我认为用一个 div 包一下，并给这个 div 设置 `padding` 就行了。

![image](https://github.com/Moonofweisheng/wot-design-uni/assets/37327614/b667d3f6-f008-4315-8e22-0f0fff6590a5)

**Comment by Moonofweisheng** [comment]
换成对称的又会有人提不要对称的，这点可以自行depp修改样式调整一下
