### ISSUE TITLE
uniapp的APP端 wd-calendar 的label不适配白天黑夜模式，文字一直是黑色

### ISSUE THREAD

**Issue by lixiaosaKk** [Moonofweisheng/wot-design-uni#388]
### Wot Design Uni 版本号

1.2.27

### 平台

APP

### 复现Demo地址

*

### 重现步骤

如题

### 期望的结果是什么？

label适配白天黑夜模式

### 实际的结果是什么？

wd-calendar 的label不适配白天黑夜模式，文字一直是黑色

**Comment by lixiaosaKk** [comment]
@UphkcRNqmafQWcSSSSSS

**Comment by lixiaosaKk** [comment]
<img width="986" alt="image" src="https://github.com/Moonofweisheng/wot-design-uni/assets/84568102/bdb363aa-2682-4da3-b8ca-640c22f24197">

**Comment by Moonofweisheng** [comment]
确认存在问题
