### ISSUE TITLE
uniapp的H5、 APP端 wd-slider 的step属性设置无效

### ISSUE THREAD

**Issue by lixiaosaKk** [Moonofweisheng/wot-design-uni#392]
### Wot Design Uni 版本号

1.2.28

### 平台

h5, APP

### 复现Demo地址

*

### 重现步骤

    <wd-slider  v-model="test1111" :min="4" :max="100" :step="0.1"/>

### 期望的结果是什么？

    <wd-slider  v-model="test1111" :min="4" :max="100" :step="0.1"/>能正常配置步进值

### 实际的结果是什么？

    <wd-slider  v-model="test1111" :min="4" :max="100" :step="0.1"/>
步进值一直是1

**Comment by Moonofweisheng** [comment]
目前`step`仅支持正整数
