### ISSUE TITLE
[新功能需求] form 表单验证，聚焦和错误提示.

### ISSUE THREAD

**Issue by PdxLook** [Moonofweisheng/wot-design-uni#393]
### 这个功能解决了什么问题？

希望有一个配置，可以切换错误提示显示方式.input底部或者toast提示，并且聚焦错误的第一个输入框。
errorType		String	toast | border-bottom | none

### 你期望的 API 是什么样子的？

```
xml <wd-form ref="form" :model="model" errorType="toast"/>
```

**Comment by wll8** [comment]
当提交表单时，如果有3个验证错误项，这时候我填写其实某一错误项时，另外别个输入框的错误也消失了。官网 demo 也是这样的，请问这是一个功能吗？应如何避免。

**Comment by Moonofweisheng** [comment]
可以选择校验指定字段




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Moonofweisheng/wot-design-uni"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月17日(星期三) 上午9:04
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Moonofweisheng/wot-design-uni] [新功能需求] form 表单验证，聚焦和错误提示. (Issue #393)





 
当提交表单时，如果有3个验证错误项，这时候我填写其实某一错误项时，另外别个输入框的错误也消失了。官网 demo 也是这样的，请问这是一个功能吗？应如何避免。

**Comment by wll8** [comment]
`选择校验指定字段` 就能解决提交时提示所有的错误项，聚焦某项时未聚焦的不清除错误吗

**Comment by Moonofweisheng** [comment]
看下文档，resetOnChange。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月18日(周四) 上午9:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Moonofweisheng/wot-design-uni] [新功能需求] form 表单验证，聚焦和错误提示. (Issue #393)




 
选择校验指定字段 就能解决提交时提示所有的错误项，聚焦某项时未聚焦的不清除错误吗

**Comment by chord-echo** [comment]
> 看下文档，resetOnChange。
> […](#)

需要的是不是resetOnChange，resetOnChange是在form model变化时（任意项）对整个表单的错误信息进行重置，事实上这个属性基本没用，当表单出现多项错误提示时，表单某一项改变后重置了整个表单的错误校验，这样可能会让用户认为那些被重置的项已经通过了校验，或者用户想知道自己还缺少哪些校验没有满足时，必须去一次次点击提交按钮。

需求：RuleType新增trigger，其中某项改变或失去焦点时，遍历其rules，根据trigger进行校验，校验只校验这一项，而不是重置这一项或者所有项，可以参考下antd。

重置某一项、滚动聚焦第一个错误项似乎也没有
