### ISSUE TITLE
[Bug 上报] Sticky 粘性布局 组件的宽度未考虑到使用 tab 等其他组件，宽度不应该在 style 中生成

### ISSUE THREAD

**Issue by bypanghu** [Moonofweisheng/wot-design-uni#396]
### Wot Design Uni 版本号

1.2.28

### 平台

微信小程序

### 复现Demo地址

无

### 重现步骤

Sticky 组件包 search 组件或者 tab 组件

### 期望的结果是什么？

宽度应该有内部撑开，而不是设定为 button的宽度

### 实际的结果是什么？

宽度写死，无法用 css 重置

**Comment by Moonofweisheng** [comment]
如果不使用sticky的话就应该没问题的。你也可以指定一下包裹tabs的元素的宽度，或者自行实现sticky。还有提issue一定要附上完整复现demo。
