### ISSUE TITLE
[新功能需求] MessageBox 弹框异步关闭

### ISSUE THREAD

**Issue by PdxLook** [Moonofweisheng/wot-design-uni#399]
### 这个功能解决了什么问题？

MessageBox 弹框异步关闭；当自定义按钮后，点击实现弹窗关闭。

### 你期望的 API 是什么样子的？

```
import { ref } from 'vue'
import { useMessage, useToast } from 'wot-design-uni'
const message = useMessage('kef-message')
const toast = useToast()


/**
 * 唤醒客服弹窗
 */
function showkef() {
  message.alert({
    title: '微信在线客服',
  })
    .then(() => {
      console.log('点击了确定按钮')
    })
    .catch(() => {
      console.log('点击了取消按钮')
    })
}

/**
 * 关闭弹窗
 */
function hideKf() {
  message.close()
}
```

**Comment by Moonofweisheng** [comment]
可以参考这里[beforConfirm](https://wot-design-uni.pages.dev/component/message-box.html#%E7%A1%AE%E8%AE%A4%E5%89%8D%E7%BD%AE%E5%A4%84%E7%90%86)，看看能否实现你的需求。

**Comment by PdxLook** [comment]
@Moonofweisheng  看了源码， 支持此功能

**Comment by sand1018** [comment]
> 可以参考这里[beforConfirm](https://wot-design-uni.pages.dev/component/message-box.html#%E7%A1%AE%E8%AE%A4%E5%89%8D%E7%BD%AE%E5%A4%84%E7%90%86)，看看能否实现你的需求。

messagebox 使用 watch 监听 options 变化， 是否可以优化成实例调用方法显示隐藏，监听 options 的方式貌似每次初始化都要执行好多次 watch
