### ISSUE TITLE
[新功能需求] custom-class 不能改成 class 吗，用 unocss tailwindcss 这类 很不好用

### ISSUE THREAD

**Issue by ubuding** [Moonofweisheng/wot-design-uni#400]
### 这个功能解决了什么问题？

使用 unocss tailwindcss 时，vscode 无法提供更有效的提示

### 你期望的 API 是什么样子的？

<wd-button class="m-1"></wd-button>

**Comment by Moonofweisheng** [comment]
你可以尝试直接写class，然后开启[mergeVirtualHostAttributes](https://wot-design-uni.pages.dev/guide/common-problems.html#%E8%A7%A3%E5%86%B3%E5%8A%9E%E6%B3%95)，不过这个功能应该只在微信平台生效

**Comment by ubuding** [comment]
个人觉得 custom-class 很不方便

**Comment by Moonofweisheng** [comment]
> 个人觉得 外部样式类 用 custom-class 很不方便， 不如 class

是不方便，但是支持在自定义组件外面写class的一般都支持合并外部样式的，这些平台class是有用的，所以我们做组件库还是不要使用class作为自定义样式类属性，我也感觉头疼，可是这已经是当前比较好的解决办法了。
