### ISSUE TITLE
[新功能需求] Swiper - list数组中指定对象的目标属性名

### ISSUE THREAD

**Issue by PdxLook** [Moonofweisheng/wot-design-uni#410]
### 这个功能解决了什么问题？

const swiperList = ref([
  'https://unpkg.com/wot-design-uni-assets/redpanda.jpg',
  'https://unpkg.com/wot-design-uni-assets/capybara.jpg',
])
当数组为下列格式的时候，指定目标属性名 - image；减少不必要的数据处理
 [
            {
                "title": "广告",
                "image": "https://unpkg.com/wot-design-uni-assets/redpanda.jpg",
                "url": "#"
            },
            {
                "title": "广告图2",
                "image": "https://unpkg.com/wot-design-uni-assets/redpanda.jpg",
                "url": "#"
            }
        ]

### 你期望的 API 是什么样子的？

```<wd-swiper :list="swiperList" keyName="image"></wd-swiper>```

**Comment by Moonofweisheng** [comment]
可以，计划添加`valueKey`支持此需求。

**Comment by PdxLook** [comment]
@Moonofweisheng 
当支持valueKey的时候，click | 点击轮播项时触发 | (index: number，item),
点击时需要返回对应的index,和item内容了，以便获取item处理点击的后续事件。
