### ISSUE TITLE
[Bug 上报] wd-icon 图标在非 http\https 协议中无法显示

### ISSUE THREAD

**Issue by mqyun** [Moonofweisheng/wot-design-uni#415]
### Wot Design Uni 版本号

1.3.0

### 平台

h5

### 复现Demo地址

无

### 重现步骤

![image](https://github.com/Moonofweisheng/wot-design-uni/assets/28822796/9d494736-2390-4d55-82e7-dceb9ab1c11e)
组件依赖的字体库取的是当前环境的协议头，如果运行环境是 file 协议的话，这个资源引用报错。

### 期望的结果是什么？

能正常展示 icon

### 实际的结果是什么？

不能正常展示 icon

**Comment by PdxLook** [comment]
重新跟新一下代码，已经修复为https了

**Comment by Moonofweisheng** [comment]
> 重新跟新一下代码，已经修复为https了

今晚发补丁

**Comment by Moonofweisheng** [comment]
1.3.1支持此功能
