### ISSUE TITLE
wd-swipe-action taouch事件是否能改成mouse事件  h5在pc电脑上访问滑动失效

### ISSUE THREAD

**Issue by springsheep** [Moonofweisheng/wot-design-uni#416]
### Wot Design Uni 版本号

1.2.28

### 平台

h5

### 复现Demo地址

1

### 重现步骤

1

### 期望的结果是什么？

1

### 实际的结果是什么？

1

**Comment by Moonofweisheng** [comment]
可以参考组件库演示demo，引入vant-touch-emulator实现在PC浏览器里面使用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Moonofweisheng/wot-design-uni"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月8日(星期一) 下午2:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Moonofweisheng/wot-design-uni] wd-swipe-action taouch事件是否能改成mouse事件  h5在pc电脑上访问滑动失效 (Issue #416)





 
Wot Design Uni 版本号
 
1.2.28
 
平台
 
h5
 
复现Demo地址
 
1
 
重现步骤
 
1
 
期望的结果是什么？
 
1
 
实际的结果是什么？
 
1
 
环境信息
 
No response
 
其他补充信息
 
No response

**Comment by Moonofweisheng** [comment]
使用[vant-touch-emulator](https://github.com/Moonofweisheng/wot-design-uni/blob/bdbdbd02a4849152296e8dbed42afe0154146c40/src/main.ts#L13)
