### ISSUE TITLE
获取不到ts组件的类型

### ISSUE THREAD

**Issue by 810505339** [Moonofweisheng/wot-design-uni#420]
### Wot Design Uni 版本号

1.3.2

### 平台

h5

### 复现Demo地址

新建一个uniapp 项目然后使用该组件

### 重现步骤

使用的最新版本的vue-official
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/50100966/d3007f6e-19fb-4f36-a5df-44a4fb4bb03a)

//tsconfig.json

```
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "jsx": "preserve",
    "resolveJsonModule": true,
    "noImplicitAny": false,
    "importHelpers": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "sourceMap": false,
    "skipLibCheck": true,
    "baseUrl": ".",
    "types": [
      "@dcloudio/types",
      "miniprogram-api-typings",
      "mini-types",
      "wot-design-uni/global"
    ],
    "paths": {
      "@/*": [
        "./src/*"
      ]
    },
    "lib": [
      "esnext",
      "dom",
      "dom.iterable",
      "scripthost"
    ]
  },
  "exclude": [
    "node_modules",
    "unpackage",
    "src/**/*.nvue"
  ],
}

```

### 期望的结果是什么？

正确的获取到组件的类型

### 实际的结果是什么？

没有获取到组件的类型

**Comment by Moonofweisheng** [comment]
volar回退到2.0.21试试



---原始邮件---
发件人: "like ***@***.***&gt;
发送时间: 2024年7月9日(周二) 中午11:26
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Moonofweisheng/wot-design-uni] 获取不到ts组件的类型 (Issue #420)




 
Wot Design Uni 版本号
 
1.3.2
 
平台
 
h5
 
复现Demo地址
 
新建一个uniapp 项目然后使用该组件
 
重现步骤
 
使用的最新版本的vue-official
 image.png (view on web)
 
//tsconfig.json
 {   "compilerOptions": {     "target": "esnext",     "module": "esnext",     "strict": true,     "jsx": "preserve",     "resolveJsonModule": true,     "noImplicitAny": false,     "importHelpers": true,     "moduleResolution": "node",     "esModuleInterop": true,     "allowSyntheticDefaultImports": true,     "experimentalDecorators": true,     "sourceMap": false,     "skipLibCheck": true,     "baseUrl": ".",     "types": [       ***@***.***/types",       "miniprogram-api-typings",       "mini-types",       "wot-design-uni/global"     ],     "paths": {       "@/*": [         "./src/*"       ]     },     "lib": [       "esnext",       "dom",       "dom.iterable",       "scripthost"     ]   },   "exclude": [     "node_modules",     "unpackage",     "src/**/*.nvue"   ], }  
期望的结果是什么？
 
正确的获取到组件的类型
 
实际的结果是什么？
 
没有获取到组件的类型
 
环境信息
 
No response
 
其他补充信息
 
No response

**Comment by 810505339** [comment]
> volar回退到2.0.21试试
> […](#)
> ---原始邮件--- 发件人: "like ***@***.***&gt; 发送时间: 2024年7月9日(周二) 中午11:26 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [Moonofweisheng/wot-design-uni] 获取不到ts组件的类型 (Issue #420) Wot Design Uni 版本号 1.3.2 平台 h5 复现Demo地址 新建一个uniapp 项目然后使用该组件 重现步骤 使用的最新版本的vue-official image.png (view on web) //tsconfig.json { "compilerOptions": { "target": "esnext", "module": "esnext", "strict": true, "jsx": "preserve", "resolveJsonModule": true, "noImplicitAny": false, "importHelpers": true, "moduleResolution": "node", "esModuleInterop": true, "allowSyntheticDefaultImports": true, "experimentalDecorators": true, "sourceMap": false, "skipLibCheck": true, "baseUrl": ".", "types": [ ***@***.***/types", "miniprogram-api-typings", "mini-types", "wot-design-uni/global" ], "paths": { "@/*": [ "./src/*" ] }, "lib": [ "esnext", "dom", "dom.iterable", "scripthost" ] }, "exclude": [ "node_modules", "unpackage", "src/**/*.nvue" ], } 期望的结果是什么？ 正确的获取到组件的类型 实际的结果是什么？ 没有获取到组件的类型 环境信息 No response 其他补充信息 No response — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

 好像是的 ts版本也只能用4.9.5 就能正确获取到组件的类型了

**Comment by 810505339** [comment]
> > volar回退到2.0.21试试 [...](#) ---原始邮件--- 发件人： “like _**@**_._**> 发送时间： 2024年7月9日（周二） 中午11：26 收件人： _**@**_.**_>;抄送： _**@**_._**>; 主题： [Moonofweisheng/wot-design-uni] 获取不到ts组件的类型 （Issue #420） Wot Design Uni 版本号 1.3.2 平台 h5 复现Demo地址 新建一个uniapp 项目然后使用该组件 重现步骤 使用的最新版本的vue-official image.png （view on web） //tsconfig.json { “compilerOptions”： { “target”： “esnext”， “module”： “esnext”， “strict”： true， “jsx”： “preserve”， “resolveJsonModule”： true， “noImplicitAny”： false， “importHelpers”： true， “moduleResolution”： “node”， “esModuleInterop”： true， “allowSyntheticDefaultImports”： true， “experimentalDecorators”： true， “sourceMap”： false， “skipLibCheck”： true， “baseUrl”： “.”， “types”： [ _**@**_.**_/types“， ”miniprogram-api-typings“， ”mini-types“， ”wot-design-uni/global“ ]， ”paths“： { ”@/_“： [ ”./src/_“ ] }， ”lib“： [ ”esnext“， ”dom“， ”dom.iterable“， ”scripthost“ ] }， ”exclude“： [ ”node_modules“， ”unpackage“， ”src/**/_.nvue“ ]， } 期望的结果是什么？ 正确的获取到组件的类型 实际的结果是什么？ 没有获取到组件的类型 环境信息 No response 其他补充信息 No response — 直接回复此邮件、在 GitHub 上查看或取消订阅。您收到此消息是因为您订阅了此线程。消息 ID：_**@**_。_**>
> 
> 好像是的 ts版本也只能用4.9.5 就能正确获取到组件的类型了

![Uploading image.png…]()
但是好像属性没了

**Comment by Moonofweisheng** [comment]
volar使用2.0.21，typescript使用4.5以下版本。
<img width="377" alt="image" src="https://github.com/Moonofweisheng/wot-design-uni/assets/26426873/1c93f312-c028-4a2e-bca9-e6e4b971edc8">

**Comment by ModyQyW** [comment]
https://github.com/uni-helper/uni-types 可做补充参考

**Comment by zhahngsan** [comment]
根据 https://github.com/uni-helper/uni-types 升级后，volar 2.0.28 版本， ts 5.5.4 版本。复制global.d.ts文件到自己项目目录src/types中，修改后如图
![image](https://github.com/user-attachments/assets/083a6a66-83d5-453a-a7b6-3d110df3a86d)

但是tsconfig.json需要修改为
![image](https://github.com/user-attachments/assets/368ca466-9e98-405f-be9c-48f2e9fa8327)

这样配置后，wd组件就有类型提示了。
这样的问题是需要把exclude代码去掉，不确定去掉后会不会有其他坏处。
不知道作者是否计划升级一下支持新版本ts及volar？

**Comment by CherishMvp** [comment]
有解决办法了吗？

**Comment by Moonofweisheng** [comment]
> 根据 https://github.com/uni-helper/uni-types 升级后，volar 2.0.28 版本， ts 5.5.4 版本。复制global.d.ts文件到自己项目目录src/types中，修改后如图 ![image](https://private-user-images.githubusercontent.com/19809583/356806693-083a6a66-83d5-453a-a7b6-3d110df3a86d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNzUyNTIsIm5iZiI6MTcyNTI3NDk1MiwicGF0aCI6Ii8xOTgwOTU4My8zNTY4MDY2OTMtMDgzYTZhNjYtODNkNS00NTNhLWE3YjYtM2QxMTBkZjNhODZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDExMDIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmOGQzMGMwNDI4ZDM1NWIzNGUxYmMwNGU4NzUxN2YzNmI2OTM1NWY4ZjRkNmM1YzEwNWQ1MmIzNGYxNWI4NmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rx_3ItmUmv6_k3-98kOOLAlxqKrzHN0hlgX8HV_VoTE)
> 
> 但是tsconfig.json需要修改为 ![image](https://private-user-images.githubusercontent.com/19809583/356807927-6dac1983-d455-4920-be97-1a91e03103b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNzUyNTIsIm5iZiI6MTcyNTI3NDk1MiwicGF0aCI6Ii8xOTgwOTU4My8zNTY4MDc5MjctNmRhYzE5ODMtZDQ1NS00OTIwLWJlOTctMWE5MWUwMzEwM2IyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDExMDIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMWQ4MjUyYjAyMWYyMjljZmQxYWMxYmNjMDQwMjFiMDcxYjc4NzhmMjc3MmMzYTU3NDliMjYzMzllMDYxZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zKrvPSeVT0BEl0lbRxEUaGPBkIrHsD0u31tacT1YTKQ)
> 
> 这样配置后，wd组件就有类型提示了。 这样的问题是需要把exclude代码去掉，不确定去掉后会不会有其他坏处。 不知道作者是否计划升级一下支持新版本ts及volar？

已经提交相关改动，1.3.10应该可以支持新版本的ts和volar了

**Comment by Moonofweisheng** [comment]
升级至1.3.10后可以支持新版本的ts和volar。
