### ISSUE TITLE
[Bug 上报] wd-toast在全局容器中配置后，子组件中无法正常使用

### ISSUE THREAD

**Issue by czh1998yr** [Moonofweisheng/wot-design-uni#424]
### Wot Design Uni 版本号

1.3.2

### 平台

h5, APP

### 复现Demo地址

https://github.com/czh1998yr/Toast-Demo

### 重现步骤

运行项目，点击按钮，观察是否有toast

### 期望的结果是什么？

在全局容器中配置之后，子组件、孙组件等无需再次引入即可正常使用toast

### 实际的结果是什么？

在全局容器中配置之后，子组件、孙组件等需再次引入才可正常使用toast

**Comment by Moonofweisheng** [comment]
看常见问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Moonofweisheng/wot-design-uni"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月9日(星期二) 下午4:52
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Moonofweisheng/wot-design-uni] [Bug 上报] wd-toast在全局容器中配置后，子组件中无法正常使用 (Issue #424)





 
Wot Design Uni 版本号
 
1.3.2
 
平台
 
h5, APP
 
复现Demo地址
 
https://github.com/czh1998yr/Toast-Demo
 
重现步骤
 
运行项目，点击按钮，观察是否有toast
 
期望的结果是什么？
 
在全局容器中配置之后，子组件、孙组件等无需再次引入即可正常使用toast
 
实际的结果是什么？
 
在全局容器中配置之后，子组件、孙组件等需再次引入才可正常使用toast
 
环境信息
 
No response
 
其他补充信息
 
No response

**Comment by czh1998yr** [comment]
> 看常见问题
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Moonofweisheng/wot-design-uni" ***@***.***&gt;; 发送时间:&nbsp;2024年7月9日(星期二) 下午4:52 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[Moonofweisheng/wot-design-uni] [Bug 上报] wd-toast在全局容器中配置后，子组件中无法正常使用 (Issue #424) Wot Design Uni 版本号 1.3.2 平台 h5, APP 复现Demo地址 https://github.com/czh1998yr/Toast-Demo 重现步骤 运行项目，点击按钮，观察是否有toast 期望的结果是什么？ 在全局容器中配置之后，子组件、孙组件等无需再次引入即可正常使用toast 实际的结果是什么？ 在全局容器中配置之后，子组件、孙组件等需再次引入才可正常使用toast 环境信息 No response 其他补充信息 No response — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

已经查看过常见问题，并且参考了wot-starter-retail的实现，我的用法我没注意到有错误的地方呢

**Comment by czh1998yr** [comment]
> > 看常见问题 [...](#) ------------------ 原始邮件 ------------------ 发件人： “Moonofweisheng/wot-design-uni” _**@**_._**>; 发送时间： 2024年7月9日（星期二） 下午4：52 _**@**_.**_>;_**@**_。_**>; 主题： [Moonofweisheng/wot-design-uni] [Bug 上报] wd-toast在全局容器中配置后，子组件中无法正常使用 （Issue #424） Wot Design Uni 版本号 1.3.2 平台 h5， APP 复现Demo地址 https://github.com/czh1998yr/Toast-Demo 重现步骤 运行项目，点击按钮，观察是否有toast 期望的结果是什么？ 在全局容器中配置之后，子组件、孙组件等无需再次引入即可正常使用toast 实际的结果是什么？ 在全局容器中配置之后，子组件、孙组件等需再次引入才可正常使用toast 环境信息 No response 其他补充信息 No response — 直接回复此邮件、在 GitHub 上查看或取消订阅。您收到此消息是因为您订阅了此线程。消息 ID：_**@**_。**_>
> 
> 已经查看过常见问题，并且参考了wot-starter-retail的实现，我的用法我没注意到有错误的地方呢

我提供了复现的Demo链接https://github.com/czh1998yr/Toast-Demo

**Comment by Moonofweisheng** [comment]
参考这里




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Moonofweisheng/wot-design-uni"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月9日(星期二) 下午4:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Moonofweisheng/wot-design-uni] [Bug 上报] wd-toast在全局容器中配置后，子组件中无法正常使用 (Issue #424)





   
看常见问题 ... ------------------ 原始邮件 ------------------ 发件人： “Moonofweisheng/wot-design-uni” @.&gt;; 发送时间： 2024年7月9日（星期二） 下午4：52 _@**.&gt;;@。&gt;; 主题： [Moonofweisheng/wot-design-uni] [Bug 上报] wd-toast在全局容器中配置后，子组件中无法正常使用 （Issue #424） Wot Design Uni 版本号 1.3.2 平台 h5， APP 复现Demo地址 https://github.com/czh1998yr/Toast-Demo 重现步骤 运行项目，点击按钮，观察是否有toast 期望的结果是什么？ 在全局容器中配置之后，子组件、孙组件等无需再次引入即可正常使用toast 实际的结果是什么？ 在全局容器中配置之后，子组件、孙组件等需再次引入才可正常使用toast 环境信息 No response 其他补充信息 No response — 直接回复此邮件、在 GitHub 上查看或取消订阅。您收到此消息是因为您订阅了此线程。消息 ID：@。**_&gt;
  
已经查看过常见问题，并且参考了wot-starter-retail的实现，我的用法我没注意到有错误的地方呢
  
我提供了复现的Demo链接https://github.com/czh1998yr/Toast-Demo

**Comment by czh1998yr** [comment]
是的，我有注意到这点，并且在您的 wot-starter-retail 项目中，在 page-wraper 中引用了 <wd-toast />，我的 demo 中也是模仿这种写法，但是在 page-wraper 中的 slot 中，正常使用，然后却该组件的在子组件无法正常使用，并且没有多次调用的情况

**Comment by czh1998yr** [comment]
是的，我有注意到这点，并且在您的 wot-starter-retail 项目中，在 page-wraper 中引用了 ，我的 demo 中也是模仿这种写法，但是在 page-wraper 中的 slot 中，正常使用，然后却该组件的在子组件无法正常使用，并且没有多次调用的情况

**Comment by czh1998yr** [comment]
> 参考这里第二点[当前组件库提供的用于控制组件显示隐藏 hooks 不生效怎么办] https://wot-design-uni.pages.dev/guide/common-problems.html#%E5%BD%93%E5%89%8D%E7%BB%84%E4%BB%B6%E5%BA%93%E6%8F%90%E4%BE%9B%E7%9A%84%E7%94%A8%E4%BA%8E%E6%8E%A7%E5%88%B6%E7%BB%84%E4%BB%B6%E6%98%BE%E7%A4%BA%E9%9A%90%E8%97%8F-hooks-%E4%B8%8D%E7%94%9F%E6%95%88%E6%80%8E%E4%B9%88%E5%8A%9E

是的，我有注意到这点，并且在您的 wot-starter-retail 项目中，在 page-wraper 中引用了 ，我的 demo 中也是模仿这种写法，但是在 page-wraper 中的 slot 中，正常使用，然后却该组件的在子组件无法正常使用，并且没有多次调用的情况

**Comment by Moonofweisheng** [comment]
行 那就晚些等我复现一下看看。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月9日(星期二) 下午5:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Moonofweisheng/wot-design-uni] [Bug 上报] wd-toast在全局容器中配置后，子组件中无法正常使用 (Issue #424)














 
是的，我有注意到这点，并且在您的 wot-starter-retail 项目中，在 page-wraper 中引用了 ，我的 demo 中也是模仿这种写法，但是在 page-wraper 中的 slot 中，正常使用，然后却该组件的在子组件无法正常使用，并且没有多次调用的情况

**Comment by czh1998yr** [comment]
> 行 那就晚些等我复现一下看看。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年7月9日(星期二) 下午5:10 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Moonofweisheng/wot-design-uni] [Bug 上报] wd-toast在全局容器中配置后，子组件中无法正常使用 (Issue #424) 是的，我有注意到这点，并且在您的 wot-starter-retail 项目中，在 page-wraper 中引用了 ，我的 demo 中也是模仿这种写法，但是在 page-wraper 中的 slot 中，正常使用，然后却该组件的在子组件无法正常使用，并且没有多次调用的情况 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

好的，感谢您

**Comment by Moonofweisheng** [comment]
> > 行 那就晚些等我复现一下看看。
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: _**@**_._**>; 发送时间: 2024年7月9日(星期二) 下午5:10 收件人: _**@**_.**_>; 抄送: _**@**_._**>; _**@**_.**_>; 主题: Re: [Moonofweisheng/wot-design-uni] [Bug 上报] wd-toast在全局容器中配置后，子组件中无法正常使用 (Issue #424) 是的，我有注意到这点，并且在您的 wot-starter-retail 项目中，在 page-wraper 中引用了 ，我的 demo 中也是模仿这种写法，但是在 page-wraper 中的 slot 中，正常使用，然后却该组件的在子组件无法正常使用，并且没有多次调用的情况 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 好的，感谢您

复现demo中确实存在此问题，子组件中未在template显示使用<wd-toast>时无法弹出，不过这也是当前组件函数式调用的实现逻辑决定的，我来解释一下：useToast实际上使用provide共享了一个变量，<wd-toast>组件inject之后观测此变量来控制toast的显隐，当子组件中未添加<wd-toast>，而父页面的组件属于上一层，不会接收子组件里面的provide，所以此时useToast所provide的内容便无toast组件接收了，所以在子组件里面使用useToast也需要显式地在SFC中使用<wd-toast>标签。不知道能否解决你的困惑，有问题仍可讨论。

**Comment by czh1998yr** [comment]
> > > 行 那就晚些等我复现一下看看。
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: _**@**_._**>; 发送时间: 2024年7月9日(星期二) 下午5:10 收件人: _**@**_.**_>; 抄送: _**@**_._**>; _**@**_.**_>; 主题: Re: [Moonofweisheng/wot-design-uni] [Bug 上报] wd-toast在全局容器中配置后，子组件中无法正常使用 (Issue #424) 是的，我有注意到这点，并且在您的 wot-starter-retail 项目中，在 page-wraper 中引用了 ，我的 demo 中也是模仿这种写法，但是在 page-wraper 中的 slot 中，正常使用，然后却该组件的在子组件无法正常使用，并且没有多次调用的情况 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> > 
> > 
> > 好的，感谢您
> 
> 复现demo中确实存在此问题，子组件中未在template显示使用`<wd-toast>`时无法弹出，不过这也是当前组件函数式调用的实现逻辑决定的，我来解释一下：`useToast`实际上使用provide共享了一个变量，`<wd-toast>`组件inject之后观测此变量来控制toast的显隐，当子组件中未添加`<wd-toast>`，而父页面的组件属于上一层，不会接收子组件里面的provide，所以此时`useToast`所`provide`的内容便无toast组件接收了，所以在子组件里面使用`useToast`也需要显式地在SFC中使用`<wd-toast>`。不知道能否解决你的困惑，有问题仍可讨论。

好的，感谢您的解答，那目前看来暂时没有好的解决办法，只能在子组件及更深层次的组件去再次引用
