### ISSUE TITLE
[Bug 上报] 官方文档错误

### ISSUE THREAD

**Issue by lixiaosaKk** [Moonofweisheng/wot-design-uni#426]
### Wot Design Uni 版本号

1.2.28

### 平台

h5, 微信小程序, 支付宝小程序, APP, 钉钉小程序, 其他小程序

### 复现Demo地址

*

### 重现步骤

<img width="1994" alt="image" src="https://github.com/Moonofweisheng/wot-design-uni/assets/84568102/2edb9ef1-39e9-45be-b05b-70f6c0ba191a">

### 期望的结果是什么？

<img width="1994" alt="image" src="https://github.com/Moonofweisheng/wot-design-uni/assets/84568102/d4df63e3-58e3-4b73-afb5-7145e4711b6b">

### 实际的结果是什么？

<img width="1994" alt="image" src="https://github.com/Moonofweisheng/wot-design-uni/assets/84568102/44557ee2-a8a9-46e5-b745-d9268253cc84">

**Comment by Moonofweisheng** [comment]
好的，感谢
