### ISSUE TITLE
滑块组件设置最大值最小值不生效

### ISSUE THREAD

**Issue by yibowangsicn** [Moonofweisheng/wot-design-uni#43]
### Wot Design Uni 版本号

0.015

### 平台

微信小程序

### 重现链接

https://wot-design-uni.netlify.app/guide/changelog.html

### 重现步骤

<wd-slider v-model="value" :min="100" :max="1000" />

### 期望的结果是什么？

自定义设置最大值最小值可以实现

### 实际的结果是什么？

不起作用

**Comment by Moonofweisheng** [comment]
已修复，见[0.1.17](https://github.com/Moonofweisheng/wot-design-uni/releases/tag/v0.1.17)
