### ISSUE TITLE
[Bug 上报] tabs change 绑定值变化时触发

### ISSUE THREAD

**Issue by PdxLook** [Moonofweisheng/wot-design-uni#430]
### Wot Design Uni 版本号

1.3.0

### 平台

微信小程序

### 复现Demo地址

无

### 重现步骤

```html
            <wd-tabs custom-class="home-tab" @change="tabChange">
              <block v-for="(item, i) in 3" :key="i">
                <wd-tab title="分类">
                  <view class="content space-y-5 mt-5">
                    {{ item.name }}
                  </view>
                </wd-tab>
              </block>
            </wd-tabs>
            
            /**
 * 分类切换
 * @param event 
 */
function tabChange(event) {
  console.log(event)
}
```
```
bug:
当不设置:name=""时，items.value[state.activeIndex].name 和props.modelValue会同时为0.导致此问题
<wd-tab :title="item.name" >

if (`**items.value[state.activeIndex].name !== props.modelValue**`) {
    emit('change', {
      index: state.activeIndex,
      name: items.value[state.activeIndex].name
    })
    emit('update:modelValue', items.value[state.activeIndex].name)
  }


```

### 期望的结果是什么？

tabChange 输出：{index: 0, name: 0}{index: 1, name: 1} {index: 2, name: 2}

### 实际的结果是什么？

{index: 1, name: 1} {index: 2, name: 2}，点击第一个时，event无任何值

**Comment by Moonofweisheng** [comment]
当前选项为0的话，点击第0项是不会发生选项的变化的，此时也就不会触发change

**Comment by oknixus** [comment]
![35e8941b24d665360ef9119d5e38427](https://github.com/user-attachments/assets/38ae8b76-f4ab-44bd-9c6f-d323e12a2acf)
如图，当点击分类B时，拿到的值是0
![fba91fb2091b9f928258068ca369d68](https://github.com/user-attachments/assets/f09acb5a-2060-4e3d-bbf2-6e8ef0484e79)
当点击分类A时，拿到的值是1。
```
        <wd-tabs v-model="tabActive" @change="handleTabClick">
          <block v-for="child in categoryOpts" :key="child.id">
            <wd-tab :title="child.classify_name">
              <Goods :goodsList="goodsList" />
            </wd-tab>
          </block>
        </wd-tabs>
```
假如categoryOpts的值是：
```
const categoryOpts = [{id: 1, classify_name: "分类A"},{id: 2, classify_name: "分类B"}]
```
当点击图中的分类B时，tabActive的值是 0，那取到的categoryOpts中的id就是 1 ，这显然是错误的

**Comment by oknixus** [comment]
> 当前选项为0的话，点击第0项是不会发生选项的变化的，此时也就不会触发change

不触发这个是ok的，这个没问题。遇到的问题是，点1触发了，拿到的是0，点0触发了，拿到的1
感觉好像是 ++i 写成了 i++，导致最后拿到的值慢一拍

**Comment by PdxLook** [comment]
@oknixus 

:name=""你把id放上去 ，应该能达到你的使用需求， 他们这个点不太清楚是否设计逻辑如此还是bug

**Comment by oknixus** [comment]
好的，谢谢。希望已经是正常的了。当前项目加了个补丁在用
