### ISSUE TITLE
[Bug 上报] Tabbar在iOS设备上开启底部安全距离顶部边框样式错误

### ISSUE THREAD

**Issue by xiguaniubi2023** [Moonofweisheng/wot-design-uni#431]
### Wot Design Uni 版本号

1.2.28 - 1.3.2

### 平台

h5, APP

### 复现Demo地址

无

### 重现步骤

将tabbar添加safeAreaInsetBottom属性

### 期望的结果是什么？

顶部边框应该位于tabbar图标上方

### 实际的结果是什么？

顶部边框与tabbar图标重叠

### 环境信息

发行平台: [H5平台、App]
操作系统 [iOS 17.5.1]
HBuilderX版本 [4.23]
uni-app版本 [4.23]
设备信息 [iPhone X - iPhone 15全系列]

### 其他补充信息
<img width="484" alt="截屏2024-07-11 15 20 47" src="https://github.com/Moonofweisheng/wot-design-uni/assets/141268132/fdea6ca8-a162-4d13-ad9b-8a6c433a87cd">

_No response_

**Comment by Moonofweisheng** [comment]
是不是你没有把原生的tabbar隐藏？补充完整复现demo看看。

**Comment by Moonofweisheng** [comment]
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/26426873/747c1ee0-4b2d-4cfc-af79-b7ee61e28960)

有个项目你可以参考下：  

https://github.com/Moonofweisheng/wot-starter-retail

**Comment by xiguaniubi2023** [comment]
问题已经找到了是编译器版本不一致 同时有编译缓存导致的。我这边重新配置编译器版本，清除所有缓存就正常了

**Comment by Moonofweisheng** [comment]
> 问题已经找到了是编译器版本不一致 同时有编译缓存导致的。我这边重新配置编译器版本，清除所有缓存就正常了

好，这个issue就关闭了
