### ISSUE TITLE
[新功能需求] 希望单选框，图标为点时能修改颜色

### ISSUE THREAD

**Issue by Haoyue-zhi** [Moonofweisheng/wot-design-uni#440]
### 这个功能解决了什么问题？

![截屏2024-07-15 16 25 05](https://github.com/user-attachments/assets/a3f40111-d75f-45f6-970b-0f57905cedda)
目前单选框shape为点时无法自定义颜色，希望可以自定义颜色

### 你期望的 API 是什么样子的？

`<wd-radio-group
            class="flex justify-end"
            modelValue="1"
            shape="dot"
            inline
            checked-color="#C8000A"
          >
            <wd-radio value="1">单选框1</wd-radio>
            <wd-radio value="2">单选框2</wd-radio>
          </wd-radio-group>`

**Comment by yetxx** [comment]
用ConfigProvider能修改wd-radio-group 组件shape=‘dot’属性的颜色吗
