### ISSUE TITLE
[Bug 上报] button点击事件的问题

### ISSUE THREAD

**Issue by www295686243** [Moonofweisheng/wot-design-uni#443]
### Wot Design Uni 版本号

1.3.3

### 平台

h5

### 复现Demo地址

暂无

### 重现步骤

![image](https://github.com/user-attachments/assets/d0b2a149-9b47-428b-bf40-6b43573d50b2)
你这里只是把event.detail放出来了，那我想用stopPropagation方法咋办？我没法阻止穿透了啊

### 期望的结果是什么？

--

### 实际的结果是什么？

--

**Comment by Moonofweisheng** [comment]
`stopPropagation`应该只在h5端有，其他端是没有的，你可以在组件外面包个<view @click.stop=""></view> 先解决下。
