### ISSUE TITLE
[新功能需求] 希望在form上交一个errorType

### ISSUE THREAD

**Issue by ZedCoding** [Moonofweisheng/wot-design-uni#456]
### 这个功能解决了什么问题？

自由配置错误提示方式

### 你期望的 API 是什么样子的？

![}4M 118 )RD2IJT6}G(CW4G](https://github.com/user-attachments/assets/e32a1d9a-70ee-4f86-9b43-e165769d1cdf)

**Comment by Moonofweisheng** [comment]
1.3.8提供
