### ISSUE TITLE
[Bug 上报] wd-picker动态获取columns报错

### ISSUE THREAD

**Issue by zeezzh** [Moonofweisheng/wot-design-uni#457]
### Wot Design Uni 版本号

1.3.5

### 平台

微信小程序

### 复现Demo地址

无

### 重现步骤

` <wd-picker :columns="columns" label="xxx"  v-model="value"  />`
` const columns = ref([]) `
`const value = ref('')`
![image](https://github.com/user-attachments/assets/79450549-6b6c-488a-9d82-da83d447f95d)

### 期望的结果是什么？

columns还未赋值时，初始化报错

### 实际的结果是什么？

不出现报错

**Comment by Moonofweisheng** [comment]
可以在获取到数据之后再渲染

**Comment by Moonofweisheng** [comment]
1.3.8已解决，如仍有问题可以重新提一个issue。
