### ISSUE TITLE
[新功能需求] Swiper 不支持插槽吗？

### ISSUE THREAD

**Issue by dengsong666** [Moonofweisheng/wot-design-uni#459]
### 这个功能解决了什么问题？

轮播的不只是图片，可以是任何元素

### 你期望的 API 是什么样子的？

提供swiper-item插槽

**Comment by flowerwOw0316** [comment]
确实，少了插槽不够灵活，有时候需要在图片上盖上一些文字。

**Comment by Moonofweisheng** [comment]
swiper-item插槽在部分小程序平台无法实现，不过可以提供轮播项标题
