### ISSUE TITLE
[Bug 上报] PickerView 的 wd-picker-view-column__item--active 在H5下失效,未展示出选中色

### ISSUE THREAD

**Issue by magoyama** [Moonofweisheng/wot-design-uni#46]
### Wot Design Uni 版本号

0.1.14

### 平台

h5, APP

### 重现链接

暂无

### 重现步骤

```
<wd-message-box selector="wd-message-box-slot" use-slot>
   <wd-picker-view :columns="state.columns" v-model="state.variable" />
</wd-message-box>
```

在message中使用pickerview,wd-picker-view-column__item--active这个类的颜色无法显示

### 期望的结果是什么？

如同Picker组件一样正常展示选中项

### 实际的结果是什么？

![截屏2023-09-19 16 38 57](https://github.com/Moonofweisheng/wot-design-uni/assets/98217090/4d807cb2-e0f6-4272-87e2-94efb2c6164d)

**Comment by Moonofweisheng** [comment]
这个问题应该是picker-view组件在给uni-app的picker-view组件设置indicator-class时，将z-index设为-1导致的。

**Comment by Moonofweisheng** [comment]
已修复，见[v0.1.18](https://github.com/Moonofweisheng/wot-design-uni/releases/tag/v0.1.18)

**Comment by magoyama** [comment]
感谢大佬,更新神速!!!
