### ISSUE TITLE
[Bug 上报] PickerView SelectPicker 选择器 的弹窗 层级 bug, ios中显示的层级不正确

### ISSUE THREAD

**Issue by yeweihui0223** [Moonofweisheng/wot-design-uni#460]
### Wot Design Uni 版本号

1.3.5

### 平台

APP

### 复现Demo地址

https://bgithub.xyz/yeweihui0223/uniapp-test.git

### 重现步骤

表单内容写scroll-view中，在Android上，PickerView显示是在最顶层的容器的，但在ios中，却显示在scroll-view内了

### 期望的结果是什么？

PickerView显示 都应该是在最顶层的容器的

### 实际的结果是什么？

ios中，PickerView弹窗层显示在scroll-view内，显示内容不完整

**Comment by Moonofweisheng** [comment]
参考uni-app社区[131736](https://ask.dcloud.net.cn/question/131736)，目前iOS端position:fixed在scroll-view里面的表现存在问题，可以将scroll-view调整为view并设置`overflow:auto;`来解决
