### ISSUE TITLE
[新功能需求] MessageBox可配置最大高度显示，超过高度再显示滚动条

### ISSUE THREAD

**Issue by wwlsky** [Moonofweisheng/wot-design-uni#461]
### 这个功能解决了什么问题？

MessageBox有个默认最大高度，超过后会显示滚动条，但有些项目可能刚好就超出一点点，就显示滚动条，不太好看，希望可以用户自行配置，如果不配置则使用默认限制，这样可适配的场景更广

### 你期望的 API 是什么样子的？

```
<wd-message-box limit="{ width: xxx, height: xxx }">
```

**Comment by Moonofweisheng** [comment]
可以通过修改[CSS变量](https://wot-design-uni.cn/component/config-provider.html#%E5%AE%9A%E5%88%B6%E4%B8%BB%E9%A2%98)来实现此功能，对应高度最大值变量：--wot-message-box-content-max-height
