### ISSUE TITLE
[Bug 上报] Tab 标签页与Navbar 导航栏组合时遇到的问题

### ISSUE THREAD

**Issue by 68511992** [Moonofweisheng/wot-design-uni#465]
### Wot Design Uni 版本号

1.3.6

### 平台

微信小程序

### 复现Demo地址

https://github.com/Moonofweisheng/wot-design-uni/

### 重现步骤

Tab 标签页与Navbar 导航栏组合使用时。在小程序端，使用【Navbar 导航栏】固定在顶部<wd-navbar fixed placeholder title="Navbar 导航条" left-arrow safeAreaInsetTop></wd-navbar>  然后我在下方使用【Tab 标签页】想让【Tab 标签页】浮动在【Navbar 导航栏】下方，但是【Tab 标签页】【粘性布局】sticky会让【Navbar 导航栏】固定在顶部的安全距离失效，我在小程序向下划动时【Tab 标签页】不会浮动在【Navbar 导航栏】下，而是自动吸顶到最顶端了。
![image](https://github.com/user-attachments/assets/10973182-cf01-4717-8f70-d2b6e1a76f39)
![image](https://github.com/user-attachments/assets/a66cc582-63f5-4325-92f8-68d986ca990e)

### 期望的结果是什么？

期望
![image](https://github.com/user-attachments/assets/fab831a0-0fd6-47ff-ab9f-c1378b56f424)

### 实际的结果是什么？

实际的结果是，我向下滑动时【Tab 标签页】会自动浮动到最顶了，

**Comment by 68511992** [comment]
在H5端是正常的。

**Comment by 68511992** [comment]
![image](https://github.com/user-attachments/assets/fc612701-a852-4f9c-b3c1-244475149f7f)

**Comment by Moonofweisheng** [comment]
自定义navbar后，页面高度就要加上navbar的高度了，按照你的描述，应该需要将navbar设置为fixed，并且获取navbar所占据的高度，设置为tabs的offset-top。效果参考附件视频。

https://github.com/user-attachments/assets/3dc6e99e-4bf4-412d-bce0-683761bd9f2e

**Comment by 68511992** [comment]
相当于要计算offset-top的值，然后再赋值是吧，我已经这样做了，可以解决。我还说是有更优解，我就不再计算状态栏和导航栏了。

**Comment by Moonofweisheng** [comment]
自定义navbar需要手动指定tabs的offset-top，tabs也无法自动兼容这个场景。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月28日(周日) 中午1:27
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [Moonofweisheng/wot-design-uni] [Bug 上报] Tab 标签页与Navbar 导航栏组合时遇到的问题 (Issue #465)




 
相当于要计算offset-top的值，然后再赋值是吧，我已经这样做了，可以解决。我还说是有更优解，我就不再计算状态栏和导航栏了。

**Comment by 68511992** [comment]
收到，感谢老哥
