### ISSUE TITLE
[Bug 上报] wd-input 显示异常

### ISSUE THREAD

**Issue by tingyuxuan123** [Moonofweisheng/wot-design-uni#470]
### Wot Design Uni 版本号

1.3.5

### 平台

微信小程序

### 复现Demo地址

无

### 重现步骤

![image](https://github.com/user-attachments/assets/2bb796e3-e38d-438c-8a7a-81bc75801c43)
![image](https://github.com/user-attachments/assets/77e80b20-0f1c-4ae1-8bf3-5f25ddb9fa0a)
![image](https://github.com/user-attachments/assets/491c2a49-c20c-488f-aa87-4c0733339780)
input 如果动态赋值了一个0 不展示

![070ca9a60a4c969ebc3fce058bae20eb](https://github.com/user-attachments/assets/9e512898-c385-4a50-a57b-4a4503860523)
![Uploading 9
![1062744f56dc4b926ecfaa17f9349a3e](https://github.com/user-attachments/assets/bb435338-4f4f-404a-9fe3-03bd958aa4c8)
0d5e7db31fe80eaf2c3fd9fba38baa3.png…]()
如果为1或者是其他数就可以展示

### 期望的结果是什么？

0

### 实际的结果是什么？

没有值

**Comment by tingyuxuan123** [comment]
![image](https://github.com/user-attachments/assets/4cee6841-edc6-4a2b-8be6-32e8aca65240)
![image](https://github.com/user-attachments/assets/c1a4b66f-c29f-48a2-96a4-95d916cb6eb3)



![image](https://github.com/user-attachments/assets/695080e9-7d7d-4bf8-8ad7-a40459b7887f)

**Comment by tingyuxuan123** [comment]
@Moonofweisheng  https://github.com/tingyuxuan123/wot-test  Home.vue

**Comment by Moonofweisheng** [comment]
> @Moonofweisheng https://github.com/tingyuxuan123/wot-test Home.vue

这个仓库是否未设置为public，无权限访问。

**Comment by Moonofweisheng** [comment]
不要给input绑定一个undefined，调整成下面的写法：
```ts
const test = ref({num:null})

setTimeout(() => {
      test.value = {num:0}
}, 1000);
```

**Comment by tingyuxuan123** [comment]
这不是bug吗，那为什么 只有值为0的时候才会出现这个问题呢

**Comment by tingyuxuan123** [comment]
demo仓库已经可以访问了，之前忘记公开了不好意思

**Comment by Moonofweisheng** [comment]
> 这不是bug吗，那为什么 只有值为0的时候才会出现这个问题呢

临时解决的话先按我给的示例来。
