### ISSUE TITLE
h5使用弹窗且未关闭，切换页面(tabbar)或返回上一页，导致页面无法滚动

### ISSUE THREAD

**Issue by Qtt9952** [Moonofweisheng/wot-design-uni#473]
### Wot Design Uni 版本号

^1.2.20

### 平台

h5

### 复现Demo地址

~

### 重现步骤

如列表页使用了可滚动的长列表，进入详情页面后使用弹窗，未关闭的情况返回上一页，回到列表页后无法进行滚动。

### 期望的结果是什么？

弹窗时，在 body 元素中使用了 overflow: hidden; 期望在页面切换或组件卸载时恢复滚动状态。

### 实际的结果是什么？

页面切换或组件卸载时仍是无法滚动状态

**Comment by Moonofweisheng** [comment]
可以先关闭popup的lockscroll，等后面我处理一下。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月31日(周三) 下午5:52
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Moonofweisheng/wot-design-uni] h5使用弹窗且未关闭，切换页面(tabbar)或返回上一页，导致页面无法滚动 (Issue #473)




 
Wot Design Uni 版本号
 
^1.2.20
 
平台
 
h5
 
复现Demo地址
 
~
 
重现步骤
 
如列表页使用了可滚动的长列表，进入详情页面后使用弹窗，未关闭的情况返回上一页，回到列表页后无法进行滚动。
 
期望的结果是什么？
 
弹窗时，在 body 元素中使用了 overflow: hidden; 期望在页面切换或组件卸载时恢复滚动状态。
 
实际的结果是什么？
 
页面切换或组件卸载时仍是无法滚动状态
 
环境信息
 
No response
 
其他补充信息
 
No response

**Comment by Qtt9952** [comment]
目前发现 popup 和 wd-message-box 的 Confirm 都会有这个问题
