### ISSUE TITLE
[Bug 上报] Table组件内容很长的时候，导致文本溢出，设置较高的行高不够灵活，不确定文本长度的情况下也是会溢出

### ISSUE THREAD

**Issue by linshenghao** [Moonofweisheng/wot-design-uni#474]
### Wot Design Uni 版本号

v1.3.6

### 平台

h5, 微信小程序

### 复现Demo地址

无

### 重现步骤

在table组件设置一个长文本的内容，文本会溢出
![e3b05c3a1d7b257917e94cd8b8dddba6](https://github.com/user-attachments/assets/77db99e8-9878-45fb-a994-014712189d82)

### 期望的结果是什么？

希望表格可以自适应内容，不要文本溢出

### 实际的结果是什么？

![e3b05c3a1d7b257917e94cd8b8dddba6](https://github.com/user-attachments/assets/e48b622a-5fba-488f-bee4-c11050dbf029)
实际上文本太长时导致内容溢出

### 环境信息

Node18.14.2

**Comment by Moonofweisheng** [comment]
基于当前table的实现，这一点无法避免，只能开发者尽量灵活设置行高和列宽了。
