### ISSUE TITLE
[Bug 上报] wd-input 无lable属性时，下划线颜色加深

### ISSUE THREAD

**Issue by Jinger-Yes** [Moonofweisheng/wot-design-uni#480]
### Wot Design Uni 版本号

1.3.6

### 平台

APP

### 复现Demo地址

https://wot-design-uni.netlify.app/component/input.html

### 重现步骤

![image](https://github.com/user-attachments/assets/1820f262-d338-4e91-8d8b-dcfe9556ee90)

### 期望的结果是什么？

<wd-input type="text" **label="基本用法"** v-model="value" placeholder="请输入..." />
添加label属性，文本框输入值时，下划线颜色正常
不添加label属性，文本框输入值时，下划线颜色正常，不加深（黑色）

### 实际的结果是什么？

不添加label属性，文本框输入值时，下划线验证加深（黑色）

**Comment by Moonofweisheng** [comment]
目前的设计是cell模式的input不会应用激活状态的底部深色分割线。

**Comment by Jinger-Yes** [comment]
目前解决方式：
<wd-input type="text" label=" " label-width="2px" v-model="value" placeholder="请输入..." />
