### ISSUE TITLE
可以添加一个FloatingPanel 浮动面板

### ISSUE THREAD

**Issue by 810505339** [Moonofweisheng/wot-design-uni#509]
### 这个功能解决了什么问题？

![image](https://github.com/user-attachments/assets/7f4013a7-36cb-46c4-9f06-22899fef8082)

### 你期望的 API 是什么样子的？

<wd-floating-panel>
  <view>
    <view
      v-for="i in 26"
      :key="i"
      :title="String.fromCharCode(i + 64)"
      size="large"
    />
  </view>
</wd-floating-panel>

**Comment by RYGRIT** [comment]
我来试试这个

**Comment by roddc** [comment]
这个可以支持从页面顶部向下拖吗
