### ISSUE TITLE
[新功能需求] Fab 悬浮按钮这个组件可以优化一下吗？

### ISSUE THREAD

**Issue by 5565007** [Moonofweisheng/wot-design-uni#512]
### 这个功能解决了什么问题？

 Fab 悬浮按钮组件不需要展开，只需要一个浮动按钮，这个按钮用插槽可以自己定义或内置一个样式，需要用到Fab的定位，拖动功能就可以了，这种需要还是有的。

### 你期望的 API 是什么样子的？

 Fab 悬浮按钮组件不需要展开，只需要一个浮动按钮，这个按钮用插槽可以自己定义或内置一个样式，需要用到Fab的定位，拖动功能就可以了，这种需要还是有的。

**Comment by Moonofweisheng** [comment]
可以。
