### ISSUE TITLE
Skeleton 骨架屏

### ISSUE THREAD

**Issue by missyouliu** [Moonofweisheng/wot-design-uni#52]
### Wot Design Uni 版本号

0.1.19

### 平台

APP

### 重现链接

xxx

### 重现步骤

<view>
    <wd-skeleton animation="gradient" theme="paragraph" />
  </view>
如果没有传入rowCol对象会报
TypeError: Object.hasOwn is not a function

### 期望的结果是什么？

不需要传入rowCol对象

### 实际的结果是什么？

xxx

**Comment by Moonofweisheng** [comment]
见[v0.1.20](https://github.com/Moonofweisheng/wot-design-uni/blob/v0.1.20/CHANGELOG.md)
