### ISSUE TITLE
[Bug 上报] wd-tabs显示异常

### ISSUE THREAD

**Issue by aizela** [Moonofweisheng/wot-design-uni#522]
### Wot Design Uni 版本号

1.3.6(1.3.7也测试了)

### 平台

微信小程序

### 复现Demo地址

https://github.com/aizela/wot-bug/blob/main/index.vue

### 重现步骤

按照文档的示例正常使用
![image](https://github.com/user-attachments/assets/9479de25-ca6e-42b1-a109-926d56098ffc)
当tabs长度在5-6个时(看设备的宽度,应该是正好不需要开启横向滚动的数量),tab的文字显示会出问题,个别文字会不显示
![image](https://github.com/user-attachments/assets/c8a396d7-5d7e-451d-89eb-60787cc4c267)

### 期望的结果是什么？

在不需要开启滚动的情况下也能正常显示

### 实际的结果是什么？

文字长度比其他tab长的一项,文字会被吞掉

### 环境信息

平台:小程序
uniapp版本:3.0.0-alpha-4010520240507001
设备信息:开发者工具就可以复现.大部分设备都可以复现

### 其他补充信息

引入方式是yarn/pnpm安装,node版本为20.15.0(开发项目是yarn+cli模式,测试时的新项目用的hbuilder),easycom引入

**Comment by Moonofweisheng** [comment]
`tabs`选项是均分的宽度，所以需要注意设置的title最好不要超出最大长度。针对此问题，我将会给tab项添加超出隐藏的逻辑。  
![image](https://github.com/user-attachments/assets/25d9eeec-2457-4ca3-9c6b-094ca22c0f29)
