### ISSUE TITLE
[Bug 上报] ActionSheet与Sidebar 一起使用产生的问题

### ISSUE THREAD

**Issue by 5565007** [Moonofweisheng/wot-design-uni#526]
### Wot Design Uni 版本号

1.3.7

### 平台

h5, 微信小程序, 支付宝小程序, APP, 钉钉小程序, 其他小程序

### 复现Demo地址

写了问题代码

### 重现步骤

我使用action-sheet然后在里面放一个sidebar的锚点的方式，wrapper高度设置成70vh，不是100vh后，就会出现问题。这个getRect取的好像是整个屏幕的高度，无法按action-sheet这个高度取，所以滚动那部分就对不上了。有问题。下面的所有代码

<template>
  <wd-action-sheet v-model="mValue" title="标题" :lazy-render="false" @opened="onFilterShow" :safe-area-inset-bottom="false">
    <view ref="filterRef" class="wraper">
      <wd-sidebar v-model="active" @change="handleChange">
        <wd-sidebar-item v-for="(item, index) in categories" :key="index" :value="index" :label="item.label" />
      </wd-sidebar>
      <scroll-view class="flex-1" scroll-y scroll-with-animation :scroll-top="scrollTop" :throttle="false" @scroll="onScroll">
        <view v-for="(item, index) in categories" :key="index" class="category">
          <wd-cell-group :title="item.title" border>
            <wd-cell v-for="(cell, index) in item.items" :key="index" :title="cell.title" :label="cell.label">
              <wd-icon name="github-filled" size="24px"></wd-icon>
            </wd-cell>
          </wd-cell-group>
        </view>
      </scroll-view>
    </view>
  </wd-action-sheet>
</template>

<script lang="ts">
export default {
  name: "rose-filter",
  options: {
    addGlobalClass: true,
    virtualHost: true,
    styleIsolation: "shared",
  },
};
</script>

<script setup lang="ts">
import { getRect, isArray } from "wot-design-uni/components/common/util";
const mValue = ref(false);

const active = ref<number>(0);
const scrollTop = ref<number>(0);
const itemScrollTop = ref<number[]>([]);

const subCategories = new Array(24).fill({ title: "标题文字", label: "这是描述这是描述" }, 0, 24);
const categories = ref([
  {
    label: "分类一",
    title: "标题一",
    items: subCategories,
  },
  {
    label: "分类二",
    title: "标题二",
    items: subCategories,
  },
  {
    label: "分类三",
    title: "标题三",
    items: subCategories.slice(0, 18),
  },
  {
    label: "分类四",
    title: "标题四",
    items: subCategories.slice(0, 21),
  },
  {
    label: "分类五",
    title: "标题五",
    items: subCategories,
  },
  {
    label: "分类六",
    title: "标题六",
    items: subCategories.slice(0, 18),
  },
  {
    label: "分类七",
    title: "标题七",
    items: subCategories,
  },
]);

const filterRef = ref();
const onFilterShow = () => {
  nextTick(() => {
    getRect(".category", true, filterRef.value).then((rects) => {
      if (isArray(rects)) {
        itemScrollTop.value = rects.map((item) => item.top || 0);
        scrollTop.value = rects[active.value].top || 0;
      }
    });
  });
};

function handleChange({ value }) {
  active.value = value;
  scrollTop.value = itemScrollTop.value[value];
}
function onScroll(e) {
  const { scrollTop } = e.detail;
  const threshold = 50; // 下一个标题与顶部的距离
  if (scrollTop < threshold) {
    active.value = 0;
    return;
  }
  const index = itemScrollTop.value.findIndex((top) => top > scrollTop && top - scrollTop <= threshold);
  if (index > -1) {
    active.value = index;
  }
}
</script>

<style scoped>
.wraper {
  display: flex;
  height: calc(70vh - var(--window-top));
  height: calc(70vh - var(--window-top) - constant(safe-area-inset-bottom));
  height: calc(70vh - var(--window-top) - env(safe-area-inset-bottom));
}
</style>

### 期望的结果是什么？

希望能看一下。修复一下。

### 实际的结果是什么？

想做一个类似淘宝查询过滤那样的一个组件

**Comment by 5565007** [comment]
这个是template部分。上面的不知道为什么放不进去

  <wd-action-sheet v-model="mValue" title="标题" :lazy-render="false" @opened="onFilterShow" :safe-area-inset-bottom="false">
    <view ref="filterRef" class="wraper">
      <wd-sidebar v-model="active" @change="handleChange">
        <wd-sidebar-item v-for="(item, index) in categories" :key="index" :value="index" :label="item.label" />
      </wd-sidebar>
      <scroll-view class="flex-1" scroll-y scroll-with-animation :scroll-top="scrollTop" :throttle="false" @scroll="onScroll">
        <view v-for="(item, index) in categories" :key="index" class="category">
          <wd-cell-group :title="item.title" border>
            <wd-cell v-for="(cell, index) in item.items" :key="index" :title="cell.title" :label="cell.label">
              <wd-icon name="github-filled" size="24px"></wd-icon>
            </wd-cell>
          </wd-cell-group>
        </view>
      </scroll-view>
    </view>
  </wd-action-sheet>
  
  
![image](https://github.com/user-attachments/assets/0768836f-4f47-42a3-b6d7-b22267537399)

**Comment by Moonofweisheng** [comment]
view标签上写ref应该是无效的，你应该将当前组件的proxy传入`getRect`。scroll-view实际的高度是否真的是70vh，需要确认下。还有，补充下完整复现demo吧。

**Comment by 5565007** [comment]
https://github.com/Moonofweisheng/wot-starter-retail/pull/1
bug的示例代码已经提交，请查看一下

**Comment by Moonofweisheng** [comment]
[首先，你要看下文档](https://uniapp.dcloud.net.cn/api/ui/nodes-info.html#nodesref-boundingclientrect)

这里是按你的思路，提供给你的修复demo
``` html
const onFilterShow = () => {
  nextTick(() => {
    getRect('.category', true, proxy).then((rects) => {
      console.log('%c [ rects ]-198', 'font-size:13px; background:pink; color:#bf2c9f;', rects)
      if (isArray(rects)) {
        rects.forEach((_, index) => {
          if (index > 0) {
            itemScrollTop.value[index] = (rects[index - 1].height || 0) + (itemScrollTop.value[index - 1] || 0)
          } else {
            itemScrollTop.value[index] = 0
          }
        })
        scrollTop.value = itemScrollTop.value[active.value] || 0
      }
    })
  })
}
```

**Comment by 5565007** [comment]
好的。谢谢大佬的解答，十分感谢
