### ISSUE TITLE
Tag标签组件样式问题

### ISSUE THREAD

**Issue by SyanH** [Moonofweisheng/wot-design-uni#53]
### Wot Design Uni 版本号

0.1.19

### 平台

h5, 微信小程序

### 重现链接

无

### 重现步骤

按照文档操作

### 期望的结果是什么？

显示正确

### 实际的结果是什么？

1. `<wd-tag round>标签</wd-tag>` 目前发现圆角标签样式不太对, 内部的文字不居中, 应该是`.wd-tag.is-round`这个样式的`line-height: 1.2;`导致的
2. `<wd-tag round closable>标签</wd-tag>`可关闭标签的关闭按钮位置也不对
3. `<wd-tag round dynamic @confirm="handleConfirm"></wd-tag>`新增标签的宽度被限制死为`88px`, 导致文字换行

**Comment by Moonofweisheng** [comment]
见[v0.1.20](https://github.com/Moonofweisheng/wot-design-uni/blob/v0.1.20/CHANGELOG.md)
