### ISSUE TITLE
[Bug 上报] Tabbar在iOS设备上开启底部安全距离顶部边框样式错误

### ISSUE THREAD

**Issue by Leepulse0** [Moonofweisheng/wot-design-uni#536]
### Wot Design Uni 版本号

1.3.8

### 平台

微信小程序

### 复现Demo地址

无

### 重现步骤

我在 issue 看到这个问题，但我也清除了缓存，也是遮挡了
这是我的代码：
	<wd-tabbar fixed v-model="tabbar" safe-area-inset-bottom>
		<wd-tabbar-item title="首页" icon="home"></wd-tabbar-item>
		<wd-tabbar-item title="工作台" icon="desktop"></wd-tabbar-item>
		<wd-tabbar-item title="数据" icon="chart"></wd-tabbar-item>
		<wd-tabbar-item title="我的" icon="user"></wd-tabbar-item>
	</wd-tabbar>

### 期望的结果是什么？

顶部边框应该位于tabbar图标上方

### 实际的结果是什么？

顶部边框与tabbar图标重叠

### 环境信息

发行平台: [微信小程序]
操作系统 [iOS 17.5.1]
HBuilderX版本 [4.24]
uni-app版本 [4.24]
设备信息 [iPhone X - iPhone 15全系列]

### 其他补充信息

<img width="387" alt="Snipaste_2024-08-19_17-11-15" src="https://github.com/user-attachments/assets/7c0812d9-7276-4b35-9397-1d6d8095bb83">

**Comment by Leepulse0** [comment]
<wd-tabbar fixed v-model="tabbar" safe-area-inset-bottom>
		<wd-tabbar-item title="首页" icon="home"></wd-tabbar-item>
		<wd-tabbar-item title="工作台" icon="desktop"></wd-tabbar-item>
		<wd-tabbar-item title="数据" icon="chart"></wd-tabbar-item>
		<wd-tabbar-item title="我的" icon="user"></wd-tabbar-item>
	</wd-tabbar>

**Comment by Moonofweisheng** [comment]
检查一下样式先，看看是啥问题。

**Comment by Leepulse0** [comment]
我的项目什么都没，就直接复制文档中的示例
<img width="729" alt="Snipaste_2024-08-19_17-11-15" src="https://github.com/user-attachments/assets/058a0d93-3ea7-44ac-b0cb-08a49065c78a">

**Comment by Moonofweisheng** [comment]
> 我的项目什么都没，就直接复制文档中的示例 <img alt="Snipaste_2024-08-19_17-11-15" width="729" src="https://private-user-images.githubusercontent.com/59757399/359050569-058a0d93-3ea7-44ac-b0cb-08a49065c78a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNTk1MjksIm5iZiI6MTcyNDA1OTIyOSwicGF0aCI6Ii81OTc1NzM5OS8zNTkwNTA1NjktMDU4YTBkOTMtM2VhNy00NGFjLWIwY2ItMDhhNDkwNjVjNzhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDA5MjAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmYmZmZjYyMzYwM2RhYmZmYzk4ZmY0YTNjMWYyNDg0MjU0ZmE4MmQyMmFmMGRjY2Q3OTJmYzMzMDE3MTY4NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9SF-MgChD1aqZ2pMGu5zfvFSQIRbCtv576fDisvD9Do">

那就看一下wot-starter-retail能否复现。

**Comment by Leepulse0** [comment]
尝试过了，都一样
![Uploading Snipaste_2024-08-19_17-11-15.png…]()

**Comment by Leepulse0** [comment]
<img width="1541" alt="Snipaste_2024-08-19_17-11-15" src="https://github.com/user-attachments/assets/2b6fd267-ce5f-4254-92f4-c366b839e1de">

**Comment by Moonofweisheng** [comment]
录屏看一下吧。我这没这个设备一时半会也解决不了，需要你协助排查问题。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月19日(星期一) 下午5:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Moonofweisheng/wot-design-uni] [Bug 上报] Tabbar在iOS设备上开启底部安全距离顶部边框样式错误 (Issue #536)














 
尝试过了，都一样

**Comment by Leepulse0** [comment]
Desktop-2024-8-19_17:29
https://www.vidline.com/share/V0NBHVDDEL/74a72be9d5d729a6c48b8d07b6c4f248
这是视频链接

**Comment by Moonofweisheng** [comment]
> Desktop-2024-8-19_17:29 https://www.vidline.com/share/V0NBHVDDEL/74a72be9d5d729a6c48b8d07b6c4f248 这是视频链接

你用微信开发者工具的模拟器就可以复现是吧？

**Comment by Leepulse0** [comment]
是的发自我的 iPhone在 2024年8月19日，17:34，不如摸鱼去 ***@***.***> 写道：﻿

Desktop-2024-8-19_17:29 https://www.vidline.com/share/V0NBHVDDEL/74a72be9d5d729a6c48b8d07b6c4f248 这是视频链接

你用微信开发者工具的模拟器就可以复现是吧？

**Comment by Leepulse0** [comment]
找问题了，已经解决了
