### ISSUE TITLE
StatusTip 缺省提示自带icon无法展示

### ISSUE THREAD

**Issue by q3156277562** [Moonofweisheng/wot-design-uni#537]
### Wot Design Uni 版本号

1.3.8

### 平台

h5, 微信小程序

### 复现Demo地址

https://wot-design-uni.cn/component/status-tip.html

### 重现步骤

进去就能看到

### 期望的结果是什么？

正常展示icon

### 实际的结果是什么？

无icon展示

**Comment by Moonofweisheng** [comment]
现在应该好了，图片在香港节点的OSS上，偶尔访问不到，可以下载下来用。

**Comment by q3156277562** [comment]
> 现在应该好了，图片在香港节点的OSS上，偶尔访问不到，可以下载下来用。

好的，能否提个建议。这个icon能否使用插槽，有时候并不想用直链或自带的icon，而是想用iconfont之类的第三方icon就比较麻烦

**Comment by Moonofweisheng** [comment]
可以，提个需求吧，这个issue可以关掉了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月20日(星期二) 上午10:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Moonofweisheng/wot-design-uni] StatusTip 缺省提示自带icon无法展示 (Issue #537)














  
现在应该好了，图片在香港节点的OSS上，偶尔访问不到，可以下载下来用。
  
好的，能否提个建议。这个icon能否使用插槽，有时候并不想用直链或自带的icon，而是想用iconfont之类的第三方icon就比较麻烦
