### ISSUE TITLE
[新功能需求] tab标签页组件添加平铺能力

### ISSUE THREAD

**Issue by ul123dr** [Moonofweisheng/wot-design-uni#540]
### 这个功能解决了什么问题？

tab标签页现在只能左右展示，无法平铺展示，自定义custom-class使tab平铺，确发现内部使用v-if判断是否展示，不点击对应的标签，内容不会展示

希望添加ping'p平铺滚动模式
<img width="1107" alt="截屏2024-08-20 16 15 41" src="https://github.com/user-attachments/assets/84c2a3f6-9801-42de-9969-776cb69816aa">

### 你期望的 API 是什么样子的？

``` <wd-tabs v-model="tab" scrollspy ></wd-tabs> ```

**Comment by Moonofweisheng** [comment]
可以尝试不将显示内容放在tab的插槽中，tabs仅用作导航，显示内容自行控制  
```html
<wd-tabs>
 <wd-tab></wd-tab>
 <wd-tab></wd-tab>
 <wd-tab></wd-tab>
</wd-tabs>

<view>
  // 显示内容
</view
```

**Comment by Moonofweisheng** [comment]
已支持，参考参见[slidable](https://wot-design-uni.cn/component/tabs.html#%E5%B7%A6%E5%AF%B9%E9%BD%90%E8%B6%85%E5%87%BA%E5%8D%B3%E5%8F%AF%E6%BB%9A%E5%8A%A8-1-4-0)
