### ISSUE TITLE
[Bug 上报] requestAnimationFrame 和其他组件冲突。

### ISSUE THREAD

**Issue by hzbnb** [Moonofweisheng/wot-design-uni#549]
### Wot Design Uni 版本号

1.3.8

### 平台

微信小程序

### 复现Demo地址

https://github.com/hzb888/sx-vk

### 重现步骤

疑似和 vk 库requestAnimationFrame 变量冲突
![554833f2bc26b6c51479980bd61356e](https://github.com/user-attachments/assets/a48bde1b-cc84-4a4e-8728-6d7168ac2fb4)

### 期望的结果是什么？

正常有遮罩

### 实际的结果是什么？

之间报错 遮罩组件引入失败！！！

**Comment by hzbnb** [comment]
有没有什么解决办法哇，这是vk库的地址 https://gitee.com/vk-uni/vk-uni-cloud-router

**Comment by hzbnb** [comment]
有了 解决办法 
![image](https://github.com/user-attachments/assets/f33a136f-472e-4fb7-ad9e-d0b13b2b009c)

**Comment by hzbnb** [comment]
笑死。。

**Comment by Moonofweisheng** [comment]
<img width="3008" alt="image" src="https://github.com/user-attachments/assets/866e56fe-6db7-416c-b9fa-8862f8591554">
勾选将JS编译成ES5可以解决
