### ISSUE TITLE
Tab 标签页使用sticky粘性布局报错

### ISSUE THREAD

**Issue by missyouliu** [Moonofweisheng/wot-design-uni#55]
### Wot Design Uni 版本号

0.1.20

### 平台

APP

### 重现链接

xx

### 重现步骤

<wd-tabs v-model="tab" swipeable animated sticky>
	<block v-for="(item,index) in tabList" :key="index">
		<wd-tab :title="`${item.title}`" :name="item.title">	
		</wd-tab>
	</block>
</wd-tabs>

### 期望的结果是什么？

tab使用粘性布局不报 [JS Framework] Failed to execute the callback function:
 TypeError: Cannot read property 'height' of null
16:32:11.861 reportJSException >>>> exception function:__WEEX_CALL_JAVASCRIPT__, exception:JavaScript execute error!Uncaught TypeError: Cannot read property 'height' of null
 at  (app-service.js:13632:38)

### 实际的结果是什么？

xx

**Comment by Moonofweisheng** [comment]
需要提供最小复现Demo
