### ISSUE TITLE
[新功能需求] 建议给wd-radio-group添加title属性，作为radio的名称，比如性别

### ISSUE THREAD

**Issue by oknixus** [Moonofweisheng/wot-design-uni#551]
### 这个功能解决了什么问题？

建议像wd-input那样，给wd-radio-group，加上一个title。
目前无法在radio-group上加title的情况下，简短的可在一行显示的radio，就会title一行，radio一行。比如性别：
![image](https://github.com/user-attachments/assets/f386e95e-bee8-4dc0-9504-7f55f4db08ea)

感觉wd-radio-group更需要title

### 你期望的 API 是什么样子的？

```        
  <wd-radio-group v-model="form.gender" title="性别" inline>
      <wd-radio :value="1" shape="dot">男</wd-radio>
      <wd-radio :value="2" shape="dot">女</wd-radio>
  </wd-radio-group>
```
希望上面的代码，可以达到图中性别Radio的这种效果：
![image](https://github.com/user-attachments/assets/c9628e47-513f-4a32-a998-9c2ee46e41d9)

**Comment by jasper-ops** [comment]
这应该是cell的工作来着

**Comment by oknixus** [comment]
> 这应该是cell的工作来着

如果这么说的话，wd-input中的title岂不是画蛇添足了？

**Comment by oknixus** [comment]
抱歉，我说错了，是加label，而不是加title。目前在使用中发现，除了wd-radio-group不支持label标题外，还有wd-input-number也是不支持label标题的。
希望可以给以下组件加上label，用于显示表单的标题：
1. wd-radio-group
2. wd-input-numer

后续发现其它的form组件，需要加label的，我会继续列出来

**Comment by oknixus** [comment]
哦哦好的，理解！🤝
