### ISSUE TITLE
tab切换字体大小颜色变化

### ISSUE THREAD

**Issue by missyouliu** [Moonofweisheng/wot-design-uni#56]
### 这个功能解决了什么问题？

希望选中的tab字体font-weight:bold,未选中的tab字体font-weight: normal且颜色为灰色

### 你期望的 API 是什么样子的？

字体样式

**Comment by Moonofweisheng** [comment]
已强化选中样式，见[v0.1.21](https://github.com/Moonofweisheng/wot-design-uni/releases/tag/v0.1.21).
