### ISSUE TITLE
wd-picker组件多级联动 当第一列或者第二列改变后点击取消按钮 然后再重新打开 后边的第二列或者第三列数据没有重置

### ISSUE THREAD

**Issue by Wwyz-98** [Moonofweisheng/wot-design-uni#562]
### Wot Design Uni 版本号

1.3.6

### 平台

支付宝小程序

### 复现Demo地址

你们官网上边的例子就能复现

### 重现步骤

![WechatIMG263](https://github.com/user-attachments/assets/f9102a9a-1a59-4aa6-8ff2-c67142071405)
默认是北京 北京 西城区 打开弹框选择广州省之后点击取消再重新打开 第二列和第三列数据没有重置

### 期望的结果是什么？

点击取消按钮之后 数据重置

### 实际的结果是什么？

暂无

### 环境信息

支付宝小程序
IOS 16.5
Iphone 12

**Comment by Moonofweisheng** [comment]
确认为bug，感谢反馈。

**Comment by Wwyz-98** [comment]
大概多久修好

**Comment by Moonofweisheng** [comment]
> 大概多久修好

你如果赶时间就在close的时候，按照绑定值重置columns试试，不依赖onChangeDistrict。
