### ISSUE TITLE
【支持性提问】现在最新版本1.3.8支持uniappx吗？

### ISSUE THREAD

**Issue by ylm-king** [Moonofweisheng/wot-design-uni#564]
我通过 uni-modelus 方式和 npm直接安装的方式，在启动的时候都报错了。

**Comment by Moonofweisheng** [comment]
还不支持



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月28日(周三) 晚上10:01
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Moonofweisheng/wot-design-uni] 【支持性提问】现在最新版本1.3.8支持uniappx吗？ (Issue #564)




 
我通过 uni-modelus 方式和 npm直接安装的方式，在启动的时候都报错了。
