### ISSUE TITLE
[Bug 上报] DropMenu 位置不会随着dom滚动

### ISSUE THREAD

**Issue by damengshu** [Moonofweisheng/wot-design-uni#568]
### Wot Design Uni 版本号

1.2.26

### 平台

h5

### 复现Demo地址（如不提供，issue将被直接关闭）

https://wot-design-uni.netlify.app/component/drop-menu.html

### 重现步骤

打开菜单， 滚动页面滚动条

### 期望的结果是什么？

wd-popup 随着页面滚动

### 实际的结果是什么？

wd-popup 固定到了打开的位置

### 环境信息

H5平台

### 其他补充信息

![image](https://github.com/user-attachments/assets/216621b4-31c6-48ea-bd9d-35b74cddb89e)

**Comment by Moonofweisheng** [comment]
滚轮操作是会这样，如果是真实手机访问的话不会的
