### ISSUE TITLE
[Bug 上报] ColPicker点击遮罩关闭，无法触发cancel事件

### ISSUE THREAD

**Issue by www295686243** [Moonofweisheng/wot-design-uni#569]
### Wot Design Uni 版本号

1.3.8

### 平台

h5

### 复现Demo地址（如不提供，issue将被直接关闭）

无

### 重现步骤

无

### 期望的结果是什么？

无

### 实际的结果是什么？

无

**Comment by www295686243** [comment]
看了下源码，原来关闭是触发close，而文档上是写错了，写成cancel

**Comment by www295686243** [comment]
但监听close的话，点遮罩关闭，会触发两次close

**Comment by RYGRIT** [comment]
@Moonofweisheng 点遮罩关闭，执行了两次的问题，是由于在 wd-popup 组件中已经通过 closeOnClickModal 这个属性判断过是否执行关闭操作，然而在 wd-action-sheet 中也去做了同样的事情。我现在修改的方式是将 wd-action-sheet 中的操作屏蔽。你看看这种修改方式合适吗

![wd-action-sheet](https://github.com/user-attachments/assets/d57446be-3be9-4a5b-a045-f6aeca1d634d)

**Comment by Moonofweisheng** [comment]
> @Moonofweisheng 点遮罩关闭，执行了两次的问题，是由于在 wd-popup 组件中已经通过 closeOnClickModal 这个属性判断过是否执行关闭操作，然而在 wd-action-sheet 中也去做了同样的事情。我现在修改的方式是将 wd-action-sheet 中的操作屏蔽。你看看这种修改方式合适吗
> 
> ![wd-action-sheet](https://private-user-images.githubusercontent.com/62373365/365340798-d57446be-3be9-4a5b-a045-f6aeca1d634d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MDcxMTEsIm5iZiI6MTcyNTgwNjgxMSwicGF0aCI6Ii82MjM3MzM2NS8zNjUzNDA3OTgtZDU3NDQ2YmUtM2JlOS00YTViLWEwNDUtZjZhZWNhMWQ2MzRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDE0NDY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0YTNjZTc2NDZiZjM0NDE5N2YyNGMxNjM5MzcxMmJiMWU3MjM5OWI5ZmVhZDdmNTBhZGNjYzNiOWE4MjI4MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Jf3Jwpz5Oj5Eo3eKGTi5mncDcRpBvr1C7VLLeiNed04)

合适，这段逻辑在action-sheet中与popup重复了。  
感谢！
