### ISSUE TITLE
[Bug 上报] form 校验在tab中无效报错

### ISSUE THREAD

**Issue by leikui** [Moonofweisheng/wot-design-uni#587]
### Wot Design Uni 版本号

1.3.9

### 平台

h5, 微信小程序

### 复现Demo地址（如不提供，issue将被直接关闭）

无

### 重现步骤

![image](https://github.com/user-attachments/assets/68e48469-0dfe-45ed-bfa5-139aa3322b16)
![image](https://github.com/user-attachments/assets/3756ebf2-48d9-4b05-8fc5-b54c3f1362ae)
![image](https://github.com/user-attachments/assets/0d1dcabc-67cd-4818-bfd2-92c92a787e57)

### 期望的结果是什么？

正常校验

### 实际的结果是什么？

放在tab外面可以正常校验，但是在里面就不行

**Comment by SuperTylerX** [comment]
因为外层包了for循环，你的form.value拿到的是数组。

**Comment by leikui** [comment]
已解决，是因为v-if的原因
