### ISSUE TITLE
toast被弹窗组件遮挡

### ISSUE THREAD

**Issue by zebraoo** [Moonofweisheng/wot-design-uni#589]
### Wot Design Uni 版本号

^1.2.24

### 平台

微信小程序

### 复现Demo地址（如不提供，issue将被直接关闭）

toast层级高于弹窗组件

### 重现步骤

toast层级高于弹窗组件

### 期望的结果是什么？

toast层级高于弹窗组件

### 实际的结果是什么？

被弹窗组件遮挡

### 环境信息

微信小程序

### 其他补充信息

微信小程序

**Comment by Moonofweisheng** [comment]
可以自行设置toast的zIndex
