### ISSUE TITLE
[Bug 上报] wd-checkbox中custom-label-class中添加的样式全部无效

### ISSUE THREAD

**Issue by oknixus** [Moonofweisheng/wot-design-uni#604]
### Wot Design Uni 版本号

1.3.8

### 平台

微信小程序

### 复现Demo地址（如不提供，issue将被直接关闭）

https://github.com/oknixus/wot-debug

### 重现步骤

```
# 在项目目录中，执行：
pnpm dev:mp-weixin

# 之后打开微信开发者工具，运行，在首页即可看到

### 期望的结果是什么？

custom-label-class中的样式应当生效，而不是被默认样式覆盖

### 实际的结果是什么？

custom-label-class中添加的样式都应当生效

当shape="button"时，custom-label-class中的样式不生效。如下图
![image](https://github.com/user-attachments/assets/5720b8a2-a326-4c04-977c-142f39696e76)
![image](https://github.com/user-attachments/assets/f803a2d0-0c3d-40b7-ac8a-23d04d73cbf4)

**Comment by oknixus** [comment]
wd-radio
wd-checkbox
两个组件的样式，如果可以多一点灵活度就好了。目前，都只能是组件当前的样式，不能通过自定义class来实现其它的风格

**Comment by oknixus** [comment]
建议给每个组件，都提供尽可能大的自由度。比如style上的自由度，建议做到组件中的每个标签都可以直接使用style来设定样式风格。当前是做不到的。有些组件，是在看了源码后，发现max-width可以通过加;的方式，添加多个样式，以使达到需要的样式效果

**Comment by Moonofweisheng** [comment]
看了下复现demo，关于样式无效的问题，class是有传入组件的，只不过某些属性的权重不够。这不是bug，参考这个issue给unocss类加一下!important，应该可以解决你的问题，这是unocss的使用问题，而非组件的实现的问题。

https://github.com/unocss/unocss/issues/523

**Comment by Moonofweisheng** [comment]
> wd-radio wd-checkbox 两个组件的样式，如果可以多一点灵活度就好了。目前，都只能是组件当前的样式，不能通过自定义class来实现其它的风格

关于组件自由度的问题，会逐渐改善。
