### ISSUE TITLE
[新功能需求] Swiper 轮播图希望可以自定义圆角大小

### ISSUE THREAD

**Issue by zohar888444** [Moonofweisheng/wot-design-uni#617]
### 这个功能解决了什么问题？

Swiper 轮播图希望可以自定义圆角大小

### 你期望的 API 是什么样子的？

Swiper 轮播图希望可以自定义圆角大小

**Comment by 810505339** [comment]
![image](https://github.com/user-attachments/assets/a10c22b2-9ba5-4ca7-82d2-2db118fab7f8)

定义css变量`--wot-swiper-radius` 来覆盖圆角大小
