### ISSUE TITLE
[新功能需求] upload定制化展示file-list中的每个item

### ISSUE THREAD

**Issue by IsKaros** [Moonofweisheng/wot-design-uni#619]
### 这个功能解决了什么问题？

满足有定制化展示item的场景
![image](https://github.com/user-attachments/assets/b229cf6e-bbf6-4f4f-8649-d05fa9e53dd4)

### 你期望的 API 是什么样子的？

新增一个插槽选项

**Comment by 810505339** [comment]
新增了`preview-cover` 来自定义扩展`file`样式
