### ISSUE TITLE
[Bug 上报] 单元格右侧没内容，但是右侧也占空间，导致左侧单元格数据换行。

### ISSUE THREAD

**Issue by mimimiaomiao1** [Moonofweisheng/wot-design-uni#621]
### Wot Design Uni 版本号

最新版

### 平台

微信小程序

### 复现Demo地址（如不提供，issue将被直接关闭）

不需要demo

### 重现步骤

![image](https://github.com/user-attachments/assets/2fd216b2-ef5d-42f2-9b88-16ec9ee5ed1e)
.wd-cell__title {
    uni-view {
        width: 100vw;
    }
} 这么写，然后什么deep 穿透在h5和app都能有效果，就是在微信小程序不行。。

### 期望的结果是什么？

能不能有一个配置项什么的？我就写了个title，能不能不让value占用空间呢？

### 实际的结果是什么？

能不能有一个配置项什么的？我就写了个title，能不能不让value占用空间呢？

**Comment by Moonofweisheng** [comment]
你把right移除掉不就行了，或者调整一下设置为flex:0，css可以有很多方案实现。

**Comment by mimimiaomiao1** [comment]
> 你把right移除掉不就行了，或者调整一下设置为flex:0，css可以有很多方案实现。

移除right是什么意思，我都没写这个属性啊，调整flex0 给这个cell加flex:0吗？
![image](https://github.com/user-attachments/assets/9cd88067-35b3-4f4c-abf8-cf78b33e8332)
![image](https://github.com/user-attachments/assets/52111dd8-3f55-4b1f-8084-c9b68712550d)
