### ISSUE TITLE
[新功能需求]  calendar组件添加open事件

### ISSUE THREAD

**Issue by Haoyue-zhi** [Moonofweisheng/wot-design-uni#624]
### 这个功能解决了什么问题？

calendar组件添加open事件，用来在打开calendar时，可以设置page-mate或者其他操作

### 你期望的 API 是什么样子的？

open

**Comment by 810505339** [comment]
![image](https://github.com/user-attachments/assets/0c9e2238-d668-499e-8f7c-566c26ac3039)
`calendar`有`open`事件的

**Comment by Haoyue-zhi** [comment]
![截屏2024-09-24 09 23 35](https://github.com/user-attachments/assets/34aaf358-ab01-4448-8c8e-e9afea51c36b)
我说的是这里面没有，我不是说方法。

**Comment by Haoyue-zhi** [comment]
> ![image](https://private-user-images.githubusercontent.com/50100966/370094645-0c9e2238-d668-499e-8f7c-566c26ac3039.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNDEyNzYsIm5iZiI6MTcyNzE0MDk3NiwicGF0aCI6Ii81MDEwMDk2Ni8zNzAwOTQ2NDUtMGM5ZTIyMzgtZDY2OC00OTllLThmN2MtNTY2YzI2YWMzMDM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDAxMjI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjODYwNTIzZDUzODFkMmQ5YzY0NjlmMzNkNWU1ZjFiNTY2MjAxOWUxYzFiYzM3OTk5MDBmOTk0NWM4YTdlZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5rba2sKvb-0Qq0Ai9md__HwpROiYuJEDJh-PuWGT9QE) `calendar`有`open`事件的

![截屏2024-09-24 09 23 35](https://github.com/user-attachments/assets/a4a01b03-ef21-4d60-a36b-14778be93fa7)
我是说是这里面没有，我不是说方法。

**Comment by 810505339** [comment]
OK 后续会修复
