### ISSUE TITLE
[新功能需求] 建议upload新增 extension 属性

### ISSUE THREAD

**Issue by wss-git** [Moonofweisheng/wot-design-uni#635]
### 这个功能解决了什么问题？

看文档中有说明 微信小程序使用chooseMessageFile实现，H5 使用chooseFile实现。
![image](https://github.com/user-attachments/assets/ef2f978b-35ee-4da5-bd9f-5b0bb82ab014)

uni-app [官方文档](https://uniapp.dcloud.net.cn/api/media/file.html#choosefile) 中说明支持 extension 属性 
![image](https://github.com/user-attachments/assets/bba0781f-faa5-45e6-9a90-e1e2f991f301)

微信小程序[官方文档](https://developers.weixin.qq.com/miniprogram/dev/api/media/image/wx.chooseMessageFile.html)也是支持extension 属性 
![image](https://github.com/user-attachments/assets/81a5df38-c37d-4d56-a308-2ce114606ed6)

### 你期望的 API 是什么样子的？

<wd-upload :extension="['.mp3']" />

**Comment by Moonofweisheng** [comment]
有计划，参见#581

**Comment by wss-git** [comment]
参见https://github.com/Moonofweisheng/wot-design-uni/issues/581
