### ISSUE TITLE
Section 分段器

### ISSUE THREAD

**Issue by missyouliu** [Moonofweisheng/wot-design-uni#64]
### 这个功能解决了什么问题？

```
用作不同视图的切换显示
```

### 你期望的 API 是什么样子的？

```
和fantUI的一样
<hd-section :list="list"></hd-section>
```

**Comment by Moonofweisheng** [comment]
已加入计划，进度见[Discussions](https://github.com/Moonofweisheng/wot-design-uni/discussions/45)

**Comment by Moonofweisheng** [comment]
[v0.1.23](https://github.com/Moonofweisheng/wot-design-uni/releases/tag/v0.1.23)新增了 Segmented 分段器
