### ISSUE TITLE
[新功能需求] w-tabs默认是懒加载的，当我没有切换到的tab时是不渲染的，导致无法调用对应的实例，可以做成参数控制是否懒加载吗

### ISSUE THREAD

**Issue by wekerSnail** [Moonofweisheng/wot-design-uni#641]
### 这个功能解决了什么问题？

当我不需要懒加载时，懒加载就会导致我需要调用的实例不存在，必须要切换过去才能渲染对应的实例。希望类似elemui中次特性可以通过参数来控制是否开启

### 你期望的 API 是什么样子的？

可以通过lazy类似的参数控制tab是否懒加载

**Comment by Moonofweisheng** [comment]
计划支持
