### ISSUE TITLE
输入框的change失效 只有再清空的时候才触发

### ISSUE THREAD

**Issue by yy8z7** [Moonofweisheng/wot-design-uni#642]
### Wot Design Uni 版本号

1.2.26

### 平台

h5

### 复现Demo地址（如不提供，issue将被直接关闭）

没有

### 重现步骤

      <wd-input type="text" v-model="value" placeholder="请输入用户名" @change="handleChange" />
const value = ref('')
const handleChange = (value) => {
  console.log('change', value)
}

### 期望的结果是什么？

修改值时同步更新

### 实际的结果是什么？

修改值时同步更新

**Comment by Moonofweisheng** [comment]
可以监听`input`或者`update:modelValue`，`change`后面会废弃。

**Comment by yy8z7** [comment]
好啊 我用了input了 只是看到文档有change&nbsp; 我看了源码 是没触发
&nbsp;


Role&nbsp;Reversal
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月30日(星期一) 下午4:37
收件人: ***@***.***&gt;; 
抄送: "Role ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Moonofweisheng/wot-design-uni] 输入框的change失效 只有再清空的时候才触发 (Issue #642)














 
可以监听input或者update:modelValue，change后面会废弃。
