### ISSUE TITLE
[新功能需求] wx.getSystemInfoSync is deprecated.Please use wx.getSystemSetting/wx.getAppAuthorizeSetting/wx.getDeviceInfo/wx.getWindowInfo/wx.getAppBaseInfo instead.

### ISSUE THREAD

**Issue by gexin1** [Moonofweisheng/wot-design-uni#644]
### 这个功能解决了什么问题？

wx.getSystemInfoSync 微信不在维护了

### 你期望的 API 是什么样子的？

wx.getSystemSetting/wx.getAppAuthorizeSetting/wx.getDeviceInfo/wx.getWindowInfo/wx.getAppBaseInfo

**Comment by Moonofweisheng** [comment]
参见：https://ask.dcloud.net.cn/question/200699  https://github.com/dcloudio/uni-app/pull/5172  
可以等uni-app修复，我们无需处理。
