### ISSUE TITLE
[Bug 上报] wd-notice-bar 页面A-B返回后，A内的wd-notice-bar停止滚动了

### ISSUE THREAD

**Issue by myHLP** [Moonofweisheng/wot-design-uni#650]
### Wot Design Uni 版本号

1.3.12

### 平台

APP

### 复现Demo地址（如不提供，issue将被直接关闭）

暂无

### 重现步骤

wd-notice-bar 页面A-B返回后，A内的wd-notice-bar停止滚动了

### 期望的结果是什么？

wd-notice-bar 页面A-B返回后，A内的wd-notice-bar继续滚动

### 实际的结果是什么？

不继续滚动

**Comment by Moonofweisheng** [comment]
下版本会修复

**Comment by Moonofweisheng** [comment]
#358
