### ISSUE TITLE
[Bug 上报] slider组件在微信小程序下出现bug，无法正常拖动

### ISSUE THREAD

**Issue by GuoJianjian** [Moonofweisheng/wot-design-uni#654]
### Wot Design Uni 版本号

1.3.10

### 平台

微信小程序

### 复现Demo地址（如不提供，issue将被直接关闭）

https://github.com/GuoJianjian/wotui-slider-bug.git

### 重现步骤

点击"弹出菜单"按钮，拖动slider组件

### 期望的结果是什么？

正常拖动slider组件

### 实际的结果是什么？

slider组件拖动异常

### 环境信息

微信开发者工具调试基础库：3.6.0

**Comment by Moonofweisheng** [comment]
先自行排查下看看[常见问题](https://wot-design-uni.cn/guide/common-problems.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%9C%A8%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E4%B8%8A%E4%BD%BF%E7%94%A8popup%E3%80%81actionsheet%E3%80%81dropdownitem%E7%AD%89%E5%BC%B9%E5%87%BA%E6%A1%86%E7%BB%84%E4%BB%B6%E5%8C%85%E8%A3%B9slider%E3%80%81tabs%E7%AD%89%E7%BB%84%E4%BB%B6%E6%97%B6-slider%E3%80%81tabs%E8%A1%A8%E7%8E%B0%E5%BC%82%E5%B8%B8)
