### ISSUE TITLE
[新功能需求] upload组件增加参数让已上传成功的图片点击后不弹出预览而是调起选择文件

### ISSUE THREAD

**Issue by kqswzhyb** [Moonofweisheng/wot-design-uni#664]
### 这个功能解决了什么问题？

现在重新上传文件要点击删除，才能再次选择文件，用户操作比较麻烦

### 你期望的 API 是什么样子的？

<wd-upload  :click-preview="false"/>

**Comment by Moonofweisheng** [comment]
使用reupload属性控制是否可以重传。
