### ISSUE TITLE
[Bug 上报] input框use-suffix-slot属性不管用

### ISSUE THREAD

**Issue by Haoyue-zhi** [Moonofweisheng/wot-design-uni#665]
### Wot Design Uni 版本号

1.3.12

### 平台

h5

### 复现Demo地址（如不提供，issue将被直接关闭）

无

### 重现步骤

![截屏2024-10-16 12 05 49](https://github.com/user-attachments/assets/21a0f685-0fbf-4192-9daa-7a619bfe421f)

### 期望的结果是什么？

use-suffix-slot属性控制插槽显隐

### 实际的结果是什么？

input框use-suffix-slot属性不管用

**Comment by Moonofweisheng** [comment]
此属性仅用于设置开启插槽，已废弃，下版本移除。
