### ISSUE TITLE
Sticky 粘性布局组件在H5中吸顶后有概率一直吸在顶部无法随滚动恢复

### ISSUE THREAD

**Issue by LTTGGj** [Moonofweisheng/wot-design-uni#67]
### Wot Design Uni 版本号

0.1.23

### 平台

h5

### 重现链接

https://wot-design-uni.netlify.app/component/sticky.html

### 重现步骤

<wd-sticky>
	<view class="padding-sm bg-white" style="width: 100vw;padding-bottom: 0;">
		<wd-segmented :options="tab1.list" v-model:value="tab1.cur" :vibrate-short="true" @change="getlist($event.value)">		</wd-segmented>
	</view>
</wd-sticky>
<view style="height:1000px"></view>
上述代码为复现代码 吸顶组件嵌套分段器组件 在下滑列表页时 吸顶组件有概率一直吸在顶部无法随滚动恢复，只有再次滑倒吸顶位置才能恢复

### 期望的结果是什么？

吸顶组件可以再滚动条超过顶部位置时吸附在最顶部 不超过时随页面滚动

### 实际的结果是什么？

有概率一直吸在顶部无法随滚动恢复

**Comment by Moonofweisheng** [comment]
未复现，发现问题再提
