### ISSUE TITLE
[新功能需求] 请在此填写标题 wd-tabs组件支持 titile支持角标

### ISSUE THREAD

**Issue by TAYUN** [Moonofweisheng/wot-design-uni#672]
### 这个功能解决了什么问题？

比如订单页面每个tab需要添加数量角标显示

### 你期望的 API 是什么样子的？

提供插槽或者角标属性

**Comment by akai-b** [comment]
兄弟目前有找到替代方案吗，我也有需要实现红点的需求，暂时没找到解决方案

**Comment by TAYUN** [comment]
> 兄弟目前有找到替代方案吗，我也有需要实现红点的需求，暂时没找到解决方案

还没有

**Comment by akai-b** [comment]
> > 兄弟目前有找到替代方案吗，我也有需要实现红点的需求，暂时没找到解决方案
> 
> 还没有

我刚刚找到一种比较简陋的做法：在tabs的custom-class里根据红点逻辑定义带相应下标的class,再写好对应下标的样式,，你的是角标的话可以定义data-xx,使用伪类的content: attr(data-xx);的方式实现，希望对你有点帮助
![image](https://github.com/user-attachments/assets/18737fbe-0759-4b54-8d72-f9fa6d122410)

![image](https://github.com/user-attachments/assets/e09907bf-8621-41d3-be5c-56fb504bced5)

**Comment by TAYUN** [comment]
> > > 兄弟目前有找到替代方案吗，我也有需要实现红点的需求，暂时没找到解决方案
> > 
> > 
> > 还没有
> 
> 我刚刚找到一种比较简陋的做法：在tabs的custom-class里根据红点逻辑定义带相应下标的class,再写好对应下标的样式,，你的是角标的话可以定义data-xx,使用伪类的content: attr(data-xx);的方式实现，希望对你有点帮助 ![image](https://private-user-images.githubusercontent.com/63035134/378668425-18737fbe-0759-4b54-8d72-f9fa6d122410.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1Njc4NzQsIm5iZiI6MTcyOTU2NzU3NCwicGF0aCI6Ii82MzAzNTEzNC8zNzg2Njg0MjUtMTg3MzdmYmUtMDc1OS00YjU0LThkNzItZjlmYTZkMTIyNDEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDAzMjYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyNGMwMzRmYTNmN2ZhYTgzMWEzMjI4ODM3MjkxMzk1MTA4YWZkYTkwYTkwZTEyN2IzZjU5YmNkNjhhMDQ1ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LrIeNQ3wqx5NqbRSXkgGM4gWy6MmxmYT7LY---LAJcA)
> 
> ![image](https://private-user-images.githubusercontent.com/63035134/378668518-e09907bf-8621-41d3-be5c-56fb504bced5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1Njc4NzQsIm5iZiI6MTcyOTU2NzU3NCwicGF0aCI6Ii82MzAzNTEzNC8zNzg2Njg1MTgtZTA5OTA3YmYtODYyMS00MWQzLWJlNWMtNTZmYjUwNGJjZWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDAzMjYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlZjA1ZTM5NzlhOTY3NjlhYzVlZDVhMzhlYmE4MDNlYzM0Y2E3ODRlMDgwNGEzNWJiZGM0NWU3NzA2ZWEzNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.a3brkN5-KcrRtfj7XAL5p138SeliGQHa4R9ALbaBYQI)

厉害，想象力真丰富，效果图有吗，看看

**Comment by akai-b** [comment]
> > > > 兄弟目前有找到替代方案吗，我也有需要实现红点的需求，暂时没找到解决方案
> > > 
> > > 
> > > 还没有
> > 
> > 
> > 我刚刚找到一种比较简陋的做法：在tabs的custom-class里根据红点逻辑定义带相应下标的class,再写好对应下标的样式,，你的是角标的话可以定义data-xx,使用伪类的content: attr(data-xx);的方式实现，希望对你有点帮助 ![image](https://private-user-images.githubusercontent.com/63035134/378668425-18737fbe-0759-4b54-8d72-f9fa6d122410.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1Njc4NzQsIm5iZiI6MTcyOTU2NzU3NCwicGF0aCI6Ii82MzAzNTEzNC8zNzg2Njg0MjUtMTg3MzdmYmUtMDc1OS00YjU0LThkNzItZjlmYTZkMTIyNDEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDAzMjYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyNGMwMzRmYTNmN2ZhYTgzMWEzMjI4ODM3MjkxMzk1MTA4YWZkYTkwYTkwZTEyN2IzZjU5YmNkNjhhMDQ1ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LrIeNQ3wqx5NqbRSXkgGM4gWy6MmxmYT7LY---LAJcA)
> > ![image](https://private-user-images.githubusercontent.com/63035134/378668518-e09907bf-8621-41d3-be5c-56fb504bced5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1Njc4NzQsIm5iZiI6MTcyOTU2NzU3NCwicGF0aCI6Ii82MzAzNTEzNC8zNzg2Njg1MTgtZTA5OTA3YmYtODYyMS00MWQzLWJlNWMtNTZmYjUwNGJjZWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDAzMjYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlZjA1ZTM5NzlhOTY3NjlhYzVlZDVhMzhlYmE4MDNlYzM0Y2E3ODRlMDgwNGEzNWJiZGM0NWU3NzA2ZWEzNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.a3brkN5-KcrRtfj7XAL5p138SeliGQHa4R9ALbaBYQI)
> 
> 厉害，想象力真丰富，效果图有吗，看看

![image](https://github.com/user-attachments/assets/245d631b-aff5-426e-8af7-de2d63ba0656)

**Comment by TAYUN** [comment]
> > > > > 兄弟目前有找到替代方案吗，我也有需要实现红点的需求，暂时没找到解决方案
> > > > 
> > > > 
> > > > 还没有
> > > 
> > > 
> > > 我刚刚找到一种比较简陋的做法：在tabs的custom-class里根据红点逻辑定义带相应下标的class,再写好对应下标的样式,，你的是角标的话可以定义data-xx,使用伪类的content: attr(data-xx);的方式实现，希望对你有点帮助 ![image](https://private-user-images.githubusercontent.com/63035134/378668425-18737fbe-0759-4b54-8d72-f9fa6d122410.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1Njc4NzQsIm5iZiI6MTcyOTU2NzU3NCwicGF0aCI6Ii82MzAzNTEzNC8zNzg2Njg0MjUtMTg3MzdmYmUtMDc1OS00YjU0LThkNzItZjlmYTZkMTIyNDEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDAzMjYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyNGMwMzRmYTNmN2ZhYTgzMWEzMjI4ODM3MjkxMzk1MTA4YWZkYTkwYTkwZTEyN2IzZjU5YmNkNjhhMDQ1ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LrIeNQ3wqx5NqbRSXkgGM4gWy6MmxmYT7LY---LAJcA)
> > > ![image](https://private-user-images.githubusercontent.com/63035134/378668518-e09907bf-8621-41d3-be5c-56fb504bced5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1Njc4NzQsIm5iZiI6MTcyOTU2NzU3NCwicGF0aCI6Ii82MzAzNTEzNC8zNzg2Njg1MTgtZTA5OTA3YmYtODYyMS00MWQzLWJlNWMtNTZmYjUwNGJjZWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDAzMjYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlZjA1ZTM5NzlhOTY3NjlhYzVlZDVhMzhlYmE4MDNlYzM0Y2E3ODRlMDgwNGEzNWJiZGM0NWU3NzA2ZWEzNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.a3brkN5-KcrRtfj7XAL5p138SeliGQHa4R9ALbaBYQI)
> > 
> > 
> > 厉害，想象力真丰富，效果图有吗，看看
> 
> ![image](https://private-user-images.githubusercontent.com/63035134/378674639-245d631b-aff5-426e-8af7-de2d63ba0656.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1Njk3NzQsIm5iZiI6MTcyOTU2OTQ3NCwicGF0aCI6Ii82MzAzNTEzNC8zNzg2NzQ2MzktMjQ1ZDYzMWItYWZmNS00MjZlLThhZjctZGUyZDYzYmEwNjU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDAzNTc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzOWFiOTI3MzAxYjNkYmI2NDYxZWQzYTljNjI1ZjQ4MWVhNGQ0NjQ1OWJhZDJjNDkyOTFkN2NkODE0ZGYyYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.g0MBYFKO57u9RIDd7Uy6o7iBEs_hBIHrrbrtpE7xkfs)

界面不错阿，有空我试试，太感谢了。
