### ISSUE TITLE
[新功能需求] SelectPicker 单复选选择器组件打开弹窗时如果已有选中值定位到选中值

### ISSUE THREAD

**Issue by LTTGGj** [Moonofweisheng/wot-design-uni#68]
### 这个功能解决了什么问题？

可以便捷的看到选中值，如果是多选方便取消选中值

### 你期望的 API 是什么样子的？

每次打开弹窗遍历选项并定位到第一个选中值

**Comment by Moonofweisheng** [comment]
安排在0.1.29版本
