### ISSUE TITLE
[Bug 上报] QQ 2群的号码（992131171）错了吗，查无此群

### ISSUE THREAD

**Issue by gmajip** [Moonofweisheng/wot-design-uni#684]
### Wot Design Uni 版本号

1.3.13

### 平台

h5

### 复现Demo地址（如不提供，issue将被直接关闭）

无

### 重现步骤

文档->指南->加群沟通 
文档中的QQ 2群号码992131171，查无此群，文档中号码正确吗？？？

### 期望的结果是什么？

正确的QQ群号

### 实际的结果是什么？

992131171

**Comment by Moonofweisheng** [comment]
应该是加群方式没有允许搜索，调整了，你可以再试试。
