### ISSUE TITLE
[Bug 上报] wd-pagination 无法直接展示

### ISSUE THREAD

**Issue by myHLP** [Moonofweisheng/wot-design-uni#693]
### Wot Design Uni 版本号

1.3.12

### 平台

APP

### 复现Demo地址（如不提供，issue将被直接关闭）

暂无

### 重现步骤

按照示例直接使用

### 期望的结果是什么？

能正常使用

### 实际的结果是什么？

组件无法展示

**Comment by Moonofweisheng** [comment]
![image](https://github.com/user-attachments/assets/eb6f830e-2aba-4f5e-8928-f41234c02fb5)
