### ISSUE TITLE
[Bug 上报] tabbar组件safeAreaInsetBottom不生效，在小程序上没有看到paddingBottom样式

### ISSUE THREAD

**Issue by wekerSnail** [Moonofweisheng/wot-design-uni#695]
### Wot Design Uni 版本号

1.3.13

### 平台

微信小程序

### 复现Demo地址（如不提供，issue将被直接关闭）

暂时没有

### 重现步骤

正常使用

### 期望的结果是什么？

正常可以太高底部

### 实际的结果是什么？

没有任何变化

**Comment by wekerSnail** [comment]
![image](https://github.com/user-attachments/assets/a5a1b9dc-263d-4000-80a1-461db68c28a0)

**Comment by Moonofweisheng** [comment]
看着你也没有设置fixed，此时安全区不会生效。如果设置了fixed，重启一下开发者工具，如果还有问题的话参考一下[wot-demo ](https://github.com/Moonofweisheng/wot-demo)  解决 。  

这个issue没有提供复现demo，直接关闭。
