### ISSUE TITLE
[新功能需求] Swiper 轮播组件是否可支持外部传入是图片类型还是视频，目前如果url没有后缀会识别错误

### ISSUE THREAD

**Issue by lianghang1** [Moonofweisheng/wot-design-uni#712]
### 这个功能解决了什么问题？

目前 Swiper 组件是根据 isImageUrl 判断url后缀的，部分url可能是后台接口地址，没有 .jpg 之类的后缀，造成图片识别为视频。
![image](https://github.com/user-attachments/assets/4be22639-d169-4eff-942a-e9759245aab2)
![image](https://github.com/user-attachments/assets/393a73b6-3709-4819-af76-79aa8bfe4a0f)

### 你期望的 API 是什么样子的？

v-if="isImageUrl(isObj(item) ? item[类型属性] : item)"

**Comment by Moonofweisheng** [comment]
可以的，计划支持。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月14日(周四) 下午3:04
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Moonofweisheng/wot-design-uni] [新功能需求] Swiper 轮播组件是否可支持外部传入是图片类型还是视频 (Issue #712)




 
这个功能解决了什么问题？
 
目前 Swiper 组件是根据 isImageUrl 判断url后缀的，部分url可能是后台接口地址，没有 .jpg 之类的后缀，造成图片识别为视频。
 image.png (view on web)
 
你期望的 API 是什么样子的？
 
v-if="isImageUrl(isObj(item) ? item[类型属性] : item)"
