### ISSUE TITLE
是我用的不对吗，里面组件的样式完全改不了

### ISSUE THREAD

**Issue by huyuan9479** [Moonofweisheng/wot-design-uni#732]
### Wot Design Uni 版本号

1.3.14

### 平台

微信小程序

### 复现Demo地址（如不提供，将被直接关闭）

www

### 重现步骤

<wd-row :gutter="8" custom-class="mt-2">
    <wd-col :span="12" custom-class="one">
      <view class="recommend-row-item">span: 12</view>
    </wd-col>
    <wd-col :span="12">
      <view class="recommend-row-item">span: 12</view>
    </wd-col>
  </wd-row>

:deep(.one) {
    background-color: red;
  }

### 期望的结果是什么？

背景变红色

### 实际的结果是什么？

无效

### 环境信息

微信小程序

**Comment by Moonofweisheng** [comment]
用的不对，看常见问题。
