### ISSUE TITLE
在uniapp中使用Tooltip组件的时候，文字提示已经显现，点击页面其他位置文字提示不会自动隐藏

### ISSUE THREAD

**Issue by breakFetter** [Moonofweisheng/wot-design-uni#734]
### Wot Design Uni 版本号

1.3.10

### 平台

h5, APP

### 复现Demo地址（如不提供，将被直接关闭）

暂无

### 重现步骤

暂无

### 期望的结果是什么？

我希望如果文字提示已经出现的情况下，不管页面点击哪个位置 它都会自动隐藏

### 实际的结果是什么？

我只能手动控制文字提示的隐藏

**Comment by Moonofweisheng** [comment]
![image](https://github.com/user-attachments/assets/4da99146-b8b8-44b0-9a0d-7baa4aa5e4f9)

**Comment by breakFetter** [comment]
> ![image](https://private-user-images.githubusercontent.com/26426873/389354474-4da99146-b8b8-44b0-9a0d-7baa4aa5e4f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MDU1OTUsIm5iZiI6MTczMjUwNTI5NSwicGF0aCI6Ii8yNjQyNjg3My8zODkzNTQ0NzQtNGRhOTkxNDYtYjhiOC00NGIwLTlhMGQtN2JhYTRhYTVlNGY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDAzMjgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxNTU4Zjc3NzQ3ZDJmOGUxYzcwMDI2MGI0MWRiMTRkY2QwZDM2OGI2YjU0NDAwNDRjMGQ0ODRmZTBmNTExNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zonKJeaSI0cktKv_7RyFwPE4YAvmDjGaU0YRrYqhaXM)
我使用的就是useQueue和图片上的demo一致，但是效果不理想

**Comment by Moonofweisheng** [comment]
> > ![image](https://private-user-images.githubusercontent.com/26426873/389354474-4da99146-b8b8-44b0-9a0d-7baa4aa5e4f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MDU1OTUsIm5iZiI6MTczMjUwNTI5NSwicGF0aCI6Ii8yNjQyNjg3My8zODkzNTQ0NzQtNGRhOTkxNDYtYjhiOC00NGIwLTlhMGQtN2JhYTRhYTVlNGY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDAzMjgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxNTU4Zjc3NzQ3ZDJmOGUxYzcwMDI2MGI0MWRiMTRkY2QwZDM2OGI2YjU0NDAwNDRjMGQ0ODRmZTBmNTExNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zonKJeaSI0cktKv_7RyFwPE4YAvmDjGaU0YRrYqhaXM)
> > 我使用的就是useQueue和图片上的demo一致，但是效果不理想

文档拉到底部，有demo的源码，可以参考。
