### ISSUE TITLE
[Bug 上报] 1.4.0Swiper 轮播

### ISSUE THREAD

**Issue by Rem-Blove** [Moonofweisheng/wot-design-uni#735]
### Wot Design Uni 版本号

1.4.0

### 平台

微信小程序

### 复现Demo地址（如不提供，将被直接关闭）

无

### 重现步骤

![image](https://github.com/user-attachments/assets/f9704401-d546-4cce-8cb7-7e1b1e94db77)
![image](https://github.com/user-attachments/assets/1e22988f-a150-4b9c-b448-13eca4a986fa)

### 期望的结果是什么？

尽快修复！！！

### 实际的结果是什么？

在1.13.14图片可以正常显示，在1.4.0无法显示图片

### 环境信息
系统版本：win11
uniapp: 4.33.2024111702-alpha

**Comment by Moonofweisheng** [comment]
复现数据提供一下

**Comment by Rem-Blove** [comment]
> 复现数据提供一下，截图里面的list，给个json。

[
    {
        "createBy": null,
        "createTime": "2024-11-19 10:07:31",
        "id": 7,
        "isDisplay": "1",
        "relevantId": 3,
        "relevantName": "数学为什么这么难",
        "remark": null,
        "remarks": null,
        "slideshowUrl": "https://img.pub/p/199ae31dcabee7e05cd2.jpg",
        "type": "1",
        "updateBy": null,
        "updateTime": "2024-11-19 10:07:30"
    }
]
