### ISSUE TITLE
[Bug 上报] wd-row组件微信小程序无法手动绑定style样式，h5正常

### ISSUE THREAD

**Issue by baymax-arch** [Moonofweisheng/wot-design-uni#736]
### Wot Design Uni 版本号

1.3.9

### 平台

h5, 微信小程序

### 复现Demo地址（如不提供，将被直接关闭）

   <wd-row       custom-class="wd-col-self"       :gutter="10"       :style="{         border: '1px solid red',       }"     ></wd-row>

### 重现步骤

![image](https://github.com/user-attachments/assets/7a3387ed-7422-4511-8216-cab657c61808)
![image](https://github.com/user-attachments/assets/95061ac1-56e7-4f1f-90f0-ddd76a1fee4a)
![image](https://github.com/user-attachments/assets/cba724cb-a601-4ac3-bd1d-29ec5d59ba01)

### 期望的结果是什么？

wd-row组件  微信小程序支持动态绑定style

### 实际的结果是什么？

wd-row组件  微信小程序不支持动态绑定style

**Comment by baymax-arch** [comment]
> ```
>    <wd-row
>       custom-class="wd-col-self"
>       :gutter="10"
>       :style="{
>         border: '1px solid red',
>       }"
>     ></wd-row>
> ```

简单demo，可以复现

**Comment by Moonofweisheng** [comment]
看常见问题，微信小程序自定义组件想要合并外部css，需要加配置，最好还是使用`custom-style`或者`custom-class`实现
```html
   <wd-row
      custom-class="wd-col-self"
      :gutter="10"
      custom-style="border: 1px solid red"
    ></wd-row>
```
