### ISSUE TITLE
[Bug 上报] 1.4.0版本 collapse折叠面板 v-model 不支持 数组赋空 收起，1.3.11版本支持。

### ISSUE THREAD

**Issue by sunllight111** [Moonofweisheng/wot-design-uni#741]
### Wot Design Uni 版本号

1.4.0

### 平台

APP

### 复现Demo地址（如不提供，将被直接关闭）

暂无

### 重现步骤

<wd-collapse v-model="chosenValue" >

const chosenValue= ref([])

chosenValue.value=[]

chosenValue.value.push(val)  

### 期望的结果是什么？

chosenValue.value=[] //赋空收起

chosenValue.value.push(val)  //该部分在@change部分根据反馈的value 进行 push操作

### 实际的结果是什么？

赋空收起失效

**Comment by Moonofweisheng** [comment]
临时解决：使用toggleAll方法关闭。  

1.4.1 版本会修复此问题。
