### ISSUE TITLE
[Bug 上报] tabs组件animated与sticky共存时导致发生切换内容容器偏移

### ISSUE THREAD

**Issue by Glamours** [Moonofweisheng/wot-design-uni#742]
### Wot Design Uni 版本号

1.4.0

### 平台

h5, 微信小程序

### 复现Demo地址（如不提供，将被直接关闭）

暂无

### 重现步骤

更新至1.4.0后tab组件原有的animated与sticky共存时导致发生切换内容容器偏移，之前版本没有此问题
<wd-tabs v-model="tab" animated sticky></wd-tabs>

### 期望的结果是什么？

应支持animated与sticky配合使用切换时容器内容无偏移

### 实际的结果是什么？

animated与sticky共存时将导致切换内容容器偏移

**Comment by Moonofweisheng** [comment]
是什么现象？描述清楚一些，怎么偏移的。

**Comment by Moonofweisheng** [comment]
> > 你好，@Glamours。
> > 我们需要你提供一个最小重现demo，以便于我们帮你排查问题。你可以通过 [create-uni](https://github.com/uni-helper/create-uni) 快速创建一个wot-design-uni项目，并添加相关复现逻辑来提供。
> 
> ![QQ20241128-114522](https://private-user-images.githubusercontent.com/10833141/390632943-79c97b93-d920-4f73-bf8c-639ac996bcf1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NjYyNTYsIm5iZiI6MTczMjc2NTk1NiwicGF0aCI6Ii8xMDgzMzE0MS8zOTA2MzI5NDMtNzljOTdiOTMtZDkyMC00ZjczLWJmOGMtNjM5YWM5OTZiY2YxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDAzNTIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4MzdhNDk1MDgxZDMyMjc2YWY1YjJlOWI5ZTkwM2Y2ZGYwMmJlMjM4MzIzNjllODFiOWM1NWUzZTAzMjY0ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NMT69yd6324y7KPt3aAByEPj5t_VRdhYGOIpYwmdQeQ)

图片看不出问题，提供点详细点的信息，，示例代码，复现demo给一下。

**Comment by Moonofweisheng** [comment]
可以自行设置tab子项的宽度，保证不要超出屏幕宽度。
```
      <wd-tabs v-model="tabWithBadge" @change="handleChange">
        <wd-tab v-for="(item, index) in tabsWithBadge" :key="index" :title="`${item.title}`" :badge-props="item.badgeProps">
          <view class="content">{{ item.title }}徽标</view>
        </wd-tab>
      </wd-tabs>
```
```
.content{
width:100vw;
}
```
