### ISSUE TITLE
文档中wd-cell的custom-titlec-class的说明是不是错了？

### ISSUE THREAD

**Issue by buptzyf** [Moonofweisheng/wot-design-uni#772]
这是文档说明，https://wot-design-uni.cn/component/cell.html#cell-%E5%A4%96%E9%83%A8%E6%A0%B7%E5%BC%8F%E7%B1%BB指出是title 使用 slot 时的自定义样式

源码中是

        <view class="wd-cell__title">
          
          <view v-if="title" :class="customTitleClass">{{ title }}</view>
          <slot v-else name="title"></slot>
          

          
          <view v-if="label" :class="`wd-cell__label ${customLabelClass}`">{{ label }}</view>
          <slot v-else name="label" />
          
        </view>

**Comment by Moonofweisheng** [comment]
是错了
