### ISSUE TITLE
官网演示建议

### ISSUE THREAD

**Issue by sql0041** [Moonofweisheng/wot-design-uni#773]
### Wot Design Uni 版本号

1.50

### 平台

h5, 微信小程序

### 复现Demo地址（如不提供，将被直接关闭）

https://wot-design-uni.pages.dev/component/input#attributes

### 重现步骤

进入官网后右侧效果展示区域显示不完整 本机的显示器大小为1920*1080

### 期望的结果是什么？

在浏览器中能够完全展示

### 实际的结果是什么？

目前有一部分是被遮盖没有展示 只有缩放浏览器或修改显示器的分辨率才可以正常显示全部
建议滚动事件也优化一下

**Comment by PdxLook** [comment]
![image](https://github.com/user-attachments/assets/ac4507f6-0d5b-4833-bf49-86593e8dfdb6)
![image](https://github.com/user-attachments/assets/ea5067a4-d9e8-4bf4-981b-656cd45c4407)
是否浏览器开了缩小放大？
