### ISSUE TITLE
IndexBar组件索引错误问题

### ISSUE THREAD

**Issue by liumang666** [Moonofweisheng/wot-design-uni#774]
### Wot Design Uni 版本号

1.5.1

### 平台

微信小程序

### 复现Demo地址（如不提供，将被直接关闭）

https://wot-design-uni.netlify.app/component/index-bar.html

### 重现步骤

复制官方的IndexBar组件例子，使用安卓手机打开小程序，点击组件右侧索引，当点击D的时候，城市列表D置顶了，但是索引值却变成C，除了点击ABC索引是正常的，其余DEFGH缩影点击的时候都会显示成前一个索引（注：目前安卓手机出现问题，苹果手机却是正常的）

### 期望的结果是什么？

点击D索引时，索引列表显示D高亮，主列表滚动到D置顶，以此类推

### 实际的结果是什么？

点击D索引时，主列表滚动到D置顶，但是索引值变成了C

### 环境信息

发行平台：微信小程序
操作系统：小米10，安卓12 （苹果系统没有出现问题）

**Comment by Moonofweisheng** [comment]
看一下官网的小程序示例有没有问题，目前未提供复现demo，无法复现，关闭此issue。
