### ISSUE TITLE
[Bug 上报] toast没有反应

### ISSUE THREAD

**Issue by lyplay2** [Moonofweisheng/wot-design-uni#779]
### Wot Design Uni 版本号

1.51

### 平台

微信小程序

### 复现Demo地址（如不提供，将被直接关闭）

import { useToast } from '@/uni_modules/wot-design-uni' const toast = useToast()  toast.success('删除成功')

### 重现步骤

import { useToast } from '@/uni_modules/wot-design-uni'
const toast = useToast()

toast.success('删除成功')

### 期望的结果是什么？

弹出 toast

### 实际的结果是什么？

没有 反应

### 环境信息

H5 也不显示

**Comment by Moonofweisheng** [comment]
看文档
