### ISSUE TITLE
[Bug 上报] 请在此填写标题

### ISSUE THREAD

**Issue by LTTGGj** [Moonofweisheng/wot-design-uni#81]
### Wot Design Uni 版本号

0.1.27

### 平台

h5, 微信小程序

### 重现链接

https://wot-design-uni.netlify.app/component/tabs.html

### 重现步骤

<template>
	<view>
		<wd-tabs v-model="cur" :slidable-num="2">
		  <block v-for="(item,index) in arr" :key="index">
			<wd-tab :title="item" :name="item" :disabled="index === 2"></wd-tab>
		  </block>
		</wd-tabs>
		<view style="text-align: center;padding: 24px;">当前选中值{{cur}}</view>
		<wd-button type="success" @click="cur=0">选中选项1</wd-button>
		<wd-button type="warning" @click="cur=1">选中选项2</wd-button>
		<wd-button type="error" @click="cur=2">选中选项3</wd-button>
	</view>
</template>

<script setup>
	import {onLoad,onShow, onReady} from "@dcloudio/uni-app";
	import {ref,reactive,getCurrentInstance} from 'vue';
	const {proxy} = getCurrentInstance(),cur=ref(0),arr=ref(['选项1','选项2','选项3']);
</script>

<style>

</style>

### 期望的结果是什么？

动态切换组件绑定值 修改选中项

### 实际的结果是什么？

选中项无变化

**Comment by Moonofweisheng** [comment]
issue重复
