### ISSUE TITLE
[Bug 上报] 在windows中开发会出现换行符报错

### ISSUE THREAD

**Issue by gjssss** [Moonofweisheng/wot-design-uni#85]
### Wot Design Uni 版本号

0.1.32

### 平台

h5, 微信小程序

### 重现链接

无

### 重现步骤

![image](https://github.com/Moonofweisheng/wot-design-uni/assets/74909529/0f41c0b1-fb61-45b7-9471-b04b2ecefec2)
在windows中会出现eslint与prettier对换行符报错

可能需要更改一下eslint与prettier配置
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/74909529/0828f0a8-153e-4908-8df0-e8971c4cd09d)
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/74909529/92f4f4b5-1b08-4fe3-9c5a-61a64bf0f28d)

### 期望的结果是什么？

无

### 实际的结果是什么？

无

**Comment by Moonofweisheng** [comment]
执行`git config --global core.autocrlf false` 后重新克隆代码，可以解决。

**Comment by gjssss** [comment]
@Moonofweisheng 好滴
