### ISSUE TITLE
Tabs 的v-model 不生效啊

### ISSUE THREAD

**Issue by SunHengX** [Moonofweisheng/wot-design-uni#91]
### Wot Design Uni 版本号

0.1.33

### 平台

h5

### 重现链接

http://localhost:5173

### 重现步骤

这Tabs 的v-model 怎么绑定都是显示的是下标啊,而且下标还不太对
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/63703285/6827ab9a-efde-4d00-882e-a9f53bc071a7)
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/63703285/ff5d2acc-407f-40e4-ac0c-bc107ddfab7a)
而且我传标签名的话,直接报错
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/63703285/2529cd9b-b439-4f88-a9ef-74a4ba0e0000)

### 期望的结果是什么？

v-model的值是tab的name 来决定的

### 实际的结果是什么？

v-model的值是tab的name 来决定的

**Comment by Moonofweisheng** [comment]
0.1.35 已修复修复

**Comment by SunHengX** [comment]
![image](https://github.com/Moonofweisheng/wot-design-uni/assets/63703285/2ceedf59-e80d-4bf6-9361-9d154f5e94c9)
大概一看,我感觉应该是需要这样搞,这样搞的话,你也需要把在emit(click,)之前也要搞一个emit(update)才对

**Comment by SunHengX** [comment]
> 0.1.35 已修复修复

emit(click)之前也要搞一下吧https://github.com/Moonofweisheng/wot-design-uni/issues/91#issuecomment-1773709835

**Comment by Moonofweisheng** [comment]
> > 0.1.35 已修复修复
> 
> emit(click)之前也要搞一下吧[#91 (comment)](https://github.com/Moonofweisheng/wot-design-uni/issues/91#issuecomment-1773709835)

确认是有这个问题，稍微晚会，我回到家后会修复这个问题
