### ISSUE TITLE
日期选择器组件显示事件无法跟随新值动态展示

### ISSUE THREAD

**Issue by yibowangsicn** [Moonofweisheng/wot-design-uni#96]
### Wot Design Uni 版本号

0.1.38

### 平台

微信小程序

### 重现链接

https://wot-design-uni.netlify.app/component/datetime-picker.html

### 重现步骤

选择器绑定change事件 @change="termMobileChange"

//wd-datetime-picker组件
<wd-datetime-picker
          v-model="planStateTime"
          :default-value="defaultValue"
          :minDate="minDate"
          :maxDate="maxDate"
          label="预约时间:"
          @confirm="planStateTimeConfirm"
          @open="openPicker"
        />
        
        
        
let planStateTime = ref(Date.now())//绑定时间
let defaultValue = ref(Date.now())//默认时间
changeDevice(){//切换设备
 通过设备号调用设备信息查询接口（）
 getDviceInfo()
}
getDviceInfo(){
 。。。。。获取设备信息  提取时间  时间为零时区时间 
   planStateTime.value = new Date(res.result.planStateTime).getTime() + 8 * 60 * 60
   isShowPicker.value = false
}

### 期望的结果是什么？

组件展示值跟随更改最新值动态展示

### 实际的结果是什么？

实际是自己获取一个新值   当前时间，并且不会跟随时间动态修改。

**Comment by Moonofweisheng** [comment]
1b13873cef4b7c760698abce7dca500cd548c660
